/*
Crossly Seller API

The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crossly

import (
	"encoding/json"
	"time"
)

// GetMeTemplateResponse struct for GetMeTemplateResponse
type GetMeTemplateResponse struct {
	Id string `json:"id"`
	Brand NullableString `json:"brand,omitempty"`
	Name string `json:"name"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
	UserId string `json:"userId"`
	Condition NullableString `json:"condition,omitempty"`
	Size NullableString `json:"size,omitempty"`
	Material NullableString `json:"material,omitempty"`
	Style NullableString `json:"style,omitempty"`
	Pattern NullableString `json:"pattern,omitempty"`
	Department NullableString `json:"department,omitempty"`
	Gender NullableString `json:"gender,omitempty"`
	ItemType NullableString `json:"itemType,omitempty"`
	SizeSystem NullableString `json:"sizeSystem,omitempty"`
	Color NullableString `json:"color,omitempty"`
	Tags []string `json:"tags,omitempty"`
	Notes NullableString `json:"notes,omitempty"`
	WeightOz NullableFloat32 `json:"weightOz,omitempty"`
	IsDefault bool `json:"isDefault"`
	Description NullableString `json:"description,omitempty"`
	Title NullableString `json:"title,omitempty"`
	Scope string `json:"scope"`
	ShareToken NullableString `json:"shareToken,omitempty"`
	DescriptionVariants []string `json:"descriptionVariants,omitempty"`
	TitleVariants []string `json:"titleVariants,omitempty"`
	DefaultForCategory NullableString `json:"defaultForCategory,omitempty"`
	SortOrder float32 `json:"sortOrder"`
}

// NewGetMeTemplateResponse instantiates a new GetMeTemplateResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetMeTemplateResponse(id string, name string, createdAt time.Time, updatedAt time.Time, userId string, isDefault bool, scope string, sortOrder float32) *GetMeTemplateResponse {
	this := GetMeTemplateResponse{}
	this.Id = id
	this.Name = name
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	this.UserId = userId
	this.IsDefault = isDefault
	this.Scope = scope
	this.SortOrder = sortOrder
	return &this
}

// NewGetMeTemplateResponseWithDefaults instantiates a new GetMeTemplateResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetMeTemplateResponseWithDefaults() *GetMeTemplateResponse {
	this := GetMeTemplateResponse{}
	return &this
}

// GetId returns the Id field value
func (o *GetMeTemplateResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *GetMeTemplateResponse) GetIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *GetMeTemplateResponse) SetId(v string) {
	o.Id = v
}

// GetBrand returns the Brand field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetMeTemplateResponse) GetBrand() string {
	if o == nil || o.Brand.Get() == nil {
		var ret string
		return ret
	}
	return *o.Brand.Get()
}

// GetBrandOk returns a tuple with the Brand field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetMeTemplateResponse) GetBrandOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Brand.Get(), o.Brand.IsSet()
}

// HasBrand returns a boolean if a field has been set.
func (o *GetMeTemplateResponse) HasBrand() bool {
	if o != nil && o.Brand.IsSet() {
		return true
	}

	return false
}

// SetBrand gets a reference to the given NullableString and assigns it to the Brand field.
func (o *GetMeTemplateResponse) SetBrand(v string) {
	o.Brand.Set(&v)
}
// SetBrandNil sets the value for Brand to be an explicit nil
func (o *GetMeTemplateResponse) SetBrandNil() {
	o.Brand.Set(nil)
}

// UnsetBrand ensures that no value is present for Brand, not even an explicit nil
func (o *GetMeTemplateResponse) UnsetBrand() {
	o.Brand.Unset()
}

// GetName returns the Name field value
func (o *GetMeTemplateResponse) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *GetMeTemplateResponse) GetNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *GetMeTemplateResponse) SetName(v string) {
	o.Name = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *GetMeTemplateResponse) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *GetMeTemplateResponse) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *GetMeTemplateResponse) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *GetMeTemplateResponse) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *GetMeTemplateResponse) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *GetMeTemplateResponse) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

// GetUserId returns the UserId field value
func (o *GetMeTemplateResponse) GetUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *GetMeTemplateResponse) GetUserIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *GetMeTemplateResponse) SetUserId(v string) {
	o.UserId = v
}

// GetCondition returns the Condition field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetMeTemplateResponse) GetCondition() string {
	if o == nil || o.Condition.Get() == nil {
		var ret string
		return ret
	}
	return *o.Condition.Get()
}

// GetConditionOk returns a tuple with the Condition field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetMeTemplateResponse) GetConditionOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Condition.Get(), o.Condition.IsSet()
}

// HasCondition returns a boolean if a field has been set.
func (o *GetMeTemplateResponse) HasCondition() bool {
	if o != nil && o.Condition.IsSet() {
		return true
	}

	return false
}

// SetCondition gets a reference to the given NullableString and assigns it to the Condition field.
func (o *GetMeTemplateResponse) SetCondition(v string) {
	o.Condition.Set(&v)
}
// SetConditionNil sets the value for Condition to be an explicit nil
func (o *GetMeTemplateResponse) SetConditionNil() {
	o.Condition.Set(nil)
}

// UnsetCondition ensures that no value is present for Condition, not even an explicit nil
func (o *GetMeTemplateResponse) UnsetCondition() {
	o.Condition.Unset()
}

// GetSize returns the Size field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetMeTemplateResponse) GetSize() string {
	if o == nil || o.Size.Get() == nil {
		var ret string
		return ret
	}
	return *o.Size.Get()
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetMeTemplateResponse) GetSizeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Size.Get(), o.Size.IsSet()
}

// HasSize returns a boolean if a field has been set.
func (o *GetMeTemplateResponse) HasSize() bool {
	if o != nil && o.Size.IsSet() {
		return true
	}

	return false
}

// SetSize gets a reference to the given NullableString and assigns it to the Size field.
func (o *GetMeTemplateResponse) SetSize(v string) {
	o.Size.Set(&v)
}
// SetSizeNil sets the value for Size to be an explicit nil
func (o *GetMeTemplateResponse) SetSizeNil() {
	o.Size.Set(nil)
}

// UnsetSize ensures that no value is present for Size, not even an explicit nil
func (o *GetMeTemplateResponse) UnsetSize() {
	o.Size.Unset()
}

// GetMaterial returns the Material field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetMeTemplateResponse) GetMaterial() string {
	if o == nil || o.Material.Get() == nil {
		var ret string
		return ret
	}
	return *o.Material.Get()
}

// GetMaterialOk returns a tuple with the Material field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetMeTemplateResponse) GetMaterialOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Material.Get(), o.Material.IsSet()
}

// HasMaterial returns a boolean if a field has been set.
func (o *GetMeTemplateResponse) HasMaterial() bool {
	if o != nil && o.Material.IsSet() {
		return true
	}

	return false
}

// SetMaterial gets a reference to the given NullableString and assigns it to the Material field.
func (o *GetMeTemplateResponse) SetMaterial(v string) {
	o.Material.Set(&v)
}
// SetMaterialNil sets the value for Material to be an explicit nil
func (o *GetMeTemplateResponse) SetMaterialNil() {
	o.Material.Set(nil)
}

// UnsetMaterial ensures that no value is present for Material, not even an explicit nil
func (o *GetMeTemplateResponse) UnsetMaterial() {
	o.Material.Unset()
}

// GetStyle returns the Style field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetMeTemplateResponse) GetStyle() string {
	if o == nil || o.Style.Get() == nil {
		var ret string
		return ret
	}
	return *o.Style.Get()
}

// GetStyleOk returns a tuple with the Style field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetMeTemplateResponse) GetStyleOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Style.Get(), o.Style.IsSet()
}

// HasStyle returns a boolean if a field has been set.
func (o *GetMeTemplateResponse) HasStyle() bool {
	if o != nil && o.Style.IsSet() {
		return true
	}

	return false
}

// SetStyle gets a reference to the given NullableString and assigns it to the Style field.
func (o *GetMeTemplateResponse) SetStyle(v string) {
	o.Style.Set(&v)
}
// SetStyleNil sets the value for Style to be an explicit nil
func (o *GetMeTemplateResponse) SetStyleNil() {
	o.Style.Set(nil)
}

// UnsetStyle ensures that no value is present for Style, not even an explicit nil
func (o *GetMeTemplateResponse) UnsetStyle() {
	o.Style.Unset()
}

// GetPattern returns the Pattern field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetMeTemplateResponse) GetPattern() string {
	if o == nil || o.Pattern.Get() == nil {
		var ret string
		return ret
	}
	return *o.Pattern.Get()
}

// GetPatternOk returns a tuple with the Pattern field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetMeTemplateResponse) GetPatternOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Pattern.Get(), o.Pattern.IsSet()
}

// HasPattern returns a boolean if a field has been set.
func (o *GetMeTemplateResponse) HasPattern() bool {
	if o != nil && o.Pattern.IsSet() {
		return true
	}

	return false
}

// SetPattern gets a reference to the given NullableString and assigns it to the Pattern field.
func (o *GetMeTemplateResponse) SetPattern(v string) {
	o.Pattern.Set(&v)
}
// SetPatternNil sets the value for Pattern to be an explicit nil
func (o *GetMeTemplateResponse) SetPatternNil() {
	o.Pattern.Set(nil)
}

// UnsetPattern ensures that no value is present for Pattern, not even an explicit nil
func (o *GetMeTemplateResponse) UnsetPattern() {
	o.Pattern.Unset()
}

// GetDepartment returns the Department field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetMeTemplateResponse) GetDepartment() string {
	if o == nil || o.Department.Get() == nil {
		var ret string
		return ret
	}
	return *o.Department.Get()
}

// GetDepartmentOk returns a tuple with the Department field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetMeTemplateResponse) GetDepartmentOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Department.Get(), o.Department.IsSet()
}

// HasDepartment returns a boolean if a field has been set.
func (o *GetMeTemplateResponse) HasDepartment() bool {
	if o != nil && o.Department.IsSet() {
		return true
	}

	return false
}

// SetDepartment gets a reference to the given NullableString and assigns it to the Department field.
func (o *GetMeTemplateResponse) SetDepartment(v string) {
	o.Department.Set(&v)
}
// SetDepartmentNil sets the value for Department to be an explicit nil
func (o *GetMeTemplateResponse) SetDepartmentNil() {
	o.Department.Set(nil)
}

// UnsetDepartment ensures that no value is present for Department, not even an explicit nil
func (o *GetMeTemplateResponse) UnsetDepartment() {
	o.Department.Unset()
}

// GetGender returns the Gender field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetMeTemplateResponse) GetGender() string {
	if o == nil || o.Gender.Get() == nil {
		var ret string
		return ret
	}
	return *o.Gender.Get()
}

// GetGenderOk returns a tuple with the Gender field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetMeTemplateResponse) GetGenderOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Gender.Get(), o.Gender.IsSet()
}

// HasGender returns a boolean if a field has been set.
func (o *GetMeTemplateResponse) HasGender() bool {
	if o != nil && o.Gender.IsSet() {
		return true
	}

	return false
}

// SetGender gets a reference to the given NullableString and assigns it to the Gender field.
func (o *GetMeTemplateResponse) SetGender(v string) {
	o.Gender.Set(&v)
}
// SetGenderNil sets the value for Gender to be an explicit nil
func (o *GetMeTemplateResponse) SetGenderNil() {
	o.Gender.Set(nil)
}

// UnsetGender ensures that no value is present for Gender, not even an explicit nil
func (o *GetMeTemplateResponse) UnsetGender() {
	o.Gender.Unset()
}

// GetItemType returns the ItemType field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetMeTemplateResponse) GetItemType() string {
	if o == nil || o.ItemType.Get() == nil {
		var ret string
		return ret
	}
	return *o.ItemType.Get()
}

// GetItemTypeOk returns a tuple with the ItemType field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetMeTemplateResponse) GetItemTypeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.ItemType.Get(), o.ItemType.IsSet()
}

// HasItemType returns a boolean if a field has been set.
func (o *GetMeTemplateResponse) HasItemType() bool {
	if o != nil && o.ItemType.IsSet() {
		return true
	}

	return false
}

// SetItemType gets a reference to the given NullableString and assigns it to the ItemType field.
func (o *GetMeTemplateResponse) SetItemType(v string) {
	o.ItemType.Set(&v)
}
// SetItemTypeNil sets the value for ItemType to be an explicit nil
func (o *GetMeTemplateResponse) SetItemTypeNil() {
	o.ItemType.Set(nil)
}

// UnsetItemType ensures that no value is present for ItemType, not even an explicit nil
func (o *GetMeTemplateResponse) UnsetItemType() {
	o.ItemType.Unset()
}

// GetSizeSystem returns the SizeSystem field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetMeTemplateResponse) GetSizeSystem() string {
	if o == nil || o.SizeSystem.Get() == nil {
		var ret string
		return ret
	}
	return *o.SizeSystem.Get()
}

// GetSizeSystemOk returns a tuple with the SizeSystem field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetMeTemplateResponse) GetSizeSystemOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.SizeSystem.Get(), o.SizeSystem.IsSet()
}

// HasSizeSystem returns a boolean if a field has been set.
func (o *GetMeTemplateResponse) HasSizeSystem() bool {
	if o != nil && o.SizeSystem.IsSet() {
		return true
	}

	return false
}

// SetSizeSystem gets a reference to the given NullableString and assigns it to the SizeSystem field.
func (o *GetMeTemplateResponse) SetSizeSystem(v string) {
	o.SizeSystem.Set(&v)
}
// SetSizeSystemNil sets the value for SizeSystem to be an explicit nil
func (o *GetMeTemplateResponse) SetSizeSystemNil() {
	o.SizeSystem.Set(nil)
}

// UnsetSizeSystem ensures that no value is present for SizeSystem, not even an explicit nil
func (o *GetMeTemplateResponse) UnsetSizeSystem() {
	o.SizeSystem.Unset()
}

// GetColor returns the Color field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetMeTemplateResponse) GetColor() string {
	if o == nil || o.Color.Get() == nil {
		var ret string
		return ret
	}
	return *o.Color.Get()
}

// GetColorOk returns a tuple with the Color field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetMeTemplateResponse) GetColorOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Color.Get(), o.Color.IsSet()
}

// HasColor returns a boolean if a field has been set.
func (o *GetMeTemplateResponse) HasColor() bool {
	if o != nil && o.Color.IsSet() {
		return true
	}

	return false
}

// SetColor gets a reference to the given NullableString and assigns it to the Color field.
func (o *GetMeTemplateResponse) SetColor(v string) {
	o.Color.Set(&v)
}
// SetColorNil sets the value for Color to be an explicit nil
func (o *GetMeTemplateResponse) SetColorNil() {
	o.Color.Set(nil)
}

// UnsetColor ensures that no value is present for Color, not even an explicit nil
func (o *GetMeTemplateResponse) UnsetColor() {
	o.Color.Unset()
}

// GetTags returns the Tags field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetMeTemplateResponse) GetTags() []string {
	if o == nil  {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetMeTemplateResponse) GetTagsOk() ([]string, bool) {
	if o == nil || o.Tags == nil {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *GetMeTemplateResponse) HasTags() bool {
	if o != nil && o.Tags != nil {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *GetMeTemplateResponse) SetTags(v []string) {
	o.Tags = v
}

// GetNotes returns the Notes field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetMeTemplateResponse) GetNotes() string {
	if o == nil || o.Notes.Get() == nil {
		var ret string
		return ret
	}
	return *o.Notes.Get()
}

// GetNotesOk returns a tuple with the Notes field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetMeTemplateResponse) GetNotesOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Notes.Get(), o.Notes.IsSet()
}

// HasNotes returns a boolean if a field has been set.
func (o *GetMeTemplateResponse) HasNotes() bool {
	if o != nil && o.Notes.IsSet() {
		return true
	}

	return false
}

// SetNotes gets a reference to the given NullableString and assigns it to the Notes field.
func (o *GetMeTemplateResponse) SetNotes(v string) {
	o.Notes.Set(&v)
}
// SetNotesNil sets the value for Notes to be an explicit nil
func (o *GetMeTemplateResponse) SetNotesNil() {
	o.Notes.Set(nil)
}

// UnsetNotes ensures that no value is present for Notes, not even an explicit nil
func (o *GetMeTemplateResponse) UnsetNotes() {
	o.Notes.Unset()
}

// GetWeightOz returns the WeightOz field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetMeTemplateResponse) GetWeightOz() float32 {
	if o == nil || o.WeightOz.Get() == nil {
		var ret float32
		return ret
	}
	return *o.WeightOz.Get()
}

// GetWeightOzOk returns a tuple with the WeightOz field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetMeTemplateResponse) GetWeightOzOk() (*float32, bool) {
	if o == nil  {
		return nil, false
	}
	return o.WeightOz.Get(), o.WeightOz.IsSet()
}

// HasWeightOz returns a boolean if a field has been set.
func (o *GetMeTemplateResponse) HasWeightOz() bool {
	if o != nil && o.WeightOz.IsSet() {
		return true
	}

	return false
}

// SetWeightOz gets a reference to the given NullableFloat32 and assigns it to the WeightOz field.
func (o *GetMeTemplateResponse) SetWeightOz(v float32) {
	o.WeightOz.Set(&v)
}
// SetWeightOzNil sets the value for WeightOz to be an explicit nil
func (o *GetMeTemplateResponse) SetWeightOzNil() {
	o.WeightOz.Set(nil)
}

// UnsetWeightOz ensures that no value is present for WeightOz, not even an explicit nil
func (o *GetMeTemplateResponse) UnsetWeightOz() {
	o.WeightOz.Unset()
}

// GetIsDefault returns the IsDefault field value
func (o *GetMeTemplateResponse) GetIsDefault() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsDefault
}

// GetIsDefaultOk returns a tuple with the IsDefault field value
// and a boolean to check if the value has been set.
func (o *GetMeTemplateResponse) GetIsDefaultOk() (*bool, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.IsDefault, true
}

// SetIsDefault sets field value
func (o *GetMeTemplateResponse) SetIsDefault(v bool) {
	o.IsDefault = v
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetMeTemplateResponse) GetDescription() string {
	if o == nil || o.Description.Get() == nil {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetMeTemplateResponse) GetDescriptionOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *GetMeTemplateResponse) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *GetMeTemplateResponse) SetDescription(v string) {
	o.Description.Set(&v)
}
// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *GetMeTemplateResponse) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *GetMeTemplateResponse) UnsetDescription() {
	o.Description.Unset()
}

// GetTitle returns the Title field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetMeTemplateResponse) GetTitle() string {
	if o == nil || o.Title.Get() == nil {
		var ret string
		return ret
	}
	return *o.Title.Get()
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetMeTemplateResponse) GetTitleOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Title.Get(), o.Title.IsSet()
}

// HasTitle returns a boolean if a field has been set.
func (o *GetMeTemplateResponse) HasTitle() bool {
	if o != nil && o.Title.IsSet() {
		return true
	}

	return false
}

// SetTitle gets a reference to the given NullableString and assigns it to the Title field.
func (o *GetMeTemplateResponse) SetTitle(v string) {
	o.Title.Set(&v)
}
// SetTitleNil sets the value for Title to be an explicit nil
func (o *GetMeTemplateResponse) SetTitleNil() {
	o.Title.Set(nil)
}

// UnsetTitle ensures that no value is present for Title, not even an explicit nil
func (o *GetMeTemplateResponse) UnsetTitle() {
	o.Title.Unset()
}

// GetScope returns the Scope field value
func (o *GetMeTemplateResponse) GetScope() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Scope
}

// GetScopeOk returns a tuple with the Scope field value
// and a boolean to check if the value has been set.
func (o *GetMeTemplateResponse) GetScopeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Scope, true
}

// SetScope sets field value
func (o *GetMeTemplateResponse) SetScope(v string) {
	o.Scope = v
}

// GetShareToken returns the ShareToken field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetMeTemplateResponse) GetShareToken() string {
	if o == nil || o.ShareToken.Get() == nil {
		var ret string
		return ret
	}
	return *o.ShareToken.Get()
}

// GetShareTokenOk returns a tuple with the ShareToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetMeTemplateResponse) GetShareTokenOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.ShareToken.Get(), o.ShareToken.IsSet()
}

// HasShareToken returns a boolean if a field has been set.
func (o *GetMeTemplateResponse) HasShareToken() bool {
	if o != nil && o.ShareToken.IsSet() {
		return true
	}

	return false
}

// SetShareToken gets a reference to the given NullableString and assigns it to the ShareToken field.
func (o *GetMeTemplateResponse) SetShareToken(v string) {
	o.ShareToken.Set(&v)
}
// SetShareTokenNil sets the value for ShareToken to be an explicit nil
func (o *GetMeTemplateResponse) SetShareTokenNil() {
	o.ShareToken.Set(nil)
}

// UnsetShareToken ensures that no value is present for ShareToken, not even an explicit nil
func (o *GetMeTemplateResponse) UnsetShareToken() {
	o.ShareToken.Unset()
}

// GetDescriptionVariants returns the DescriptionVariants field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetMeTemplateResponse) GetDescriptionVariants() []string {
	if o == nil  {
		var ret []string
		return ret
	}
	return o.DescriptionVariants
}

// GetDescriptionVariantsOk returns a tuple with the DescriptionVariants field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetMeTemplateResponse) GetDescriptionVariantsOk() ([]string, bool) {
	if o == nil || o.DescriptionVariants == nil {
		return nil, false
	}
	return o.DescriptionVariants, true
}

// HasDescriptionVariants returns a boolean if a field has been set.
func (o *GetMeTemplateResponse) HasDescriptionVariants() bool {
	if o != nil && o.DescriptionVariants != nil {
		return true
	}

	return false
}

// SetDescriptionVariants gets a reference to the given []string and assigns it to the DescriptionVariants field.
func (o *GetMeTemplateResponse) SetDescriptionVariants(v []string) {
	o.DescriptionVariants = v
}

// GetTitleVariants returns the TitleVariants field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetMeTemplateResponse) GetTitleVariants() []string {
	if o == nil  {
		var ret []string
		return ret
	}
	return o.TitleVariants
}

// GetTitleVariantsOk returns a tuple with the TitleVariants field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetMeTemplateResponse) GetTitleVariantsOk() ([]string, bool) {
	if o == nil || o.TitleVariants == nil {
		return nil, false
	}
	return o.TitleVariants, true
}

// HasTitleVariants returns a boolean if a field has been set.
func (o *GetMeTemplateResponse) HasTitleVariants() bool {
	if o != nil && o.TitleVariants != nil {
		return true
	}

	return false
}

// SetTitleVariants gets a reference to the given []string and assigns it to the TitleVariants field.
func (o *GetMeTemplateResponse) SetTitleVariants(v []string) {
	o.TitleVariants = v
}

// GetDefaultForCategory returns the DefaultForCategory field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetMeTemplateResponse) GetDefaultForCategory() string {
	if o == nil || o.DefaultForCategory.Get() == nil {
		var ret string
		return ret
	}
	return *o.DefaultForCategory.Get()
}

// GetDefaultForCategoryOk returns a tuple with the DefaultForCategory field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetMeTemplateResponse) GetDefaultForCategoryOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.DefaultForCategory.Get(), o.DefaultForCategory.IsSet()
}

// HasDefaultForCategory returns a boolean if a field has been set.
func (o *GetMeTemplateResponse) HasDefaultForCategory() bool {
	if o != nil && o.DefaultForCategory.IsSet() {
		return true
	}

	return false
}

// SetDefaultForCategory gets a reference to the given NullableString and assigns it to the DefaultForCategory field.
func (o *GetMeTemplateResponse) SetDefaultForCategory(v string) {
	o.DefaultForCategory.Set(&v)
}
// SetDefaultForCategoryNil sets the value for DefaultForCategory to be an explicit nil
func (o *GetMeTemplateResponse) SetDefaultForCategoryNil() {
	o.DefaultForCategory.Set(nil)
}

// UnsetDefaultForCategory ensures that no value is present for DefaultForCategory, not even an explicit nil
func (o *GetMeTemplateResponse) UnsetDefaultForCategory() {
	o.DefaultForCategory.Unset()
}

// GetSortOrder returns the SortOrder field value
func (o *GetMeTemplateResponse) GetSortOrder() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.SortOrder
}

// GetSortOrderOk returns a tuple with the SortOrder field value
// and a boolean to check if the value has been set.
func (o *GetMeTemplateResponse) GetSortOrderOk() (*float32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.SortOrder, true
}

// SetSortOrder sets field value
func (o *GetMeTemplateResponse) SetSortOrder(v float32) {
	o.SortOrder = v
}

func (o GetMeTemplateResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	if o.Brand.IsSet() {
		toSerialize["brand"] = o.Brand.Get()
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if true {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	if true {
		toSerialize["userId"] = o.UserId
	}
	if o.Condition.IsSet() {
		toSerialize["condition"] = o.Condition.Get()
	}
	if o.Size.IsSet() {
		toSerialize["size"] = o.Size.Get()
	}
	if o.Material.IsSet() {
		toSerialize["material"] = o.Material.Get()
	}
	if o.Style.IsSet() {
		toSerialize["style"] = o.Style.Get()
	}
	if o.Pattern.IsSet() {
		toSerialize["pattern"] = o.Pattern.Get()
	}
	if o.Department.IsSet() {
		toSerialize["department"] = o.Department.Get()
	}
	if o.Gender.IsSet() {
		toSerialize["gender"] = o.Gender.Get()
	}
	if o.ItemType.IsSet() {
		toSerialize["itemType"] = o.ItemType.Get()
	}
	if o.SizeSystem.IsSet() {
		toSerialize["sizeSystem"] = o.SizeSystem.Get()
	}
	if o.Color.IsSet() {
		toSerialize["color"] = o.Color.Get()
	}
	if o.Tags != nil {
		toSerialize["tags"] = o.Tags
	}
	if o.Notes.IsSet() {
		toSerialize["notes"] = o.Notes.Get()
	}
	if o.WeightOz.IsSet() {
		toSerialize["weightOz"] = o.WeightOz.Get()
	}
	if true {
		toSerialize["isDefault"] = o.IsDefault
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if o.Title.IsSet() {
		toSerialize["title"] = o.Title.Get()
	}
	if true {
		toSerialize["scope"] = o.Scope
	}
	if o.ShareToken.IsSet() {
		toSerialize["shareToken"] = o.ShareToken.Get()
	}
	if o.DescriptionVariants != nil {
		toSerialize["descriptionVariants"] = o.DescriptionVariants
	}
	if o.TitleVariants != nil {
		toSerialize["titleVariants"] = o.TitleVariants
	}
	if o.DefaultForCategory.IsSet() {
		toSerialize["defaultForCategory"] = o.DefaultForCategory.Get()
	}
	if true {
		toSerialize["sortOrder"] = o.SortOrder
	}
	return json.Marshal(toSerialize)
}

type NullableGetMeTemplateResponse struct {
	value *GetMeTemplateResponse
	isSet bool
}

func (v NullableGetMeTemplateResponse) Get() *GetMeTemplateResponse {
	return v.value
}

func (v *NullableGetMeTemplateResponse) Set(val *GetMeTemplateResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetMeTemplateResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetMeTemplateResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetMeTemplateResponse(val *GetMeTemplateResponse) *NullableGetMeTemplateResponse {
	return &NullableGetMeTemplateResponse{value: val, isSet: true}
}

func (v NullableGetMeTemplateResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetMeTemplateResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


