/*
Crossly Seller API

The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crossly

import (
	"encoding/json"
	"time"
)

// GetMarketProductResponseProduct struct for GetMarketProductResponseProduct
type GetMarketProductResponseProduct struct {
	Id string `json:"id"`
	Brand NullableString `json:"brand,omitempty"`
	Name string `json:"name"`
	CreatedAt time.Time `json:"createdAt"`
	Status string `json:"status"`
	RetailCents NullableFloat32 `json:"retailCents,omitempty"`
	CategorySlug string `json:"categorySlug"`
	ExternalId NullableString `json:"externalId,omitempty"`
	ImageUrl NullableString `json:"imageUrl,omitempty"`
	Model NullableString `json:"model,omitempty"`
	Colorway NullableString `json:"colorway,omitempty"`
	StyleCode NullableString `json:"styleCode,omitempty"`
	ReleaseDate NullableString `json:"releaseDate,omitempty"`
	SubmittedByUserId NullableString `json:"submittedByUserId,omitempty"`
	ApprovedByUserId NullableString `json:"approvedByUserId,omitempty"`
	ApprovedAt NullableTime `json:"approvedAt,omitempty"`
	RejectionReason NullableString `json:"rejectionReason,omitempty"`
	ProposedVariants []GetMarketProductResponseProductProposedVariants `json:"proposedVariants"`
	Verification map[string]interface{} `json:"verification"`
	AiVerdict map[string]interface{} `json:"aiVerdict,omitempty"`
	SubmissionSource NullableString `json:"submissionSource,omitempty"`
	DuplicateOfSkuId NullableString `json:"duplicateOfSkuId,omitempty"`
	PreferredProviderSlug NullableString `json:"preferredProviderSlug,omitempty"`
	AllowPreBid bool `json:"allowPreBid"`
	PreBidOpensAt NullableTime `json:"preBidOpensAt,omitempty"`
	Featured bool `json:"featured"`
	ExternalSource NullableString `json:"externalSource,omitempty"`
	ExternalSyncedAt NullableTime `json:"externalSyncedAt,omitempty"`
	GradedGradeKeys []string `json:"gradedGradeKeys"`
	LowestAskCents NullableFloat32 `json:"lowestAskCents,omitempty"`
	HighestBidCents NullableFloat32 `json:"highestBidCents,omitempty"`
	LastSaleCents NullableFloat32 `json:"lastSaleCents,omitempty"`
	TradesCount float32 `json:"tradesCount"`
}

// NewGetMarketProductResponseProduct instantiates a new GetMarketProductResponseProduct object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetMarketProductResponseProduct(id string, name string, createdAt time.Time, status string, categorySlug string, proposedVariants []GetMarketProductResponseProductProposedVariants, verification map[string]interface{}, allowPreBid bool, featured bool, gradedGradeKeys []string, tradesCount float32) *GetMarketProductResponseProduct {
	this := GetMarketProductResponseProduct{}
	this.Id = id
	this.Name = name
	this.CreatedAt = createdAt
	this.Status = status
	this.CategorySlug = categorySlug
	this.ProposedVariants = proposedVariants
	this.Verification = verification
	this.AllowPreBid = allowPreBid
	this.Featured = featured
	this.GradedGradeKeys = gradedGradeKeys
	this.TradesCount = tradesCount
	return &this
}

// NewGetMarketProductResponseProductWithDefaults instantiates a new GetMarketProductResponseProduct object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetMarketProductResponseProductWithDefaults() *GetMarketProductResponseProduct {
	this := GetMarketProductResponseProduct{}
	return &this
}

// GetId returns the Id field value
func (o *GetMarketProductResponseProduct) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *GetMarketProductResponseProduct) GetIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *GetMarketProductResponseProduct) SetId(v string) {
	o.Id = v
}

// GetBrand returns the Brand field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetMarketProductResponseProduct) GetBrand() string {
	if o == nil || o.Brand.Get() == nil {
		var ret string
		return ret
	}
	return *o.Brand.Get()
}

// GetBrandOk returns a tuple with the Brand field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetMarketProductResponseProduct) GetBrandOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Brand.Get(), o.Brand.IsSet()
}

// HasBrand returns a boolean if a field has been set.
func (o *GetMarketProductResponseProduct) HasBrand() bool {
	if o != nil && o.Brand.IsSet() {
		return true
	}

	return false
}

// SetBrand gets a reference to the given NullableString and assigns it to the Brand field.
func (o *GetMarketProductResponseProduct) SetBrand(v string) {
	o.Brand.Set(&v)
}
// SetBrandNil sets the value for Brand to be an explicit nil
func (o *GetMarketProductResponseProduct) SetBrandNil() {
	o.Brand.Set(nil)
}

// UnsetBrand ensures that no value is present for Brand, not even an explicit nil
func (o *GetMarketProductResponseProduct) UnsetBrand() {
	o.Brand.Unset()
}

// GetName returns the Name field value
func (o *GetMarketProductResponseProduct) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *GetMarketProductResponseProduct) GetNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *GetMarketProductResponseProduct) SetName(v string) {
	o.Name = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *GetMarketProductResponseProduct) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *GetMarketProductResponseProduct) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *GetMarketProductResponseProduct) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetStatus returns the Status field value
func (o *GetMarketProductResponseProduct) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *GetMarketProductResponseProduct) GetStatusOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *GetMarketProductResponseProduct) SetStatus(v string) {
	o.Status = v
}

// GetRetailCents returns the RetailCents field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetMarketProductResponseProduct) GetRetailCents() float32 {
	if o == nil || o.RetailCents.Get() == nil {
		var ret float32
		return ret
	}
	return *o.RetailCents.Get()
}

// GetRetailCentsOk returns a tuple with the RetailCents field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetMarketProductResponseProduct) GetRetailCentsOk() (*float32, bool) {
	if o == nil  {
		return nil, false
	}
	return o.RetailCents.Get(), o.RetailCents.IsSet()
}

// HasRetailCents returns a boolean if a field has been set.
func (o *GetMarketProductResponseProduct) HasRetailCents() bool {
	if o != nil && o.RetailCents.IsSet() {
		return true
	}

	return false
}

// SetRetailCents gets a reference to the given NullableFloat32 and assigns it to the RetailCents field.
func (o *GetMarketProductResponseProduct) SetRetailCents(v float32) {
	o.RetailCents.Set(&v)
}
// SetRetailCentsNil sets the value for RetailCents to be an explicit nil
func (o *GetMarketProductResponseProduct) SetRetailCentsNil() {
	o.RetailCents.Set(nil)
}

// UnsetRetailCents ensures that no value is present for RetailCents, not even an explicit nil
func (o *GetMarketProductResponseProduct) UnsetRetailCents() {
	o.RetailCents.Unset()
}

// GetCategorySlug returns the CategorySlug field value
func (o *GetMarketProductResponseProduct) GetCategorySlug() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CategorySlug
}

// GetCategorySlugOk returns a tuple with the CategorySlug field value
// and a boolean to check if the value has been set.
func (o *GetMarketProductResponseProduct) GetCategorySlugOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.CategorySlug, true
}

// SetCategorySlug sets field value
func (o *GetMarketProductResponseProduct) SetCategorySlug(v string) {
	o.CategorySlug = v
}

// GetExternalId returns the ExternalId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetMarketProductResponseProduct) GetExternalId() string {
	if o == nil || o.ExternalId.Get() == nil {
		var ret string
		return ret
	}
	return *o.ExternalId.Get()
}

// GetExternalIdOk returns a tuple with the ExternalId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetMarketProductResponseProduct) GetExternalIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.ExternalId.Get(), o.ExternalId.IsSet()
}

// HasExternalId returns a boolean if a field has been set.
func (o *GetMarketProductResponseProduct) HasExternalId() bool {
	if o != nil && o.ExternalId.IsSet() {
		return true
	}

	return false
}

// SetExternalId gets a reference to the given NullableString and assigns it to the ExternalId field.
func (o *GetMarketProductResponseProduct) SetExternalId(v string) {
	o.ExternalId.Set(&v)
}
// SetExternalIdNil sets the value for ExternalId to be an explicit nil
func (o *GetMarketProductResponseProduct) SetExternalIdNil() {
	o.ExternalId.Set(nil)
}

// UnsetExternalId ensures that no value is present for ExternalId, not even an explicit nil
func (o *GetMarketProductResponseProduct) UnsetExternalId() {
	o.ExternalId.Unset()
}

// GetImageUrl returns the ImageUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetMarketProductResponseProduct) GetImageUrl() string {
	if o == nil || o.ImageUrl.Get() == nil {
		var ret string
		return ret
	}
	return *o.ImageUrl.Get()
}

// GetImageUrlOk returns a tuple with the ImageUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetMarketProductResponseProduct) GetImageUrlOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.ImageUrl.Get(), o.ImageUrl.IsSet()
}

// HasImageUrl returns a boolean if a field has been set.
func (o *GetMarketProductResponseProduct) HasImageUrl() bool {
	if o != nil && o.ImageUrl.IsSet() {
		return true
	}

	return false
}

// SetImageUrl gets a reference to the given NullableString and assigns it to the ImageUrl field.
func (o *GetMarketProductResponseProduct) SetImageUrl(v string) {
	o.ImageUrl.Set(&v)
}
// SetImageUrlNil sets the value for ImageUrl to be an explicit nil
func (o *GetMarketProductResponseProduct) SetImageUrlNil() {
	o.ImageUrl.Set(nil)
}

// UnsetImageUrl ensures that no value is present for ImageUrl, not even an explicit nil
func (o *GetMarketProductResponseProduct) UnsetImageUrl() {
	o.ImageUrl.Unset()
}

// GetModel returns the Model field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetMarketProductResponseProduct) GetModel() string {
	if o == nil || o.Model.Get() == nil {
		var ret string
		return ret
	}
	return *o.Model.Get()
}

// GetModelOk returns a tuple with the Model field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetMarketProductResponseProduct) GetModelOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Model.Get(), o.Model.IsSet()
}

// HasModel returns a boolean if a field has been set.
func (o *GetMarketProductResponseProduct) HasModel() bool {
	if o != nil && o.Model.IsSet() {
		return true
	}

	return false
}

// SetModel gets a reference to the given NullableString and assigns it to the Model field.
func (o *GetMarketProductResponseProduct) SetModel(v string) {
	o.Model.Set(&v)
}
// SetModelNil sets the value for Model to be an explicit nil
func (o *GetMarketProductResponseProduct) SetModelNil() {
	o.Model.Set(nil)
}

// UnsetModel ensures that no value is present for Model, not even an explicit nil
func (o *GetMarketProductResponseProduct) UnsetModel() {
	o.Model.Unset()
}

// GetColorway returns the Colorway field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetMarketProductResponseProduct) GetColorway() string {
	if o == nil || o.Colorway.Get() == nil {
		var ret string
		return ret
	}
	return *o.Colorway.Get()
}

// GetColorwayOk returns a tuple with the Colorway field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetMarketProductResponseProduct) GetColorwayOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Colorway.Get(), o.Colorway.IsSet()
}

// HasColorway returns a boolean if a field has been set.
func (o *GetMarketProductResponseProduct) HasColorway() bool {
	if o != nil && o.Colorway.IsSet() {
		return true
	}

	return false
}

// SetColorway gets a reference to the given NullableString and assigns it to the Colorway field.
func (o *GetMarketProductResponseProduct) SetColorway(v string) {
	o.Colorway.Set(&v)
}
// SetColorwayNil sets the value for Colorway to be an explicit nil
func (o *GetMarketProductResponseProduct) SetColorwayNil() {
	o.Colorway.Set(nil)
}

// UnsetColorway ensures that no value is present for Colorway, not even an explicit nil
func (o *GetMarketProductResponseProduct) UnsetColorway() {
	o.Colorway.Unset()
}

// GetStyleCode returns the StyleCode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetMarketProductResponseProduct) GetStyleCode() string {
	if o == nil || o.StyleCode.Get() == nil {
		var ret string
		return ret
	}
	return *o.StyleCode.Get()
}

// GetStyleCodeOk returns a tuple with the StyleCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetMarketProductResponseProduct) GetStyleCodeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.StyleCode.Get(), o.StyleCode.IsSet()
}

// HasStyleCode returns a boolean if a field has been set.
func (o *GetMarketProductResponseProduct) HasStyleCode() bool {
	if o != nil && o.StyleCode.IsSet() {
		return true
	}

	return false
}

// SetStyleCode gets a reference to the given NullableString and assigns it to the StyleCode field.
func (o *GetMarketProductResponseProduct) SetStyleCode(v string) {
	o.StyleCode.Set(&v)
}
// SetStyleCodeNil sets the value for StyleCode to be an explicit nil
func (o *GetMarketProductResponseProduct) SetStyleCodeNil() {
	o.StyleCode.Set(nil)
}

// UnsetStyleCode ensures that no value is present for StyleCode, not even an explicit nil
func (o *GetMarketProductResponseProduct) UnsetStyleCode() {
	o.StyleCode.Unset()
}

// GetReleaseDate returns the ReleaseDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetMarketProductResponseProduct) GetReleaseDate() string {
	if o == nil || o.ReleaseDate.Get() == nil {
		var ret string
		return ret
	}
	return *o.ReleaseDate.Get()
}

// GetReleaseDateOk returns a tuple with the ReleaseDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetMarketProductResponseProduct) GetReleaseDateOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.ReleaseDate.Get(), o.ReleaseDate.IsSet()
}

// HasReleaseDate returns a boolean if a field has been set.
func (o *GetMarketProductResponseProduct) HasReleaseDate() bool {
	if o != nil && o.ReleaseDate.IsSet() {
		return true
	}

	return false
}

// SetReleaseDate gets a reference to the given NullableString and assigns it to the ReleaseDate field.
func (o *GetMarketProductResponseProduct) SetReleaseDate(v string) {
	o.ReleaseDate.Set(&v)
}
// SetReleaseDateNil sets the value for ReleaseDate to be an explicit nil
func (o *GetMarketProductResponseProduct) SetReleaseDateNil() {
	o.ReleaseDate.Set(nil)
}

// UnsetReleaseDate ensures that no value is present for ReleaseDate, not even an explicit nil
func (o *GetMarketProductResponseProduct) UnsetReleaseDate() {
	o.ReleaseDate.Unset()
}

// GetSubmittedByUserId returns the SubmittedByUserId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetMarketProductResponseProduct) GetSubmittedByUserId() string {
	if o == nil || o.SubmittedByUserId.Get() == nil {
		var ret string
		return ret
	}
	return *o.SubmittedByUserId.Get()
}

// GetSubmittedByUserIdOk returns a tuple with the SubmittedByUserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetMarketProductResponseProduct) GetSubmittedByUserIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.SubmittedByUserId.Get(), o.SubmittedByUserId.IsSet()
}

// HasSubmittedByUserId returns a boolean if a field has been set.
func (o *GetMarketProductResponseProduct) HasSubmittedByUserId() bool {
	if o != nil && o.SubmittedByUserId.IsSet() {
		return true
	}

	return false
}

// SetSubmittedByUserId gets a reference to the given NullableString and assigns it to the SubmittedByUserId field.
func (o *GetMarketProductResponseProduct) SetSubmittedByUserId(v string) {
	o.SubmittedByUserId.Set(&v)
}
// SetSubmittedByUserIdNil sets the value for SubmittedByUserId to be an explicit nil
func (o *GetMarketProductResponseProduct) SetSubmittedByUserIdNil() {
	o.SubmittedByUserId.Set(nil)
}

// UnsetSubmittedByUserId ensures that no value is present for SubmittedByUserId, not even an explicit nil
func (o *GetMarketProductResponseProduct) UnsetSubmittedByUserId() {
	o.SubmittedByUserId.Unset()
}

// GetApprovedByUserId returns the ApprovedByUserId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetMarketProductResponseProduct) GetApprovedByUserId() string {
	if o == nil || o.ApprovedByUserId.Get() == nil {
		var ret string
		return ret
	}
	return *o.ApprovedByUserId.Get()
}

// GetApprovedByUserIdOk returns a tuple with the ApprovedByUserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetMarketProductResponseProduct) GetApprovedByUserIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.ApprovedByUserId.Get(), o.ApprovedByUserId.IsSet()
}

// HasApprovedByUserId returns a boolean if a field has been set.
func (o *GetMarketProductResponseProduct) HasApprovedByUserId() bool {
	if o != nil && o.ApprovedByUserId.IsSet() {
		return true
	}

	return false
}

// SetApprovedByUserId gets a reference to the given NullableString and assigns it to the ApprovedByUserId field.
func (o *GetMarketProductResponseProduct) SetApprovedByUserId(v string) {
	o.ApprovedByUserId.Set(&v)
}
// SetApprovedByUserIdNil sets the value for ApprovedByUserId to be an explicit nil
func (o *GetMarketProductResponseProduct) SetApprovedByUserIdNil() {
	o.ApprovedByUserId.Set(nil)
}

// UnsetApprovedByUserId ensures that no value is present for ApprovedByUserId, not even an explicit nil
func (o *GetMarketProductResponseProduct) UnsetApprovedByUserId() {
	o.ApprovedByUserId.Unset()
}

// GetApprovedAt returns the ApprovedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetMarketProductResponseProduct) GetApprovedAt() time.Time {
	if o == nil || o.ApprovedAt.Get() == nil {
		var ret time.Time
		return ret
	}
	return *o.ApprovedAt.Get()
}

// GetApprovedAtOk returns a tuple with the ApprovedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetMarketProductResponseProduct) GetApprovedAtOk() (*time.Time, bool) {
	if o == nil  {
		return nil, false
	}
	return o.ApprovedAt.Get(), o.ApprovedAt.IsSet()
}

// HasApprovedAt returns a boolean if a field has been set.
func (o *GetMarketProductResponseProduct) HasApprovedAt() bool {
	if o != nil && o.ApprovedAt.IsSet() {
		return true
	}

	return false
}

// SetApprovedAt gets a reference to the given NullableTime and assigns it to the ApprovedAt field.
func (o *GetMarketProductResponseProduct) SetApprovedAt(v time.Time) {
	o.ApprovedAt.Set(&v)
}
// SetApprovedAtNil sets the value for ApprovedAt to be an explicit nil
func (o *GetMarketProductResponseProduct) SetApprovedAtNil() {
	o.ApprovedAt.Set(nil)
}

// UnsetApprovedAt ensures that no value is present for ApprovedAt, not even an explicit nil
func (o *GetMarketProductResponseProduct) UnsetApprovedAt() {
	o.ApprovedAt.Unset()
}

// GetRejectionReason returns the RejectionReason field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetMarketProductResponseProduct) GetRejectionReason() string {
	if o == nil || o.RejectionReason.Get() == nil {
		var ret string
		return ret
	}
	return *o.RejectionReason.Get()
}

// GetRejectionReasonOk returns a tuple with the RejectionReason field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetMarketProductResponseProduct) GetRejectionReasonOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.RejectionReason.Get(), o.RejectionReason.IsSet()
}

// HasRejectionReason returns a boolean if a field has been set.
func (o *GetMarketProductResponseProduct) HasRejectionReason() bool {
	if o != nil && o.RejectionReason.IsSet() {
		return true
	}

	return false
}

// SetRejectionReason gets a reference to the given NullableString and assigns it to the RejectionReason field.
func (o *GetMarketProductResponseProduct) SetRejectionReason(v string) {
	o.RejectionReason.Set(&v)
}
// SetRejectionReasonNil sets the value for RejectionReason to be an explicit nil
func (o *GetMarketProductResponseProduct) SetRejectionReasonNil() {
	o.RejectionReason.Set(nil)
}

// UnsetRejectionReason ensures that no value is present for RejectionReason, not even an explicit nil
func (o *GetMarketProductResponseProduct) UnsetRejectionReason() {
	o.RejectionReason.Unset()
}

// GetProposedVariants returns the ProposedVariants field value
func (o *GetMarketProductResponseProduct) GetProposedVariants() []GetMarketProductResponseProductProposedVariants {
	if o == nil {
		var ret []GetMarketProductResponseProductProposedVariants
		return ret
	}

	return o.ProposedVariants
}

// GetProposedVariantsOk returns a tuple with the ProposedVariants field value
// and a boolean to check if the value has been set.
func (o *GetMarketProductResponseProduct) GetProposedVariantsOk() ([]GetMarketProductResponseProductProposedVariants, bool) {
	if o == nil  {
		return nil, false
	}
	return o.ProposedVariants, true
}

// SetProposedVariants sets field value
func (o *GetMarketProductResponseProduct) SetProposedVariants(v []GetMarketProductResponseProductProposedVariants) {
	o.ProposedVariants = v
}

// GetVerification returns the Verification field value
func (o *GetMarketProductResponseProduct) GetVerification() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Verification
}

// GetVerificationOk returns a tuple with the Verification field value
// and a boolean to check if the value has been set.
func (o *GetMarketProductResponseProduct) GetVerificationOk() (map[string]interface{}, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Verification, true
}

// SetVerification sets field value
func (o *GetMarketProductResponseProduct) SetVerification(v map[string]interface{}) {
	o.Verification = v
}

// GetAiVerdict returns the AiVerdict field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetMarketProductResponseProduct) GetAiVerdict() map[string]interface{} {
	if o == nil  {
		var ret map[string]interface{}
		return ret
	}
	return o.AiVerdict
}

// GetAiVerdictOk returns a tuple with the AiVerdict field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetMarketProductResponseProduct) GetAiVerdictOk() (map[string]interface{}, bool) {
	if o == nil || o.AiVerdict == nil {
		return nil, false
	}
	return o.AiVerdict, true
}

// HasAiVerdict returns a boolean if a field has been set.
func (o *GetMarketProductResponseProduct) HasAiVerdict() bool {
	if o != nil && o.AiVerdict != nil {
		return true
	}

	return false
}

// SetAiVerdict gets a reference to the given map[string]interface{} and assigns it to the AiVerdict field.
func (o *GetMarketProductResponseProduct) SetAiVerdict(v map[string]interface{}) {
	o.AiVerdict = v
}

// GetSubmissionSource returns the SubmissionSource field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetMarketProductResponseProduct) GetSubmissionSource() string {
	if o == nil || o.SubmissionSource.Get() == nil {
		var ret string
		return ret
	}
	return *o.SubmissionSource.Get()
}

// GetSubmissionSourceOk returns a tuple with the SubmissionSource field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetMarketProductResponseProduct) GetSubmissionSourceOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.SubmissionSource.Get(), o.SubmissionSource.IsSet()
}

// HasSubmissionSource returns a boolean if a field has been set.
func (o *GetMarketProductResponseProduct) HasSubmissionSource() bool {
	if o != nil && o.SubmissionSource.IsSet() {
		return true
	}

	return false
}

// SetSubmissionSource gets a reference to the given NullableString and assigns it to the SubmissionSource field.
func (o *GetMarketProductResponseProduct) SetSubmissionSource(v string) {
	o.SubmissionSource.Set(&v)
}
// SetSubmissionSourceNil sets the value for SubmissionSource to be an explicit nil
func (o *GetMarketProductResponseProduct) SetSubmissionSourceNil() {
	o.SubmissionSource.Set(nil)
}

// UnsetSubmissionSource ensures that no value is present for SubmissionSource, not even an explicit nil
func (o *GetMarketProductResponseProduct) UnsetSubmissionSource() {
	o.SubmissionSource.Unset()
}

// GetDuplicateOfSkuId returns the DuplicateOfSkuId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetMarketProductResponseProduct) GetDuplicateOfSkuId() string {
	if o == nil || o.DuplicateOfSkuId.Get() == nil {
		var ret string
		return ret
	}
	return *o.DuplicateOfSkuId.Get()
}

// GetDuplicateOfSkuIdOk returns a tuple with the DuplicateOfSkuId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetMarketProductResponseProduct) GetDuplicateOfSkuIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.DuplicateOfSkuId.Get(), o.DuplicateOfSkuId.IsSet()
}

// HasDuplicateOfSkuId returns a boolean if a field has been set.
func (o *GetMarketProductResponseProduct) HasDuplicateOfSkuId() bool {
	if o != nil && o.DuplicateOfSkuId.IsSet() {
		return true
	}

	return false
}

// SetDuplicateOfSkuId gets a reference to the given NullableString and assigns it to the DuplicateOfSkuId field.
func (o *GetMarketProductResponseProduct) SetDuplicateOfSkuId(v string) {
	o.DuplicateOfSkuId.Set(&v)
}
// SetDuplicateOfSkuIdNil sets the value for DuplicateOfSkuId to be an explicit nil
func (o *GetMarketProductResponseProduct) SetDuplicateOfSkuIdNil() {
	o.DuplicateOfSkuId.Set(nil)
}

// UnsetDuplicateOfSkuId ensures that no value is present for DuplicateOfSkuId, not even an explicit nil
func (o *GetMarketProductResponseProduct) UnsetDuplicateOfSkuId() {
	o.DuplicateOfSkuId.Unset()
}

// GetPreferredProviderSlug returns the PreferredProviderSlug field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetMarketProductResponseProduct) GetPreferredProviderSlug() string {
	if o == nil || o.PreferredProviderSlug.Get() == nil {
		var ret string
		return ret
	}
	return *o.PreferredProviderSlug.Get()
}

// GetPreferredProviderSlugOk returns a tuple with the PreferredProviderSlug field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetMarketProductResponseProduct) GetPreferredProviderSlugOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.PreferredProviderSlug.Get(), o.PreferredProviderSlug.IsSet()
}

// HasPreferredProviderSlug returns a boolean if a field has been set.
func (o *GetMarketProductResponseProduct) HasPreferredProviderSlug() bool {
	if o != nil && o.PreferredProviderSlug.IsSet() {
		return true
	}

	return false
}

// SetPreferredProviderSlug gets a reference to the given NullableString and assigns it to the PreferredProviderSlug field.
func (o *GetMarketProductResponseProduct) SetPreferredProviderSlug(v string) {
	o.PreferredProviderSlug.Set(&v)
}
// SetPreferredProviderSlugNil sets the value for PreferredProviderSlug to be an explicit nil
func (o *GetMarketProductResponseProduct) SetPreferredProviderSlugNil() {
	o.PreferredProviderSlug.Set(nil)
}

// UnsetPreferredProviderSlug ensures that no value is present for PreferredProviderSlug, not even an explicit nil
func (o *GetMarketProductResponseProduct) UnsetPreferredProviderSlug() {
	o.PreferredProviderSlug.Unset()
}

// GetAllowPreBid returns the AllowPreBid field value
func (o *GetMarketProductResponseProduct) GetAllowPreBid() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.AllowPreBid
}

// GetAllowPreBidOk returns a tuple with the AllowPreBid field value
// and a boolean to check if the value has been set.
func (o *GetMarketProductResponseProduct) GetAllowPreBidOk() (*bool, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.AllowPreBid, true
}

// SetAllowPreBid sets field value
func (o *GetMarketProductResponseProduct) SetAllowPreBid(v bool) {
	o.AllowPreBid = v
}

// GetPreBidOpensAt returns the PreBidOpensAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetMarketProductResponseProduct) GetPreBidOpensAt() time.Time {
	if o == nil || o.PreBidOpensAt.Get() == nil {
		var ret time.Time
		return ret
	}
	return *o.PreBidOpensAt.Get()
}

// GetPreBidOpensAtOk returns a tuple with the PreBidOpensAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetMarketProductResponseProduct) GetPreBidOpensAtOk() (*time.Time, bool) {
	if o == nil  {
		return nil, false
	}
	return o.PreBidOpensAt.Get(), o.PreBidOpensAt.IsSet()
}

// HasPreBidOpensAt returns a boolean if a field has been set.
func (o *GetMarketProductResponseProduct) HasPreBidOpensAt() bool {
	if o != nil && o.PreBidOpensAt.IsSet() {
		return true
	}

	return false
}

// SetPreBidOpensAt gets a reference to the given NullableTime and assigns it to the PreBidOpensAt field.
func (o *GetMarketProductResponseProduct) SetPreBidOpensAt(v time.Time) {
	o.PreBidOpensAt.Set(&v)
}
// SetPreBidOpensAtNil sets the value for PreBidOpensAt to be an explicit nil
func (o *GetMarketProductResponseProduct) SetPreBidOpensAtNil() {
	o.PreBidOpensAt.Set(nil)
}

// UnsetPreBidOpensAt ensures that no value is present for PreBidOpensAt, not even an explicit nil
func (o *GetMarketProductResponseProduct) UnsetPreBidOpensAt() {
	o.PreBidOpensAt.Unset()
}

// GetFeatured returns the Featured field value
func (o *GetMarketProductResponseProduct) GetFeatured() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Featured
}

// GetFeaturedOk returns a tuple with the Featured field value
// and a boolean to check if the value has been set.
func (o *GetMarketProductResponseProduct) GetFeaturedOk() (*bool, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Featured, true
}

// SetFeatured sets field value
func (o *GetMarketProductResponseProduct) SetFeatured(v bool) {
	o.Featured = v
}

// GetExternalSource returns the ExternalSource field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetMarketProductResponseProduct) GetExternalSource() string {
	if o == nil || o.ExternalSource.Get() == nil {
		var ret string
		return ret
	}
	return *o.ExternalSource.Get()
}

// GetExternalSourceOk returns a tuple with the ExternalSource field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetMarketProductResponseProduct) GetExternalSourceOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.ExternalSource.Get(), o.ExternalSource.IsSet()
}

// HasExternalSource returns a boolean if a field has been set.
func (o *GetMarketProductResponseProduct) HasExternalSource() bool {
	if o != nil && o.ExternalSource.IsSet() {
		return true
	}

	return false
}

// SetExternalSource gets a reference to the given NullableString and assigns it to the ExternalSource field.
func (o *GetMarketProductResponseProduct) SetExternalSource(v string) {
	o.ExternalSource.Set(&v)
}
// SetExternalSourceNil sets the value for ExternalSource to be an explicit nil
func (o *GetMarketProductResponseProduct) SetExternalSourceNil() {
	o.ExternalSource.Set(nil)
}

// UnsetExternalSource ensures that no value is present for ExternalSource, not even an explicit nil
func (o *GetMarketProductResponseProduct) UnsetExternalSource() {
	o.ExternalSource.Unset()
}

// GetExternalSyncedAt returns the ExternalSyncedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetMarketProductResponseProduct) GetExternalSyncedAt() time.Time {
	if o == nil || o.ExternalSyncedAt.Get() == nil {
		var ret time.Time
		return ret
	}
	return *o.ExternalSyncedAt.Get()
}

// GetExternalSyncedAtOk returns a tuple with the ExternalSyncedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetMarketProductResponseProduct) GetExternalSyncedAtOk() (*time.Time, bool) {
	if o == nil  {
		return nil, false
	}
	return o.ExternalSyncedAt.Get(), o.ExternalSyncedAt.IsSet()
}

// HasExternalSyncedAt returns a boolean if a field has been set.
func (o *GetMarketProductResponseProduct) HasExternalSyncedAt() bool {
	if o != nil && o.ExternalSyncedAt.IsSet() {
		return true
	}

	return false
}

// SetExternalSyncedAt gets a reference to the given NullableTime and assigns it to the ExternalSyncedAt field.
func (o *GetMarketProductResponseProduct) SetExternalSyncedAt(v time.Time) {
	o.ExternalSyncedAt.Set(&v)
}
// SetExternalSyncedAtNil sets the value for ExternalSyncedAt to be an explicit nil
func (o *GetMarketProductResponseProduct) SetExternalSyncedAtNil() {
	o.ExternalSyncedAt.Set(nil)
}

// UnsetExternalSyncedAt ensures that no value is present for ExternalSyncedAt, not even an explicit nil
func (o *GetMarketProductResponseProduct) UnsetExternalSyncedAt() {
	o.ExternalSyncedAt.Unset()
}

// GetGradedGradeKeys returns the GradedGradeKeys field value
func (o *GetMarketProductResponseProduct) GetGradedGradeKeys() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.GradedGradeKeys
}

// GetGradedGradeKeysOk returns a tuple with the GradedGradeKeys field value
// and a boolean to check if the value has been set.
func (o *GetMarketProductResponseProduct) GetGradedGradeKeysOk() ([]string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.GradedGradeKeys, true
}

// SetGradedGradeKeys sets field value
func (o *GetMarketProductResponseProduct) SetGradedGradeKeys(v []string) {
	o.GradedGradeKeys = v
}

// GetLowestAskCents returns the LowestAskCents field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetMarketProductResponseProduct) GetLowestAskCents() float32 {
	if o == nil || o.LowestAskCents.Get() == nil {
		var ret float32
		return ret
	}
	return *o.LowestAskCents.Get()
}

// GetLowestAskCentsOk returns a tuple with the LowestAskCents field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetMarketProductResponseProduct) GetLowestAskCentsOk() (*float32, bool) {
	if o == nil  {
		return nil, false
	}
	return o.LowestAskCents.Get(), o.LowestAskCents.IsSet()
}

// HasLowestAskCents returns a boolean if a field has been set.
func (o *GetMarketProductResponseProduct) HasLowestAskCents() bool {
	if o != nil && o.LowestAskCents.IsSet() {
		return true
	}

	return false
}

// SetLowestAskCents gets a reference to the given NullableFloat32 and assigns it to the LowestAskCents field.
func (o *GetMarketProductResponseProduct) SetLowestAskCents(v float32) {
	o.LowestAskCents.Set(&v)
}
// SetLowestAskCentsNil sets the value for LowestAskCents to be an explicit nil
func (o *GetMarketProductResponseProduct) SetLowestAskCentsNil() {
	o.LowestAskCents.Set(nil)
}

// UnsetLowestAskCents ensures that no value is present for LowestAskCents, not even an explicit nil
func (o *GetMarketProductResponseProduct) UnsetLowestAskCents() {
	o.LowestAskCents.Unset()
}

// GetHighestBidCents returns the HighestBidCents field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetMarketProductResponseProduct) GetHighestBidCents() float32 {
	if o == nil || o.HighestBidCents.Get() == nil {
		var ret float32
		return ret
	}
	return *o.HighestBidCents.Get()
}

// GetHighestBidCentsOk returns a tuple with the HighestBidCents field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetMarketProductResponseProduct) GetHighestBidCentsOk() (*float32, bool) {
	if o == nil  {
		return nil, false
	}
	return o.HighestBidCents.Get(), o.HighestBidCents.IsSet()
}

// HasHighestBidCents returns a boolean if a field has been set.
func (o *GetMarketProductResponseProduct) HasHighestBidCents() bool {
	if o != nil && o.HighestBidCents.IsSet() {
		return true
	}

	return false
}

// SetHighestBidCents gets a reference to the given NullableFloat32 and assigns it to the HighestBidCents field.
func (o *GetMarketProductResponseProduct) SetHighestBidCents(v float32) {
	o.HighestBidCents.Set(&v)
}
// SetHighestBidCentsNil sets the value for HighestBidCents to be an explicit nil
func (o *GetMarketProductResponseProduct) SetHighestBidCentsNil() {
	o.HighestBidCents.Set(nil)
}

// UnsetHighestBidCents ensures that no value is present for HighestBidCents, not even an explicit nil
func (o *GetMarketProductResponseProduct) UnsetHighestBidCents() {
	o.HighestBidCents.Unset()
}

// GetLastSaleCents returns the LastSaleCents field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetMarketProductResponseProduct) GetLastSaleCents() float32 {
	if o == nil || o.LastSaleCents.Get() == nil {
		var ret float32
		return ret
	}
	return *o.LastSaleCents.Get()
}

// GetLastSaleCentsOk returns a tuple with the LastSaleCents field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetMarketProductResponseProduct) GetLastSaleCentsOk() (*float32, bool) {
	if o == nil  {
		return nil, false
	}
	return o.LastSaleCents.Get(), o.LastSaleCents.IsSet()
}

// HasLastSaleCents returns a boolean if a field has been set.
func (o *GetMarketProductResponseProduct) HasLastSaleCents() bool {
	if o != nil && o.LastSaleCents.IsSet() {
		return true
	}

	return false
}

// SetLastSaleCents gets a reference to the given NullableFloat32 and assigns it to the LastSaleCents field.
func (o *GetMarketProductResponseProduct) SetLastSaleCents(v float32) {
	o.LastSaleCents.Set(&v)
}
// SetLastSaleCentsNil sets the value for LastSaleCents to be an explicit nil
func (o *GetMarketProductResponseProduct) SetLastSaleCentsNil() {
	o.LastSaleCents.Set(nil)
}

// UnsetLastSaleCents ensures that no value is present for LastSaleCents, not even an explicit nil
func (o *GetMarketProductResponseProduct) UnsetLastSaleCents() {
	o.LastSaleCents.Unset()
}

// GetTradesCount returns the TradesCount field value
func (o *GetMarketProductResponseProduct) GetTradesCount() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.TradesCount
}

// GetTradesCountOk returns a tuple with the TradesCount field value
// and a boolean to check if the value has been set.
func (o *GetMarketProductResponseProduct) GetTradesCountOk() (*float32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.TradesCount, true
}

// SetTradesCount sets field value
func (o *GetMarketProductResponseProduct) SetTradesCount(v float32) {
	o.TradesCount = v
}

func (o GetMarketProductResponseProduct) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	if o.Brand.IsSet() {
		toSerialize["brand"] = o.Brand.Get()
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if true {
		toSerialize["status"] = o.Status
	}
	if o.RetailCents.IsSet() {
		toSerialize["retailCents"] = o.RetailCents.Get()
	}
	if true {
		toSerialize["categorySlug"] = o.CategorySlug
	}
	if o.ExternalId.IsSet() {
		toSerialize["externalId"] = o.ExternalId.Get()
	}
	if o.ImageUrl.IsSet() {
		toSerialize["imageUrl"] = o.ImageUrl.Get()
	}
	if o.Model.IsSet() {
		toSerialize["model"] = o.Model.Get()
	}
	if o.Colorway.IsSet() {
		toSerialize["colorway"] = o.Colorway.Get()
	}
	if o.StyleCode.IsSet() {
		toSerialize["styleCode"] = o.StyleCode.Get()
	}
	if o.ReleaseDate.IsSet() {
		toSerialize["releaseDate"] = o.ReleaseDate.Get()
	}
	if o.SubmittedByUserId.IsSet() {
		toSerialize["submittedByUserId"] = o.SubmittedByUserId.Get()
	}
	if o.ApprovedByUserId.IsSet() {
		toSerialize["approvedByUserId"] = o.ApprovedByUserId.Get()
	}
	if o.ApprovedAt.IsSet() {
		toSerialize["approvedAt"] = o.ApprovedAt.Get()
	}
	if o.RejectionReason.IsSet() {
		toSerialize["rejectionReason"] = o.RejectionReason.Get()
	}
	if true {
		toSerialize["proposedVariants"] = o.ProposedVariants
	}
	if true {
		toSerialize["verification"] = o.Verification
	}
	if o.AiVerdict != nil {
		toSerialize["aiVerdict"] = o.AiVerdict
	}
	if o.SubmissionSource.IsSet() {
		toSerialize["submissionSource"] = o.SubmissionSource.Get()
	}
	if o.DuplicateOfSkuId.IsSet() {
		toSerialize["duplicateOfSkuId"] = o.DuplicateOfSkuId.Get()
	}
	if o.PreferredProviderSlug.IsSet() {
		toSerialize["preferredProviderSlug"] = o.PreferredProviderSlug.Get()
	}
	if true {
		toSerialize["allowPreBid"] = o.AllowPreBid
	}
	if o.PreBidOpensAt.IsSet() {
		toSerialize["preBidOpensAt"] = o.PreBidOpensAt.Get()
	}
	if true {
		toSerialize["featured"] = o.Featured
	}
	if o.ExternalSource.IsSet() {
		toSerialize["externalSource"] = o.ExternalSource.Get()
	}
	if o.ExternalSyncedAt.IsSet() {
		toSerialize["externalSyncedAt"] = o.ExternalSyncedAt.Get()
	}
	if true {
		toSerialize["gradedGradeKeys"] = o.GradedGradeKeys
	}
	if o.LowestAskCents.IsSet() {
		toSerialize["lowestAskCents"] = o.LowestAskCents.Get()
	}
	if o.HighestBidCents.IsSet() {
		toSerialize["highestBidCents"] = o.HighestBidCents.Get()
	}
	if o.LastSaleCents.IsSet() {
		toSerialize["lastSaleCents"] = o.LastSaleCents.Get()
	}
	if true {
		toSerialize["tradesCount"] = o.TradesCount
	}
	return json.Marshal(toSerialize)
}

type NullableGetMarketProductResponseProduct struct {
	value *GetMarketProductResponseProduct
	isSet bool
}

func (v NullableGetMarketProductResponseProduct) Get() *GetMarketProductResponseProduct {
	return v.value
}

func (v *NullableGetMarketProductResponseProduct) Set(val *GetMarketProductResponseProduct) {
	v.value = val
	v.isSet = true
}

func (v NullableGetMarketProductResponseProduct) IsSet() bool {
	return v.isSet
}

func (v *NullableGetMarketProductResponseProduct) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetMarketProductResponseProduct(val *GetMarketProductResponseProduct) *NullableGetMarketProductResponseProduct {
	return &NullableGetMarketProductResponseProduct{value: val, isSet: true}
}

func (v NullableGetMarketProductResponseProduct) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetMarketProductResponseProduct) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


