/*
Crossly Seller API

The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crossly

import (
	"encoding/json"
)

// GetAutomationRuleExportResponseAction struct for GetAutomationRuleExportResponseAction
type GetAutomationRuleExportResponseAction struct {
	Type string `json:"type"`
	Config map[string]interface{} `json:"config"`
}

// NewGetAutomationRuleExportResponseAction instantiates a new GetAutomationRuleExportResponseAction object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAutomationRuleExportResponseAction(type_ string, config map[string]interface{}) *GetAutomationRuleExportResponseAction {
	this := GetAutomationRuleExportResponseAction{}
	this.Type = type_
	this.Config = config
	return &this
}

// NewGetAutomationRuleExportResponseActionWithDefaults instantiates a new GetAutomationRuleExportResponseAction object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAutomationRuleExportResponseActionWithDefaults() *GetAutomationRuleExportResponseAction {
	this := GetAutomationRuleExportResponseAction{}
	return &this
}

// GetType returns the Type field value
func (o *GetAutomationRuleExportResponseAction) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *GetAutomationRuleExportResponseAction) GetTypeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *GetAutomationRuleExportResponseAction) SetType(v string) {
	o.Type = v
}

// GetConfig returns the Config field value
func (o *GetAutomationRuleExportResponseAction) GetConfig() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Config
}

// GetConfigOk returns a tuple with the Config field value
// and a boolean to check if the value has been set.
func (o *GetAutomationRuleExportResponseAction) GetConfigOk() (map[string]interface{}, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Config, true
}

// SetConfig sets field value
func (o *GetAutomationRuleExportResponseAction) SetConfig(v map[string]interface{}) {
	o.Config = v
}

func (o GetAutomationRuleExportResponseAction) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["type"] = o.Type
	}
	if true {
		toSerialize["config"] = o.Config
	}
	return json.Marshal(toSerialize)
}

type NullableGetAutomationRuleExportResponseAction struct {
	value *GetAutomationRuleExportResponseAction
	isSet bool
}

func (v NullableGetAutomationRuleExportResponseAction) Get() *GetAutomationRuleExportResponseAction {
	return v.value
}

func (v *NullableGetAutomationRuleExportResponseAction) Set(val *GetAutomationRuleExportResponseAction) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAutomationRuleExportResponseAction) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAutomationRuleExportResponseAction) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAutomationRuleExportResponseAction(val *GetAutomationRuleExportResponseAction) *NullableGetAutomationRuleExportResponseAction {
	return &NullableGetAutomationRuleExportResponseAction{value: val, isSet: true}
}

func (v NullableGetAutomationRuleExportResponseAction) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAutomationRuleExportResponseAction) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


