/*
Crossly Seller API

The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crossly

import (
	"encoding/json"
)

// GetMagicDraftResponse struct for GetMagicDraftResponse
type GetMagicDraftResponse struct {
	Draft GetMagicDraftResponseDraft `json:"draft"`
}

// NewGetMagicDraftResponse instantiates a new GetMagicDraftResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetMagicDraftResponse(draft GetMagicDraftResponseDraft) *GetMagicDraftResponse {
	this := GetMagicDraftResponse{}
	this.Draft = draft
	return &this
}

// NewGetMagicDraftResponseWithDefaults instantiates a new GetMagicDraftResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetMagicDraftResponseWithDefaults() *GetMagicDraftResponse {
	this := GetMagicDraftResponse{}
	return &this
}

// GetDraft returns the Draft field value
func (o *GetMagicDraftResponse) GetDraft() GetMagicDraftResponseDraft {
	if o == nil {
		var ret GetMagicDraftResponseDraft
		return ret
	}

	return o.Draft
}

// GetDraftOk returns a tuple with the Draft field value
// and a boolean to check if the value has been set.
func (o *GetMagicDraftResponse) GetDraftOk() (*GetMagicDraftResponseDraft, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Draft, true
}

// SetDraft sets field value
func (o *GetMagicDraftResponse) SetDraft(v GetMagicDraftResponseDraft) {
	o.Draft = v
}

func (o GetMagicDraftResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["draft"] = o.Draft
	}
	return json.Marshal(toSerialize)
}

type NullableGetMagicDraftResponse struct {
	value *GetMagicDraftResponse
	isSet bool
}

func (v NullableGetMagicDraftResponse) Get() *GetMagicDraftResponse {
	return v.value
}

func (v *NullableGetMagicDraftResponse) Set(val *GetMagicDraftResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetMagicDraftResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetMagicDraftResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetMagicDraftResponse(val *GetMagicDraftResponse) *NullableGetMagicDraftResponse {
	return &NullableGetMagicDraftResponse{value: val, isSet: true}
}

func (v NullableGetMagicDraftResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetMagicDraftResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


