/*
Crossly Seller API

The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crossly

import (
	"encoding/json"
)

// GetAnalyticBookkeepingResponse struct for GetAnalyticBookkeepingResponse
type GetAnalyticBookkeepingResponse struct {
	Year float32 `json:"year"`
	MonthlyPL []GetAnalyticBookkeepingResponseMonthlyPL `json:"monthlyPL"`
	AnnualTotals GetAnalyticBookkeepingResponseAnnualTotals `json:"annualTotals"`
	PlatformBreakdown []GetAnalyticBookkeepingResponsePlatformBreakdown `json:"platformBreakdown"`
}

// NewGetAnalyticBookkeepingResponse instantiates a new GetAnalyticBookkeepingResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAnalyticBookkeepingResponse(year float32, monthlyPL []GetAnalyticBookkeepingResponseMonthlyPL, annualTotals GetAnalyticBookkeepingResponseAnnualTotals, platformBreakdown []GetAnalyticBookkeepingResponsePlatformBreakdown) *GetAnalyticBookkeepingResponse {
	this := GetAnalyticBookkeepingResponse{}
	this.Year = year
	this.MonthlyPL = monthlyPL
	this.AnnualTotals = annualTotals
	this.PlatformBreakdown = platformBreakdown
	return &this
}

// NewGetAnalyticBookkeepingResponseWithDefaults instantiates a new GetAnalyticBookkeepingResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAnalyticBookkeepingResponseWithDefaults() *GetAnalyticBookkeepingResponse {
	this := GetAnalyticBookkeepingResponse{}
	return &this
}

// GetYear returns the Year field value
func (o *GetAnalyticBookkeepingResponse) GetYear() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Year
}

// GetYearOk returns a tuple with the Year field value
// and a boolean to check if the value has been set.
func (o *GetAnalyticBookkeepingResponse) GetYearOk() (*float32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Year, true
}

// SetYear sets field value
func (o *GetAnalyticBookkeepingResponse) SetYear(v float32) {
	o.Year = v
}

// GetMonthlyPL returns the MonthlyPL field value
func (o *GetAnalyticBookkeepingResponse) GetMonthlyPL() []GetAnalyticBookkeepingResponseMonthlyPL {
	if o == nil {
		var ret []GetAnalyticBookkeepingResponseMonthlyPL
		return ret
	}

	return o.MonthlyPL
}

// GetMonthlyPLOk returns a tuple with the MonthlyPL field value
// and a boolean to check if the value has been set.
func (o *GetAnalyticBookkeepingResponse) GetMonthlyPLOk() ([]GetAnalyticBookkeepingResponseMonthlyPL, bool) {
	if o == nil  {
		return nil, false
	}
	return o.MonthlyPL, true
}

// SetMonthlyPL sets field value
func (o *GetAnalyticBookkeepingResponse) SetMonthlyPL(v []GetAnalyticBookkeepingResponseMonthlyPL) {
	o.MonthlyPL = v
}

// GetAnnualTotals returns the AnnualTotals field value
func (o *GetAnalyticBookkeepingResponse) GetAnnualTotals() GetAnalyticBookkeepingResponseAnnualTotals {
	if o == nil {
		var ret GetAnalyticBookkeepingResponseAnnualTotals
		return ret
	}

	return o.AnnualTotals
}

// GetAnnualTotalsOk returns a tuple with the AnnualTotals field value
// and a boolean to check if the value has been set.
func (o *GetAnalyticBookkeepingResponse) GetAnnualTotalsOk() (*GetAnalyticBookkeepingResponseAnnualTotals, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.AnnualTotals, true
}

// SetAnnualTotals sets field value
func (o *GetAnalyticBookkeepingResponse) SetAnnualTotals(v GetAnalyticBookkeepingResponseAnnualTotals) {
	o.AnnualTotals = v
}

// GetPlatformBreakdown returns the PlatformBreakdown field value
func (o *GetAnalyticBookkeepingResponse) GetPlatformBreakdown() []GetAnalyticBookkeepingResponsePlatformBreakdown {
	if o == nil {
		var ret []GetAnalyticBookkeepingResponsePlatformBreakdown
		return ret
	}

	return o.PlatformBreakdown
}

// GetPlatformBreakdownOk returns a tuple with the PlatformBreakdown field value
// and a boolean to check if the value has been set.
func (o *GetAnalyticBookkeepingResponse) GetPlatformBreakdownOk() ([]GetAnalyticBookkeepingResponsePlatformBreakdown, bool) {
	if o == nil  {
		return nil, false
	}
	return o.PlatformBreakdown, true
}

// SetPlatformBreakdown sets field value
func (o *GetAnalyticBookkeepingResponse) SetPlatformBreakdown(v []GetAnalyticBookkeepingResponsePlatformBreakdown) {
	o.PlatformBreakdown = v
}

func (o GetAnalyticBookkeepingResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["year"] = o.Year
	}
	if true {
		toSerialize["monthlyPL"] = o.MonthlyPL
	}
	if true {
		toSerialize["annualTotals"] = o.AnnualTotals
	}
	if true {
		toSerialize["platformBreakdown"] = o.PlatformBreakdown
	}
	return json.Marshal(toSerialize)
}

type NullableGetAnalyticBookkeepingResponse struct {
	value *GetAnalyticBookkeepingResponse
	isSet bool
}

func (v NullableGetAnalyticBookkeepingResponse) Get() *GetAnalyticBookkeepingResponse {
	return v.value
}

func (v *NullableGetAnalyticBookkeepingResponse) Set(val *GetAnalyticBookkeepingResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAnalyticBookkeepingResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAnalyticBookkeepingResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAnalyticBookkeepingResponse(val *GetAnalyticBookkeepingResponse) *NullableGetAnalyticBookkeepingResponse {
	return &NullableGetAnalyticBookkeepingResponse{value: val, isSet: true}
}

func (v NullableGetAnalyticBookkeepingResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAnalyticBookkeepingResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


