/*
Crossly Seller API

The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crossly

import (
	"encoding/json"
)

// ListTaxonomySuggestItemCatalog struct for ListTaxonomySuggestItemCatalog
type ListTaxonomySuggestItemCatalog struct {
	Department string `json:"department"`
	Category string `json:"category"`
	CategoryFeatures []string `json:"category_features"`
}

// NewListTaxonomySuggestItemCatalog instantiates a new ListTaxonomySuggestItemCatalog object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListTaxonomySuggestItemCatalog(department string, category string, categoryFeatures []string) *ListTaxonomySuggestItemCatalog {
	this := ListTaxonomySuggestItemCatalog{}
	this.Department = department
	this.Category = category
	this.CategoryFeatures = categoryFeatures
	return &this
}

// NewListTaxonomySuggestItemCatalogWithDefaults instantiates a new ListTaxonomySuggestItemCatalog object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListTaxonomySuggestItemCatalogWithDefaults() *ListTaxonomySuggestItemCatalog {
	this := ListTaxonomySuggestItemCatalog{}
	return &this
}

// GetDepartment returns the Department field value
func (o *ListTaxonomySuggestItemCatalog) GetDepartment() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Department
}

// GetDepartmentOk returns a tuple with the Department field value
// and a boolean to check if the value has been set.
func (o *ListTaxonomySuggestItemCatalog) GetDepartmentOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Department, true
}

// SetDepartment sets field value
func (o *ListTaxonomySuggestItemCatalog) SetDepartment(v string) {
	o.Department = v
}

// GetCategory returns the Category field value
func (o *ListTaxonomySuggestItemCatalog) GetCategory() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Category
}

// GetCategoryOk returns a tuple with the Category field value
// and a boolean to check if the value has been set.
func (o *ListTaxonomySuggestItemCatalog) GetCategoryOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Category, true
}

// SetCategory sets field value
func (o *ListTaxonomySuggestItemCatalog) SetCategory(v string) {
	o.Category = v
}

// GetCategoryFeatures returns the CategoryFeatures field value
func (o *ListTaxonomySuggestItemCatalog) GetCategoryFeatures() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.CategoryFeatures
}

// GetCategoryFeaturesOk returns a tuple with the CategoryFeatures field value
// and a boolean to check if the value has been set.
func (o *ListTaxonomySuggestItemCatalog) GetCategoryFeaturesOk() ([]string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.CategoryFeatures, true
}

// SetCategoryFeatures sets field value
func (o *ListTaxonomySuggestItemCatalog) SetCategoryFeatures(v []string) {
	o.CategoryFeatures = v
}

func (o ListTaxonomySuggestItemCatalog) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["department"] = o.Department
	}
	if true {
		toSerialize["category"] = o.Category
	}
	if true {
		toSerialize["category_features"] = o.CategoryFeatures
	}
	return json.Marshal(toSerialize)
}

type NullableListTaxonomySuggestItemCatalog struct {
	value *ListTaxonomySuggestItemCatalog
	isSet bool
}

func (v NullableListTaxonomySuggestItemCatalog) Get() *ListTaxonomySuggestItemCatalog {
	return v.value
}

func (v *NullableListTaxonomySuggestItemCatalog) Set(val *ListTaxonomySuggestItemCatalog) {
	v.value = val
	v.isSet = true
}

func (v NullableListTaxonomySuggestItemCatalog) IsSet() bool {
	return v.isSet
}

func (v *NullableListTaxonomySuggestItemCatalog) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListTaxonomySuggestItemCatalog(val *ListTaxonomySuggestItemCatalog) *NullableListTaxonomySuggestItemCatalog {
	return &NullableListTaxonomySuggestItemCatalog{value: val, isSet: true}
}

func (v NullableListTaxonomySuggestItemCatalog) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListTaxonomySuggestItemCatalog) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


