/*
Crossly Seller API

The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crossly

import (
	"encoding/json"
)

// GetAnalyticDashboardResponseRevenue struct for GetAnalyticDashboardResponseRevenue
type GetAnalyticDashboardResponseRevenue struct {
	Current float32 `json:"current"`
	Previous float32 `json:"previous"`
	PctChange NullableFloat32 `json:"pctChange,omitempty"`
}

// NewGetAnalyticDashboardResponseRevenue instantiates a new GetAnalyticDashboardResponseRevenue object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAnalyticDashboardResponseRevenue(current float32, previous float32) *GetAnalyticDashboardResponseRevenue {
	this := GetAnalyticDashboardResponseRevenue{}
	this.Current = current
	this.Previous = previous
	return &this
}

// NewGetAnalyticDashboardResponseRevenueWithDefaults instantiates a new GetAnalyticDashboardResponseRevenue object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAnalyticDashboardResponseRevenueWithDefaults() *GetAnalyticDashboardResponseRevenue {
	this := GetAnalyticDashboardResponseRevenue{}
	return &this
}

// GetCurrent returns the Current field value
func (o *GetAnalyticDashboardResponseRevenue) GetCurrent() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Current
}

// GetCurrentOk returns a tuple with the Current field value
// and a boolean to check if the value has been set.
func (o *GetAnalyticDashboardResponseRevenue) GetCurrentOk() (*float32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Current, true
}

// SetCurrent sets field value
func (o *GetAnalyticDashboardResponseRevenue) SetCurrent(v float32) {
	o.Current = v
}

// GetPrevious returns the Previous field value
func (o *GetAnalyticDashboardResponseRevenue) GetPrevious() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Previous
}

// GetPreviousOk returns a tuple with the Previous field value
// and a boolean to check if the value has been set.
func (o *GetAnalyticDashboardResponseRevenue) GetPreviousOk() (*float32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Previous, true
}

// SetPrevious sets field value
func (o *GetAnalyticDashboardResponseRevenue) SetPrevious(v float32) {
	o.Previous = v
}

// GetPctChange returns the PctChange field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetAnalyticDashboardResponseRevenue) GetPctChange() float32 {
	if o == nil || o.PctChange.Get() == nil {
		var ret float32
		return ret
	}
	return *o.PctChange.Get()
}

// GetPctChangeOk returns a tuple with the PctChange field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetAnalyticDashboardResponseRevenue) GetPctChangeOk() (*float32, bool) {
	if o == nil  {
		return nil, false
	}
	return o.PctChange.Get(), o.PctChange.IsSet()
}

// HasPctChange returns a boolean if a field has been set.
func (o *GetAnalyticDashboardResponseRevenue) HasPctChange() bool {
	if o != nil && o.PctChange.IsSet() {
		return true
	}

	return false
}

// SetPctChange gets a reference to the given NullableFloat32 and assigns it to the PctChange field.
func (o *GetAnalyticDashboardResponseRevenue) SetPctChange(v float32) {
	o.PctChange.Set(&v)
}
// SetPctChangeNil sets the value for PctChange to be an explicit nil
func (o *GetAnalyticDashboardResponseRevenue) SetPctChangeNil() {
	o.PctChange.Set(nil)
}

// UnsetPctChange ensures that no value is present for PctChange, not even an explicit nil
func (o *GetAnalyticDashboardResponseRevenue) UnsetPctChange() {
	o.PctChange.Unset()
}

func (o GetAnalyticDashboardResponseRevenue) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["current"] = o.Current
	}
	if true {
		toSerialize["previous"] = o.Previous
	}
	if o.PctChange.IsSet() {
		toSerialize["pctChange"] = o.PctChange.Get()
	}
	return json.Marshal(toSerialize)
}

type NullableGetAnalyticDashboardResponseRevenue struct {
	value *GetAnalyticDashboardResponseRevenue
	isSet bool
}

func (v NullableGetAnalyticDashboardResponseRevenue) Get() *GetAnalyticDashboardResponseRevenue {
	return v.value
}

func (v *NullableGetAnalyticDashboardResponseRevenue) Set(val *GetAnalyticDashboardResponseRevenue) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAnalyticDashboardResponseRevenue) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAnalyticDashboardResponseRevenue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAnalyticDashboardResponseRevenue(val *GetAnalyticDashboardResponseRevenue) *NullableGetAnalyticDashboardResponseRevenue {
	return &NullableGetAnalyticDashboardResponseRevenue{value: val, isSet: true}
}

func (v NullableGetAnalyticDashboardResponseRevenue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAnalyticDashboardResponseRevenue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


