/*
Crossly Seller API

The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crossly

import (
	"encoding/json"
)

// CreateListingResponseJobs struct for CreateListingResponseJobs
type CreateListingResponseJobs struct {
	Platform string `json:"platform"`
	JobId string `json:"jobId"`
}

// NewCreateListingResponseJobs instantiates a new CreateListingResponseJobs object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateListingResponseJobs(platform string, jobId string) *CreateListingResponseJobs {
	this := CreateListingResponseJobs{}
	this.Platform = platform
	this.JobId = jobId
	return &this
}

// NewCreateListingResponseJobsWithDefaults instantiates a new CreateListingResponseJobs object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateListingResponseJobsWithDefaults() *CreateListingResponseJobs {
	this := CreateListingResponseJobs{}
	return &this
}

// GetPlatform returns the Platform field value
func (o *CreateListingResponseJobs) GetPlatform() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Platform
}

// GetPlatformOk returns a tuple with the Platform field value
// and a boolean to check if the value has been set.
func (o *CreateListingResponseJobs) GetPlatformOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Platform, true
}

// SetPlatform sets field value
func (o *CreateListingResponseJobs) SetPlatform(v string) {
	o.Platform = v
}

// GetJobId returns the JobId field value
func (o *CreateListingResponseJobs) GetJobId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.JobId
}

// GetJobIdOk returns a tuple with the JobId field value
// and a boolean to check if the value has been set.
func (o *CreateListingResponseJobs) GetJobIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.JobId, true
}

// SetJobId sets field value
func (o *CreateListingResponseJobs) SetJobId(v string) {
	o.JobId = v
}

func (o CreateListingResponseJobs) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["platform"] = o.Platform
	}
	if true {
		toSerialize["jobId"] = o.JobId
	}
	return json.Marshal(toSerialize)
}

type NullableCreateListingResponseJobs struct {
	value *CreateListingResponseJobs
	isSet bool
}

func (v NullableCreateListingResponseJobs) Get() *CreateListingResponseJobs {
	return v.value
}

func (v *NullableCreateListingResponseJobs) Set(val *CreateListingResponseJobs) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateListingResponseJobs) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateListingResponseJobs) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateListingResponseJobs(val *CreateListingResponseJobs) *NullableCreateListingResponseJobs {
	return &NullableCreateListingResponseJobs{value: val, isSet: true}
}

func (v NullableCreateListingResponseJobs) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateListingResponseJobs) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


