/*
Crossly Seller API

The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crossly

import (
	"encoding/json"
)

// GetTaxonomyCategoryChildrenResponse struct for GetTaxonomyCategoryChildrenResponse
type GetTaxonomyCategoryChildrenResponse struct {
	Children []GetTaxonomyCategoryResponseCategories `json:"children"`
}

// NewGetTaxonomyCategoryChildrenResponse instantiates a new GetTaxonomyCategoryChildrenResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetTaxonomyCategoryChildrenResponse(children []GetTaxonomyCategoryResponseCategories) *GetTaxonomyCategoryChildrenResponse {
	this := GetTaxonomyCategoryChildrenResponse{}
	this.Children = children
	return &this
}

// NewGetTaxonomyCategoryChildrenResponseWithDefaults instantiates a new GetTaxonomyCategoryChildrenResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetTaxonomyCategoryChildrenResponseWithDefaults() *GetTaxonomyCategoryChildrenResponse {
	this := GetTaxonomyCategoryChildrenResponse{}
	return &this
}

// GetChildren returns the Children field value
func (o *GetTaxonomyCategoryChildrenResponse) GetChildren() []GetTaxonomyCategoryResponseCategories {
	if o == nil {
		var ret []GetTaxonomyCategoryResponseCategories
		return ret
	}

	return o.Children
}

// GetChildrenOk returns a tuple with the Children field value
// and a boolean to check if the value has been set.
func (o *GetTaxonomyCategoryChildrenResponse) GetChildrenOk() ([]GetTaxonomyCategoryResponseCategories, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Children, true
}

// SetChildren sets field value
func (o *GetTaxonomyCategoryChildrenResponse) SetChildren(v []GetTaxonomyCategoryResponseCategories) {
	o.Children = v
}

func (o GetTaxonomyCategoryChildrenResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["children"] = o.Children
	}
	return json.Marshal(toSerialize)
}

type NullableGetTaxonomyCategoryChildrenResponse struct {
	value *GetTaxonomyCategoryChildrenResponse
	isSet bool
}

func (v NullableGetTaxonomyCategoryChildrenResponse) Get() *GetTaxonomyCategoryChildrenResponse {
	return v.value
}

func (v *NullableGetTaxonomyCategoryChildrenResponse) Set(val *GetTaxonomyCategoryChildrenResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetTaxonomyCategoryChildrenResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetTaxonomyCategoryChildrenResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetTaxonomyCategoryChildrenResponse(val *GetTaxonomyCategoryChildrenResponse) *NullableGetTaxonomyCategoryChildrenResponse {
	return &NullableGetTaxonomyCategoryChildrenResponse{value: val, isSet: true}
}

func (v NullableGetTaxonomyCategoryChildrenResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetTaxonomyCategoryChildrenResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


