/*
Crossly Seller API

The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crossly

import (
	"encoding/json"
)

// CreateInventoryLabelRenameResponse struct for CreateInventoryLabelRenameResponse
type CreateInventoryLabelRenameResponse struct {
	Updated float32 `json:"updated"`
}

// NewCreateInventoryLabelRenameResponse instantiates a new CreateInventoryLabelRenameResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateInventoryLabelRenameResponse(updated float32) *CreateInventoryLabelRenameResponse {
	this := CreateInventoryLabelRenameResponse{}
	this.Updated = updated
	return &this
}

// NewCreateInventoryLabelRenameResponseWithDefaults instantiates a new CreateInventoryLabelRenameResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateInventoryLabelRenameResponseWithDefaults() *CreateInventoryLabelRenameResponse {
	this := CreateInventoryLabelRenameResponse{}
	return &this
}

// GetUpdated returns the Updated field value
func (o *CreateInventoryLabelRenameResponse) GetUpdated() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Updated
}

// GetUpdatedOk returns a tuple with the Updated field value
// and a boolean to check if the value has been set.
func (o *CreateInventoryLabelRenameResponse) GetUpdatedOk() (*float32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Updated, true
}

// SetUpdated sets field value
func (o *CreateInventoryLabelRenameResponse) SetUpdated(v float32) {
	o.Updated = v
}

func (o CreateInventoryLabelRenameResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["updated"] = o.Updated
	}
	return json.Marshal(toSerialize)
}

type NullableCreateInventoryLabelRenameResponse struct {
	value *CreateInventoryLabelRenameResponse
	isSet bool
}

func (v NullableCreateInventoryLabelRenameResponse) Get() *CreateInventoryLabelRenameResponse {
	return v.value
}

func (v *NullableCreateInventoryLabelRenameResponse) Set(val *CreateInventoryLabelRenameResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateInventoryLabelRenameResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateInventoryLabelRenameResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateInventoryLabelRenameResponse(val *CreateInventoryLabelRenameResponse) *NullableCreateInventoryLabelRenameResponse {
	return &NullableCreateInventoryLabelRenameResponse{value: val, isSet: true}
}

func (v NullableCreateInventoryLabelRenameResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateInventoryLabelRenameResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


