/*
Crossly Seller API

The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crossly

import (
	"encoding/json"
)

// CreateCbxAdCreditPurchaseResponse struct for CreateCbxAdCreditPurchaseResponse
type CreateCbxAdCreditPurchaseResponse struct {
	CreditCents float32 `json:"creditCents"`
	BaseUnitsPaid string `json:"baseUnitsPaid"`
	CentsPerToken float32 `json:"centsPerToken"`
	BalanceCents float32 `json:"balanceCents"`
	Duplicate bool `json:"duplicate"`
}

// NewCreateCbxAdCreditPurchaseResponse instantiates a new CreateCbxAdCreditPurchaseResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateCbxAdCreditPurchaseResponse(creditCents float32, baseUnitsPaid string, centsPerToken float32, balanceCents float32, duplicate bool) *CreateCbxAdCreditPurchaseResponse {
	this := CreateCbxAdCreditPurchaseResponse{}
	this.CreditCents = creditCents
	this.BaseUnitsPaid = baseUnitsPaid
	this.CentsPerToken = centsPerToken
	this.BalanceCents = balanceCents
	this.Duplicate = duplicate
	return &this
}

// NewCreateCbxAdCreditPurchaseResponseWithDefaults instantiates a new CreateCbxAdCreditPurchaseResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateCbxAdCreditPurchaseResponseWithDefaults() *CreateCbxAdCreditPurchaseResponse {
	this := CreateCbxAdCreditPurchaseResponse{}
	return &this
}

// GetCreditCents returns the CreditCents field value
func (o *CreateCbxAdCreditPurchaseResponse) GetCreditCents() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.CreditCents
}

// GetCreditCentsOk returns a tuple with the CreditCents field value
// and a boolean to check if the value has been set.
func (o *CreateCbxAdCreditPurchaseResponse) GetCreditCentsOk() (*float32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.CreditCents, true
}

// SetCreditCents sets field value
func (o *CreateCbxAdCreditPurchaseResponse) SetCreditCents(v float32) {
	o.CreditCents = v
}

// GetBaseUnitsPaid returns the BaseUnitsPaid field value
func (o *CreateCbxAdCreditPurchaseResponse) GetBaseUnitsPaid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BaseUnitsPaid
}

// GetBaseUnitsPaidOk returns a tuple with the BaseUnitsPaid field value
// and a boolean to check if the value has been set.
func (o *CreateCbxAdCreditPurchaseResponse) GetBaseUnitsPaidOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.BaseUnitsPaid, true
}

// SetBaseUnitsPaid sets field value
func (o *CreateCbxAdCreditPurchaseResponse) SetBaseUnitsPaid(v string) {
	o.BaseUnitsPaid = v
}

// GetCentsPerToken returns the CentsPerToken field value
func (o *CreateCbxAdCreditPurchaseResponse) GetCentsPerToken() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.CentsPerToken
}

// GetCentsPerTokenOk returns a tuple with the CentsPerToken field value
// and a boolean to check if the value has been set.
func (o *CreateCbxAdCreditPurchaseResponse) GetCentsPerTokenOk() (*float32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.CentsPerToken, true
}

// SetCentsPerToken sets field value
func (o *CreateCbxAdCreditPurchaseResponse) SetCentsPerToken(v float32) {
	o.CentsPerToken = v
}

// GetBalanceCents returns the BalanceCents field value
func (o *CreateCbxAdCreditPurchaseResponse) GetBalanceCents() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.BalanceCents
}

// GetBalanceCentsOk returns a tuple with the BalanceCents field value
// and a boolean to check if the value has been set.
func (o *CreateCbxAdCreditPurchaseResponse) GetBalanceCentsOk() (*float32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.BalanceCents, true
}

// SetBalanceCents sets field value
func (o *CreateCbxAdCreditPurchaseResponse) SetBalanceCents(v float32) {
	o.BalanceCents = v
}

// GetDuplicate returns the Duplicate field value
func (o *CreateCbxAdCreditPurchaseResponse) GetDuplicate() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Duplicate
}

// GetDuplicateOk returns a tuple with the Duplicate field value
// and a boolean to check if the value has been set.
func (o *CreateCbxAdCreditPurchaseResponse) GetDuplicateOk() (*bool, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Duplicate, true
}

// SetDuplicate sets field value
func (o *CreateCbxAdCreditPurchaseResponse) SetDuplicate(v bool) {
	o.Duplicate = v
}

func (o CreateCbxAdCreditPurchaseResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["creditCents"] = o.CreditCents
	}
	if true {
		toSerialize["baseUnitsPaid"] = o.BaseUnitsPaid
	}
	if true {
		toSerialize["centsPerToken"] = o.CentsPerToken
	}
	if true {
		toSerialize["balanceCents"] = o.BalanceCents
	}
	if true {
		toSerialize["duplicate"] = o.Duplicate
	}
	return json.Marshal(toSerialize)
}

type NullableCreateCbxAdCreditPurchaseResponse struct {
	value *CreateCbxAdCreditPurchaseResponse
	isSet bool
}

func (v NullableCreateCbxAdCreditPurchaseResponse) Get() *CreateCbxAdCreditPurchaseResponse {
	return v.value
}

func (v *NullableCreateCbxAdCreditPurchaseResponse) Set(val *CreateCbxAdCreditPurchaseResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateCbxAdCreditPurchaseResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateCbxAdCreditPurchaseResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateCbxAdCreditPurchaseResponse(val *CreateCbxAdCreditPurchaseResponse) *NullableCreateCbxAdCreditPurchaseResponse {
	return &NullableCreateCbxAdCreditPurchaseResponse{value: val, isSet: true}
}

func (v NullableCreateCbxAdCreditPurchaseResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateCbxAdCreditPurchaseResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


