/*
Crossly Seller API

The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crossly

import (
	"encoding/json"
)

// GetWorkflowChainResponse struct for GetWorkflowChainResponse
type GetWorkflowChainResponse struct {
	Chain GetWorkflowChainResponseChain `json:"chain"`
	Steps []ListWorkflowChainsItemSteps `json:"steps"`
}

// NewGetWorkflowChainResponse instantiates a new GetWorkflowChainResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetWorkflowChainResponse(chain GetWorkflowChainResponseChain, steps []ListWorkflowChainsItemSteps) *GetWorkflowChainResponse {
	this := GetWorkflowChainResponse{}
	this.Chain = chain
	this.Steps = steps
	return &this
}

// NewGetWorkflowChainResponseWithDefaults instantiates a new GetWorkflowChainResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetWorkflowChainResponseWithDefaults() *GetWorkflowChainResponse {
	this := GetWorkflowChainResponse{}
	return &this
}

// GetChain returns the Chain field value
func (o *GetWorkflowChainResponse) GetChain() GetWorkflowChainResponseChain {
	if o == nil {
		var ret GetWorkflowChainResponseChain
		return ret
	}

	return o.Chain
}

// GetChainOk returns a tuple with the Chain field value
// and a boolean to check if the value has been set.
func (o *GetWorkflowChainResponse) GetChainOk() (*GetWorkflowChainResponseChain, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Chain, true
}

// SetChain sets field value
func (o *GetWorkflowChainResponse) SetChain(v GetWorkflowChainResponseChain) {
	o.Chain = v
}

// GetSteps returns the Steps field value
func (o *GetWorkflowChainResponse) GetSteps() []ListWorkflowChainsItemSteps {
	if o == nil {
		var ret []ListWorkflowChainsItemSteps
		return ret
	}

	return o.Steps
}

// GetStepsOk returns a tuple with the Steps field value
// and a boolean to check if the value has been set.
func (o *GetWorkflowChainResponse) GetStepsOk() ([]ListWorkflowChainsItemSteps, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Steps, true
}

// SetSteps sets field value
func (o *GetWorkflowChainResponse) SetSteps(v []ListWorkflowChainsItemSteps) {
	o.Steps = v
}

func (o GetWorkflowChainResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["chain"] = o.Chain
	}
	if true {
		toSerialize["steps"] = o.Steps
	}
	return json.Marshal(toSerialize)
}

type NullableGetWorkflowChainResponse struct {
	value *GetWorkflowChainResponse
	isSet bool
}

func (v NullableGetWorkflowChainResponse) Get() *GetWorkflowChainResponse {
	return v.value
}

func (v *NullableGetWorkflowChainResponse) Set(val *GetWorkflowChainResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetWorkflowChainResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetWorkflowChainResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetWorkflowChainResponse(val *GetWorkflowChainResponse) *NullableGetWorkflowChainResponse {
	return &NullableGetWorkflowChainResponse{value: val, isSet: true}
}

func (v NullableGetWorkflowChainResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetWorkflowChainResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


