/*
Crossly Seller API

The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crossly

import (
	"encoding/json"
)

// CreateCbxWalletPaymentConfirmResponse struct for CreateCbxWalletPaymentConfirmResponse
type CreateCbxWalletPaymentConfirmResponse struct {
	PaymentId string `json:"paymentId"`
	Duplicate bool `json:"duplicate"`
	ReleaseDecision string `json:"releaseDecision"`
	ReleaseReason string `json:"releaseReason"`
	BaseUnits string `json:"baseUnits"`
	ValueCents float32 `json:"valueCents"`
	CentsPerToken float32 `json:"centsPerToken"`
	PayerAddress string `json:"payerAddress"`
	RiskLevel NullableString `json:"riskLevel,omitempty"`
	RiskExposures []string `json:"riskExposures"`
	ScreeningProvider NullableString `json:"screeningProvider,omitempty"`
}

// NewCreateCbxWalletPaymentConfirmResponse instantiates a new CreateCbxWalletPaymentConfirmResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateCbxWalletPaymentConfirmResponse(paymentId string, duplicate bool, releaseDecision string, releaseReason string, baseUnits string, valueCents float32, centsPerToken float32, payerAddress string, riskExposures []string) *CreateCbxWalletPaymentConfirmResponse {
	this := CreateCbxWalletPaymentConfirmResponse{}
	this.PaymentId = paymentId
	this.Duplicate = duplicate
	this.ReleaseDecision = releaseDecision
	this.ReleaseReason = releaseReason
	this.BaseUnits = baseUnits
	this.ValueCents = valueCents
	this.CentsPerToken = centsPerToken
	this.PayerAddress = payerAddress
	this.RiskExposures = riskExposures
	return &this
}

// NewCreateCbxWalletPaymentConfirmResponseWithDefaults instantiates a new CreateCbxWalletPaymentConfirmResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateCbxWalletPaymentConfirmResponseWithDefaults() *CreateCbxWalletPaymentConfirmResponse {
	this := CreateCbxWalletPaymentConfirmResponse{}
	return &this
}

// GetPaymentId returns the PaymentId field value
func (o *CreateCbxWalletPaymentConfirmResponse) GetPaymentId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PaymentId
}

// GetPaymentIdOk returns a tuple with the PaymentId field value
// and a boolean to check if the value has been set.
func (o *CreateCbxWalletPaymentConfirmResponse) GetPaymentIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.PaymentId, true
}

// SetPaymentId sets field value
func (o *CreateCbxWalletPaymentConfirmResponse) SetPaymentId(v string) {
	o.PaymentId = v
}

// GetDuplicate returns the Duplicate field value
func (o *CreateCbxWalletPaymentConfirmResponse) GetDuplicate() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Duplicate
}

// GetDuplicateOk returns a tuple with the Duplicate field value
// and a boolean to check if the value has been set.
func (o *CreateCbxWalletPaymentConfirmResponse) GetDuplicateOk() (*bool, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Duplicate, true
}

// SetDuplicate sets field value
func (o *CreateCbxWalletPaymentConfirmResponse) SetDuplicate(v bool) {
	o.Duplicate = v
}

// GetReleaseDecision returns the ReleaseDecision field value
func (o *CreateCbxWalletPaymentConfirmResponse) GetReleaseDecision() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ReleaseDecision
}

// GetReleaseDecisionOk returns a tuple with the ReleaseDecision field value
// and a boolean to check if the value has been set.
func (o *CreateCbxWalletPaymentConfirmResponse) GetReleaseDecisionOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ReleaseDecision, true
}

// SetReleaseDecision sets field value
func (o *CreateCbxWalletPaymentConfirmResponse) SetReleaseDecision(v string) {
	o.ReleaseDecision = v
}

// GetReleaseReason returns the ReleaseReason field value
func (o *CreateCbxWalletPaymentConfirmResponse) GetReleaseReason() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ReleaseReason
}

// GetReleaseReasonOk returns a tuple with the ReleaseReason field value
// and a boolean to check if the value has been set.
func (o *CreateCbxWalletPaymentConfirmResponse) GetReleaseReasonOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ReleaseReason, true
}

// SetReleaseReason sets field value
func (o *CreateCbxWalletPaymentConfirmResponse) SetReleaseReason(v string) {
	o.ReleaseReason = v
}

// GetBaseUnits returns the BaseUnits field value
func (o *CreateCbxWalletPaymentConfirmResponse) GetBaseUnits() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BaseUnits
}

// GetBaseUnitsOk returns a tuple with the BaseUnits field value
// and a boolean to check if the value has been set.
func (o *CreateCbxWalletPaymentConfirmResponse) GetBaseUnitsOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.BaseUnits, true
}

// SetBaseUnits sets field value
func (o *CreateCbxWalletPaymentConfirmResponse) SetBaseUnits(v string) {
	o.BaseUnits = v
}

// GetValueCents returns the ValueCents field value
func (o *CreateCbxWalletPaymentConfirmResponse) GetValueCents() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.ValueCents
}

// GetValueCentsOk returns a tuple with the ValueCents field value
// and a boolean to check if the value has been set.
func (o *CreateCbxWalletPaymentConfirmResponse) GetValueCentsOk() (*float32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ValueCents, true
}

// SetValueCents sets field value
func (o *CreateCbxWalletPaymentConfirmResponse) SetValueCents(v float32) {
	o.ValueCents = v
}

// GetCentsPerToken returns the CentsPerToken field value
func (o *CreateCbxWalletPaymentConfirmResponse) GetCentsPerToken() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.CentsPerToken
}

// GetCentsPerTokenOk returns a tuple with the CentsPerToken field value
// and a boolean to check if the value has been set.
func (o *CreateCbxWalletPaymentConfirmResponse) GetCentsPerTokenOk() (*float32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.CentsPerToken, true
}

// SetCentsPerToken sets field value
func (o *CreateCbxWalletPaymentConfirmResponse) SetCentsPerToken(v float32) {
	o.CentsPerToken = v
}

// GetPayerAddress returns the PayerAddress field value
func (o *CreateCbxWalletPaymentConfirmResponse) GetPayerAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PayerAddress
}

// GetPayerAddressOk returns a tuple with the PayerAddress field value
// and a boolean to check if the value has been set.
func (o *CreateCbxWalletPaymentConfirmResponse) GetPayerAddressOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.PayerAddress, true
}

// SetPayerAddress sets field value
func (o *CreateCbxWalletPaymentConfirmResponse) SetPayerAddress(v string) {
	o.PayerAddress = v
}

// GetRiskLevel returns the RiskLevel field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateCbxWalletPaymentConfirmResponse) GetRiskLevel() string {
	if o == nil || o.RiskLevel.Get() == nil {
		var ret string
		return ret
	}
	return *o.RiskLevel.Get()
}

// GetRiskLevelOk returns a tuple with the RiskLevel field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateCbxWalletPaymentConfirmResponse) GetRiskLevelOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.RiskLevel.Get(), o.RiskLevel.IsSet()
}

// HasRiskLevel returns a boolean if a field has been set.
func (o *CreateCbxWalletPaymentConfirmResponse) HasRiskLevel() bool {
	if o != nil && o.RiskLevel.IsSet() {
		return true
	}

	return false
}

// SetRiskLevel gets a reference to the given NullableString and assigns it to the RiskLevel field.
func (o *CreateCbxWalletPaymentConfirmResponse) SetRiskLevel(v string) {
	o.RiskLevel.Set(&v)
}
// SetRiskLevelNil sets the value for RiskLevel to be an explicit nil
func (o *CreateCbxWalletPaymentConfirmResponse) SetRiskLevelNil() {
	o.RiskLevel.Set(nil)
}

// UnsetRiskLevel ensures that no value is present for RiskLevel, not even an explicit nil
func (o *CreateCbxWalletPaymentConfirmResponse) UnsetRiskLevel() {
	o.RiskLevel.Unset()
}

// GetRiskExposures returns the RiskExposures field value
func (o *CreateCbxWalletPaymentConfirmResponse) GetRiskExposures() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.RiskExposures
}

// GetRiskExposuresOk returns a tuple with the RiskExposures field value
// and a boolean to check if the value has been set.
func (o *CreateCbxWalletPaymentConfirmResponse) GetRiskExposuresOk() ([]string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.RiskExposures, true
}

// SetRiskExposures sets field value
func (o *CreateCbxWalletPaymentConfirmResponse) SetRiskExposures(v []string) {
	o.RiskExposures = v
}

// GetScreeningProvider returns the ScreeningProvider field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateCbxWalletPaymentConfirmResponse) GetScreeningProvider() string {
	if o == nil || o.ScreeningProvider.Get() == nil {
		var ret string
		return ret
	}
	return *o.ScreeningProvider.Get()
}

// GetScreeningProviderOk returns a tuple with the ScreeningProvider field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateCbxWalletPaymentConfirmResponse) GetScreeningProviderOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.ScreeningProvider.Get(), o.ScreeningProvider.IsSet()
}

// HasScreeningProvider returns a boolean if a field has been set.
func (o *CreateCbxWalletPaymentConfirmResponse) HasScreeningProvider() bool {
	if o != nil && o.ScreeningProvider.IsSet() {
		return true
	}

	return false
}

// SetScreeningProvider gets a reference to the given NullableString and assigns it to the ScreeningProvider field.
func (o *CreateCbxWalletPaymentConfirmResponse) SetScreeningProvider(v string) {
	o.ScreeningProvider.Set(&v)
}
// SetScreeningProviderNil sets the value for ScreeningProvider to be an explicit nil
func (o *CreateCbxWalletPaymentConfirmResponse) SetScreeningProviderNil() {
	o.ScreeningProvider.Set(nil)
}

// UnsetScreeningProvider ensures that no value is present for ScreeningProvider, not even an explicit nil
func (o *CreateCbxWalletPaymentConfirmResponse) UnsetScreeningProvider() {
	o.ScreeningProvider.Unset()
}

func (o CreateCbxWalletPaymentConfirmResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["paymentId"] = o.PaymentId
	}
	if true {
		toSerialize["duplicate"] = o.Duplicate
	}
	if true {
		toSerialize["releaseDecision"] = o.ReleaseDecision
	}
	if true {
		toSerialize["releaseReason"] = o.ReleaseReason
	}
	if true {
		toSerialize["baseUnits"] = o.BaseUnits
	}
	if true {
		toSerialize["valueCents"] = o.ValueCents
	}
	if true {
		toSerialize["centsPerToken"] = o.CentsPerToken
	}
	if true {
		toSerialize["payerAddress"] = o.PayerAddress
	}
	if o.RiskLevel.IsSet() {
		toSerialize["riskLevel"] = o.RiskLevel.Get()
	}
	if true {
		toSerialize["riskExposures"] = o.RiskExposures
	}
	if o.ScreeningProvider.IsSet() {
		toSerialize["screeningProvider"] = o.ScreeningProvider.Get()
	}
	return json.Marshal(toSerialize)
}

type NullableCreateCbxWalletPaymentConfirmResponse struct {
	value *CreateCbxWalletPaymentConfirmResponse
	isSet bool
}

func (v NullableCreateCbxWalletPaymentConfirmResponse) Get() *CreateCbxWalletPaymentConfirmResponse {
	return v.value
}

func (v *NullableCreateCbxWalletPaymentConfirmResponse) Set(val *CreateCbxWalletPaymentConfirmResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateCbxWalletPaymentConfirmResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateCbxWalletPaymentConfirmResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateCbxWalletPaymentConfirmResponse(val *CreateCbxWalletPaymentConfirmResponse) *NullableCreateCbxWalletPaymentConfirmResponse {
	return &NullableCreateCbxWalletPaymentConfirmResponse{value: val, isSet: true}
}

func (v NullableCreateCbxWalletPaymentConfirmResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateCbxWalletPaymentConfirmResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


