/*
Crossly Seller API

The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crossly

import (
	"encoding/json"
)

// CreateListingMagicFillResponse struct for CreateListingMagicFillResponse
type CreateListingMagicFillResponse struct {
	Filled map[string]interface{} `json:"filled"`
	Count float32 `json:"count"`
	// False when the seller has no AI provider configured — `count: 0` then means \"nothing new could be resolved\" rather than \"already complete\", a distinction the caller (web's useMagicFill toast) needs but `count` alone can't express. True whenever a provider IS configured, even if the AI call itself failed for some other reason (network, bad key) — that's a different problem than \"connect a provider.\"
	AiAvailable bool `json:"aiAvailable"`
}

// NewCreateListingMagicFillResponse instantiates a new CreateListingMagicFillResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateListingMagicFillResponse(filled map[string]interface{}, count float32, aiAvailable bool) *CreateListingMagicFillResponse {
	this := CreateListingMagicFillResponse{}
	this.Filled = filled
	this.Count = count
	this.AiAvailable = aiAvailable
	return &this
}

// NewCreateListingMagicFillResponseWithDefaults instantiates a new CreateListingMagicFillResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateListingMagicFillResponseWithDefaults() *CreateListingMagicFillResponse {
	this := CreateListingMagicFillResponse{}
	return &this
}

// GetFilled returns the Filled field value
func (o *CreateListingMagicFillResponse) GetFilled() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Filled
}

// GetFilledOk returns a tuple with the Filled field value
// and a boolean to check if the value has been set.
func (o *CreateListingMagicFillResponse) GetFilledOk() (map[string]interface{}, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Filled, true
}

// SetFilled sets field value
func (o *CreateListingMagicFillResponse) SetFilled(v map[string]interface{}) {
	o.Filled = v
}

// GetCount returns the Count field value
func (o *CreateListingMagicFillResponse) GetCount() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *CreateListingMagicFillResponse) GetCountOk() (*float32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *CreateListingMagicFillResponse) SetCount(v float32) {
	o.Count = v
}

// GetAiAvailable returns the AiAvailable field value
func (o *CreateListingMagicFillResponse) GetAiAvailable() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.AiAvailable
}

// GetAiAvailableOk returns a tuple with the AiAvailable field value
// and a boolean to check if the value has been set.
func (o *CreateListingMagicFillResponse) GetAiAvailableOk() (*bool, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.AiAvailable, true
}

// SetAiAvailable sets field value
func (o *CreateListingMagicFillResponse) SetAiAvailable(v bool) {
	o.AiAvailable = v
}

func (o CreateListingMagicFillResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["filled"] = o.Filled
	}
	if true {
		toSerialize["count"] = o.Count
	}
	if true {
		toSerialize["aiAvailable"] = o.AiAvailable
	}
	return json.Marshal(toSerialize)
}

type NullableCreateListingMagicFillResponse struct {
	value *CreateListingMagicFillResponse
	isSet bool
}

func (v NullableCreateListingMagicFillResponse) Get() *CreateListingMagicFillResponse {
	return v.value
}

func (v *NullableCreateListingMagicFillResponse) Set(val *CreateListingMagicFillResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateListingMagicFillResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateListingMagicFillResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateListingMagicFillResponse(val *CreateListingMagicFillResponse) *NullableCreateListingMagicFillResponse {
	return &NullableCreateListingMagicFillResponse{value: val, isSet: true}
}

func (v NullableCreateListingMagicFillResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateListingMagicFillResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


