/*
Crossly Seller API

The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crossly

import (
	"encoding/json"
)

// GetAutomationRuleExportByIdResponse struct for GetAutomationRuleExportByIdResponse
type GetAutomationRuleExportByIdResponse struct {
	Name string `json:"name"`
	Action GetAutomationRuleExportResponseAction `json:"action"`
	Trigger GetAutomationRuleExportResponseAction `json:"trigger"`
	SchemaVersion float32 `json:"schemaVersion"`
	Condition NullableGetAutomationRuleExportResponseCondition `json:"condition,omitempty"`
	Metadata NullableGetAutomationRuleExportResponseMetadata `json:"metadata,omitempty"`
	Description NullableString `json:"description,omitempty"`
	Platforms []string `json:"platforms,omitempty"`
	// Optional reference to the public schema URL — purely cosmetic.
	Schema NullableString `json:"$schema,omitempty"`
}

// NewGetAutomationRuleExportByIdResponse instantiates a new GetAutomationRuleExportByIdResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAutomationRuleExportByIdResponse(name string, action GetAutomationRuleExportResponseAction, trigger GetAutomationRuleExportResponseAction, schemaVersion float32) *GetAutomationRuleExportByIdResponse {
	this := GetAutomationRuleExportByIdResponse{}
	this.Name = name
	this.Action = action
	this.Trigger = trigger
	this.SchemaVersion = schemaVersion
	return &this
}

// NewGetAutomationRuleExportByIdResponseWithDefaults instantiates a new GetAutomationRuleExportByIdResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAutomationRuleExportByIdResponseWithDefaults() *GetAutomationRuleExportByIdResponse {
	this := GetAutomationRuleExportByIdResponse{}
	return &this
}

// GetName returns the Name field value
func (o *GetAutomationRuleExportByIdResponse) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *GetAutomationRuleExportByIdResponse) GetNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *GetAutomationRuleExportByIdResponse) SetName(v string) {
	o.Name = v
}

// GetAction returns the Action field value
func (o *GetAutomationRuleExportByIdResponse) GetAction() GetAutomationRuleExportResponseAction {
	if o == nil {
		var ret GetAutomationRuleExportResponseAction
		return ret
	}

	return o.Action
}

// GetActionOk returns a tuple with the Action field value
// and a boolean to check if the value has been set.
func (o *GetAutomationRuleExportByIdResponse) GetActionOk() (*GetAutomationRuleExportResponseAction, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Action, true
}

// SetAction sets field value
func (o *GetAutomationRuleExportByIdResponse) SetAction(v GetAutomationRuleExportResponseAction) {
	o.Action = v
}

// GetTrigger returns the Trigger field value
func (o *GetAutomationRuleExportByIdResponse) GetTrigger() GetAutomationRuleExportResponseAction {
	if o == nil {
		var ret GetAutomationRuleExportResponseAction
		return ret
	}

	return o.Trigger
}

// GetTriggerOk returns a tuple with the Trigger field value
// and a boolean to check if the value has been set.
func (o *GetAutomationRuleExportByIdResponse) GetTriggerOk() (*GetAutomationRuleExportResponseAction, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Trigger, true
}

// SetTrigger sets field value
func (o *GetAutomationRuleExportByIdResponse) SetTrigger(v GetAutomationRuleExportResponseAction) {
	o.Trigger = v
}

// GetSchemaVersion returns the SchemaVersion field value
func (o *GetAutomationRuleExportByIdResponse) GetSchemaVersion() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.SchemaVersion
}

// GetSchemaVersionOk returns a tuple with the SchemaVersion field value
// and a boolean to check if the value has been set.
func (o *GetAutomationRuleExportByIdResponse) GetSchemaVersionOk() (*float32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.SchemaVersion, true
}

// SetSchemaVersion sets field value
func (o *GetAutomationRuleExportByIdResponse) SetSchemaVersion(v float32) {
	o.SchemaVersion = v
}

// GetCondition returns the Condition field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetAutomationRuleExportByIdResponse) GetCondition() GetAutomationRuleExportResponseCondition {
	if o == nil || o.Condition.Get() == nil {
		var ret GetAutomationRuleExportResponseCondition
		return ret
	}
	return *o.Condition.Get()
}

// GetConditionOk returns a tuple with the Condition field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetAutomationRuleExportByIdResponse) GetConditionOk() (*GetAutomationRuleExportResponseCondition, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Condition.Get(), o.Condition.IsSet()
}

// HasCondition returns a boolean if a field has been set.
func (o *GetAutomationRuleExportByIdResponse) HasCondition() bool {
	if o != nil && o.Condition.IsSet() {
		return true
	}

	return false
}

// SetCondition gets a reference to the given NullableGetAutomationRuleExportResponseCondition and assigns it to the Condition field.
func (o *GetAutomationRuleExportByIdResponse) SetCondition(v GetAutomationRuleExportResponseCondition) {
	o.Condition.Set(&v)
}
// SetConditionNil sets the value for Condition to be an explicit nil
func (o *GetAutomationRuleExportByIdResponse) SetConditionNil() {
	o.Condition.Set(nil)
}

// UnsetCondition ensures that no value is present for Condition, not even an explicit nil
func (o *GetAutomationRuleExportByIdResponse) UnsetCondition() {
	o.Condition.Unset()
}

// GetMetadata returns the Metadata field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetAutomationRuleExportByIdResponse) GetMetadata() GetAutomationRuleExportResponseMetadata {
	if o == nil || o.Metadata.Get() == nil {
		var ret GetAutomationRuleExportResponseMetadata
		return ret
	}
	return *o.Metadata.Get()
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetAutomationRuleExportByIdResponse) GetMetadataOk() (*GetAutomationRuleExportResponseMetadata, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Metadata.Get(), o.Metadata.IsSet()
}

// HasMetadata returns a boolean if a field has been set.
func (o *GetAutomationRuleExportByIdResponse) HasMetadata() bool {
	if o != nil && o.Metadata.IsSet() {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given NullableGetAutomationRuleExportResponseMetadata and assigns it to the Metadata field.
func (o *GetAutomationRuleExportByIdResponse) SetMetadata(v GetAutomationRuleExportResponseMetadata) {
	o.Metadata.Set(&v)
}
// SetMetadataNil sets the value for Metadata to be an explicit nil
func (o *GetAutomationRuleExportByIdResponse) SetMetadataNil() {
	o.Metadata.Set(nil)
}

// UnsetMetadata ensures that no value is present for Metadata, not even an explicit nil
func (o *GetAutomationRuleExportByIdResponse) UnsetMetadata() {
	o.Metadata.Unset()
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetAutomationRuleExportByIdResponse) GetDescription() string {
	if o == nil || o.Description.Get() == nil {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetAutomationRuleExportByIdResponse) GetDescriptionOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *GetAutomationRuleExportByIdResponse) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *GetAutomationRuleExportByIdResponse) SetDescription(v string) {
	o.Description.Set(&v)
}
// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *GetAutomationRuleExportByIdResponse) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *GetAutomationRuleExportByIdResponse) UnsetDescription() {
	o.Description.Unset()
}

// GetPlatforms returns the Platforms field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetAutomationRuleExportByIdResponse) GetPlatforms() []string {
	if o == nil  {
		var ret []string
		return ret
	}
	return o.Platforms
}

// GetPlatformsOk returns a tuple with the Platforms field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetAutomationRuleExportByIdResponse) GetPlatformsOk() ([]string, bool) {
	if o == nil || o.Platforms == nil {
		return nil, false
	}
	return o.Platforms, true
}

// HasPlatforms returns a boolean if a field has been set.
func (o *GetAutomationRuleExportByIdResponse) HasPlatforms() bool {
	if o != nil && o.Platforms != nil {
		return true
	}

	return false
}

// SetPlatforms gets a reference to the given []string and assigns it to the Platforms field.
func (o *GetAutomationRuleExportByIdResponse) SetPlatforms(v []string) {
	o.Platforms = v
}

// GetSchema returns the Schema field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetAutomationRuleExportByIdResponse) GetSchema() string {
	if o == nil || o.Schema.Get() == nil {
		var ret string
		return ret
	}
	return *o.Schema.Get()
}

// GetSchemaOk returns a tuple with the Schema field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetAutomationRuleExportByIdResponse) GetSchemaOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Schema.Get(), o.Schema.IsSet()
}

// HasSchema returns a boolean if a field has been set.
func (o *GetAutomationRuleExportByIdResponse) HasSchema() bool {
	if o != nil && o.Schema.IsSet() {
		return true
	}

	return false
}

// SetSchema gets a reference to the given NullableString and assigns it to the Schema field.
func (o *GetAutomationRuleExportByIdResponse) SetSchema(v string) {
	o.Schema.Set(&v)
}
// SetSchemaNil sets the value for Schema to be an explicit nil
func (o *GetAutomationRuleExportByIdResponse) SetSchemaNil() {
	o.Schema.Set(nil)
}

// UnsetSchema ensures that no value is present for Schema, not even an explicit nil
func (o *GetAutomationRuleExportByIdResponse) UnsetSchema() {
	o.Schema.Unset()
}

func (o GetAutomationRuleExportByIdResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["action"] = o.Action
	}
	if true {
		toSerialize["trigger"] = o.Trigger
	}
	if true {
		toSerialize["schemaVersion"] = o.SchemaVersion
	}
	if o.Condition.IsSet() {
		toSerialize["condition"] = o.Condition.Get()
	}
	if o.Metadata.IsSet() {
		toSerialize["metadata"] = o.Metadata.Get()
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if o.Platforms != nil {
		toSerialize["platforms"] = o.Platforms
	}
	if o.Schema.IsSet() {
		toSerialize["$schema"] = o.Schema.Get()
	}
	return json.Marshal(toSerialize)
}

type NullableGetAutomationRuleExportByIdResponse struct {
	value *GetAutomationRuleExportByIdResponse
	isSet bool
}

func (v NullableGetAutomationRuleExportByIdResponse) Get() *GetAutomationRuleExportByIdResponse {
	return v.value
}

func (v *NullableGetAutomationRuleExportByIdResponse) Set(val *GetAutomationRuleExportByIdResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAutomationRuleExportByIdResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAutomationRuleExportByIdResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAutomationRuleExportByIdResponse(val *GetAutomationRuleExportByIdResponse) *NullableGetAutomationRuleExportByIdResponse {
	return &NullableGetAutomationRuleExportByIdResponse{value: val, isSet: true}
}

func (v NullableGetAutomationRuleExportByIdResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAutomationRuleExportByIdResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


