/*
Crossly Seller API

The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crossly

import (
	"encoding/json"
)

// CreateCbxClaimQuoteResponse struct for CreateCbxClaimQuoteResponse
type CreateCbxClaimQuoteResponse struct {
	RequestedBaseUnits string `json:"requestedBaseUnits"`
	ServiceFeeBaseUnits string `json:"serviceFeeBaseUnits"`
	NetworkFeeBaseUnits string `json:"networkFeeBaseUnits"`
	NetBaseUnits string `json:"netBaseUnits"`
	RequestedCents float32 `json:"requestedCents"`
	ServiceFeeCents float32 `json:"serviceFeeCents"`
	NetworkFeeCents float32 `json:"networkFeeCents"`
	NetCents float32 `json:"netCents"`
	AppliedBound string `json:"appliedBound"`
}

// NewCreateCbxClaimQuoteResponse instantiates a new CreateCbxClaimQuoteResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateCbxClaimQuoteResponse(requestedBaseUnits string, serviceFeeBaseUnits string, networkFeeBaseUnits string, netBaseUnits string, requestedCents float32, serviceFeeCents float32, networkFeeCents float32, netCents float32, appliedBound string) *CreateCbxClaimQuoteResponse {
	this := CreateCbxClaimQuoteResponse{}
	this.RequestedBaseUnits = requestedBaseUnits
	this.ServiceFeeBaseUnits = serviceFeeBaseUnits
	this.NetworkFeeBaseUnits = networkFeeBaseUnits
	this.NetBaseUnits = netBaseUnits
	this.RequestedCents = requestedCents
	this.ServiceFeeCents = serviceFeeCents
	this.NetworkFeeCents = networkFeeCents
	this.NetCents = netCents
	this.AppliedBound = appliedBound
	return &this
}

// NewCreateCbxClaimQuoteResponseWithDefaults instantiates a new CreateCbxClaimQuoteResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateCbxClaimQuoteResponseWithDefaults() *CreateCbxClaimQuoteResponse {
	this := CreateCbxClaimQuoteResponse{}
	return &this
}

// GetRequestedBaseUnits returns the RequestedBaseUnits field value
func (o *CreateCbxClaimQuoteResponse) GetRequestedBaseUnits() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RequestedBaseUnits
}

// GetRequestedBaseUnitsOk returns a tuple with the RequestedBaseUnits field value
// and a boolean to check if the value has been set.
func (o *CreateCbxClaimQuoteResponse) GetRequestedBaseUnitsOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.RequestedBaseUnits, true
}

// SetRequestedBaseUnits sets field value
func (o *CreateCbxClaimQuoteResponse) SetRequestedBaseUnits(v string) {
	o.RequestedBaseUnits = v
}

// GetServiceFeeBaseUnits returns the ServiceFeeBaseUnits field value
func (o *CreateCbxClaimQuoteResponse) GetServiceFeeBaseUnits() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ServiceFeeBaseUnits
}

// GetServiceFeeBaseUnitsOk returns a tuple with the ServiceFeeBaseUnits field value
// and a boolean to check if the value has been set.
func (o *CreateCbxClaimQuoteResponse) GetServiceFeeBaseUnitsOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ServiceFeeBaseUnits, true
}

// SetServiceFeeBaseUnits sets field value
func (o *CreateCbxClaimQuoteResponse) SetServiceFeeBaseUnits(v string) {
	o.ServiceFeeBaseUnits = v
}

// GetNetworkFeeBaseUnits returns the NetworkFeeBaseUnits field value
func (o *CreateCbxClaimQuoteResponse) GetNetworkFeeBaseUnits() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NetworkFeeBaseUnits
}

// GetNetworkFeeBaseUnitsOk returns a tuple with the NetworkFeeBaseUnits field value
// and a boolean to check if the value has been set.
func (o *CreateCbxClaimQuoteResponse) GetNetworkFeeBaseUnitsOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.NetworkFeeBaseUnits, true
}

// SetNetworkFeeBaseUnits sets field value
func (o *CreateCbxClaimQuoteResponse) SetNetworkFeeBaseUnits(v string) {
	o.NetworkFeeBaseUnits = v
}

// GetNetBaseUnits returns the NetBaseUnits field value
func (o *CreateCbxClaimQuoteResponse) GetNetBaseUnits() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NetBaseUnits
}

// GetNetBaseUnitsOk returns a tuple with the NetBaseUnits field value
// and a boolean to check if the value has been set.
func (o *CreateCbxClaimQuoteResponse) GetNetBaseUnitsOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.NetBaseUnits, true
}

// SetNetBaseUnits sets field value
func (o *CreateCbxClaimQuoteResponse) SetNetBaseUnits(v string) {
	o.NetBaseUnits = v
}

// GetRequestedCents returns the RequestedCents field value
func (o *CreateCbxClaimQuoteResponse) GetRequestedCents() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.RequestedCents
}

// GetRequestedCentsOk returns a tuple with the RequestedCents field value
// and a boolean to check if the value has been set.
func (o *CreateCbxClaimQuoteResponse) GetRequestedCentsOk() (*float32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.RequestedCents, true
}

// SetRequestedCents sets field value
func (o *CreateCbxClaimQuoteResponse) SetRequestedCents(v float32) {
	o.RequestedCents = v
}

// GetServiceFeeCents returns the ServiceFeeCents field value
func (o *CreateCbxClaimQuoteResponse) GetServiceFeeCents() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.ServiceFeeCents
}

// GetServiceFeeCentsOk returns a tuple with the ServiceFeeCents field value
// and a boolean to check if the value has been set.
func (o *CreateCbxClaimQuoteResponse) GetServiceFeeCentsOk() (*float32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ServiceFeeCents, true
}

// SetServiceFeeCents sets field value
func (o *CreateCbxClaimQuoteResponse) SetServiceFeeCents(v float32) {
	o.ServiceFeeCents = v
}

// GetNetworkFeeCents returns the NetworkFeeCents field value
func (o *CreateCbxClaimQuoteResponse) GetNetworkFeeCents() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.NetworkFeeCents
}

// GetNetworkFeeCentsOk returns a tuple with the NetworkFeeCents field value
// and a boolean to check if the value has been set.
func (o *CreateCbxClaimQuoteResponse) GetNetworkFeeCentsOk() (*float32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.NetworkFeeCents, true
}

// SetNetworkFeeCents sets field value
func (o *CreateCbxClaimQuoteResponse) SetNetworkFeeCents(v float32) {
	o.NetworkFeeCents = v
}

// GetNetCents returns the NetCents field value
func (o *CreateCbxClaimQuoteResponse) GetNetCents() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.NetCents
}

// GetNetCentsOk returns a tuple with the NetCents field value
// and a boolean to check if the value has been set.
func (o *CreateCbxClaimQuoteResponse) GetNetCentsOk() (*float32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.NetCents, true
}

// SetNetCents sets field value
func (o *CreateCbxClaimQuoteResponse) SetNetCents(v float32) {
	o.NetCents = v
}

// GetAppliedBound returns the AppliedBound field value
func (o *CreateCbxClaimQuoteResponse) GetAppliedBound() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AppliedBound
}

// GetAppliedBoundOk returns a tuple with the AppliedBound field value
// and a boolean to check if the value has been set.
func (o *CreateCbxClaimQuoteResponse) GetAppliedBoundOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.AppliedBound, true
}

// SetAppliedBound sets field value
func (o *CreateCbxClaimQuoteResponse) SetAppliedBound(v string) {
	o.AppliedBound = v
}

func (o CreateCbxClaimQuoteResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["requestedBaseUnits"] = o.RequestedBaseUnits
	}
	if true {
		toSerialize["serviceFeeBaseUnits"] = o.ServiceFeeBaseUnits
	}
	if true {
		toSerialize["networkFeeBaseUnits"] = o.NetworkFeeBaseUnits
	}
	if true {
		toSerialize["netBaseUnits"] = o.NetBaseUnits
	}
	if true {
		toSerialize["requestedCents"] = o.RequestedCents
	}
	if true {
		toSerialize["serviceFeeCents"] = o.ServiceFeeCents
	}
	if true {
		toSerialize["networkFeeCents"] = o.NetworkFeeCents
	}
	if true {
		toSerialize["netCents"] = o.NetCents
	}
	if true {
		toSerialize["appliedBound"] = o.AppliedBound
	}
	return json.Marshal(toSerialize)
}

type NullableCreateCbxClaimQuoteResponse struct {
	value *CreateCbxClaimQuoteResponse
	isSet bool
}

func (v NullableCreateCbxClaimQuoteResponse) Get() *CreateCbxClaimQuoteResponse {
	return v.value
}

func (v *NullableCreateCbxClaimQuoteResponse) Set(val *CreateCbxClaimQuoteResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateCbxClaimQuoteResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateCbxClaimQuoteResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateCbxClaimQuoteResponse(val *CreateCbxClaimQuoteResponse) *NullableCreateCbxClaimQuoteResponse {
	return &NullableCreateCbxClaimQuoteResponse{value: val, isSet: true}
}

func (v NullableCreateCbxClaimQuoteResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateCbxClaimQuoteResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


