/*
Crossly Seller API

The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crossly

import (
	"encoding/json"
)

// CreateAiEnhanceDescriptionResponse struct for CreateAiEnhanceDescriptionResponse
type CreateAiEnhanceDescriptionResponse struct {
	EnhancedDescription string `json:"enhancedDescription"`
}

// NewCreateAiEnhanceDescriptionResponse instantiates a new CreateAiEnhanceDescriptionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateAiEnhanceDescriptionResponse(enhancedDescription string) *CreateAiEnhanceDescriptionResponse {
	this := CreateAiEnhanceDescriptionResponse{}
	this.EnhancedDescription = enhancedDescription
	return &this
}

// NewCreateAiEnhanceDescriptionResponseWithDefaults instantiates a new CreateAiEnhanceDescriptionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateAiEnhanceDescriptionResponseWithDefaults() *CreateAiEnhanceDescriptionResponse {
	this := CreateAiEnhanceDescriptionResponse{}
	return &this
}

// GetEnhancedDescription returns the EnhancedDescription field value
func (o *CreateAiEnhanceDescriptionResponse) GetEnhancedDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EnhancedDescription
}

// GetEnhancedDescriptionOk returns a tuple with the EnhancedDescription field value
// and a boolean to check if the value has been set.
func (o *CreateAiEnhanceDescriptionResponse) GetEnhancedDescriptionOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.EnhancedDescription, true
}

// SetEnhancedDescription sets field value
func (o *CreateAiEnhanceDescriptionResponse) SetEnhancedDescription(v string) {
	o.EnhancedDescription = v
}

func (o CreateAiEnhanceDescriptionResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["enhancedDescription"] = o.EnhancedDescription
	}
	return json.Marshal(toSerialize)
}

type NullableCreateAiEnhanceDescriptionResponse struct {
	value *CreateAiEnhanceDescriptionResponse
	isSet bool
}

func (v NullableCreateAiEnhanceDescriptionResponse) Get() *CreateAiEnhanceDescriptionResponse {
	return v.value
}

func (v *NullableCreateAiEnhanceDescriptionResponse) Set(val *CreateAiEnhanceDescriptionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateAiEnhanceDescriptionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateAiEnhanceDescriptionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateAiEnhanceDescriptionResponse(val *CreateAiEnhanceDescriptionResponse) *NullableCreateAiEnhanceDescriptionResponse {
	return &NullableCreateAiEnhanceDescriptionResponse{value: val, isSet: true}
}

func (v NullableCreateAiEnhanceDescriptionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateAiEnhanceDescriptionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


