/*
Crossly Seller API

The seller-facing Crossly API — listings, crossposting, orders, analytics. Authenticate with a Personal Access Token (`Authorization: Bearer crossly_pat_…`) or a seller OAuth token (`crossly_oat_…`), scoped `<domain>:<read|write>`. Buyer endpoints are a SEPARATE API with a separate principal — see the Crossly Buyer API.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crossly

import (
	"encoding/json"
)

// GetCatalogLookupResponse struct for GetCatalogLookupResponse
type GetCatalogLookupResponse struct {
	Identifier GetCatalogLookupResponseIdentifier `json:"identifier"`
	Offers []GetCatalogLookupResponseOffers `json:"offers"`
}

// NewGetCatalogLookupResponse instantiates a new GetCatalogLookupResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetCatalogLookupResponse(identifier GetCatalogLookupResponseIdentifier, offers []GetCatalogLookupResponseOffers) *GetCatalogLookupResponse {
	this := GetCatalogLookupResponse{}
	this.Identifier = identifier
	this.Offers = offers
	return &this
}

// NewGetCatalogLookupResponseWithDefaults instantiates a new GetCatalogLookupResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetCatalogLookupResponseWithDefaults() *GetCatalogLookupResponse {
	this := GetCatalogLookupResponse{}
	return &this
}

// GetIdentifier returns the Identifier field value
func (o *GetCatalogLookupResponse) GetIdentifier() GetCatalogLookupResponseIdentifier {
	if o == nil {
		var ret GetCatalogLookupResponseIdentifier
		return ret
	}

	return o.Identifier
}

// GetIdentifierOk returns a tuple with the Identifier field value
// and a boolean to check if the value has been set.
func (o *GetCatalogLookupResponse) GetIdentifierOk() (*GetCatalogLookupResponseIdentifier, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Identifier, true
}

// SetIdentifier sets field value
func (o *GetCatalogLookupResponse) SetIdentifier(v GetCatalogLookupResponseIdentifier) {
	o.Identifier = v
}

// GetOffers returns the Offers field value
func (o *GetCatalogLookupResponse) GetOffers() []GetCatalogLookupResponseOffers {
	if o == nil {
		var ret []GetCatalogLookupResponseOffers
		return ret
	}

	return o.Offers
}

// GetOffersOk returns a tuple with the Offers field value
// and a boolean to check if the value has been set.
func (o *GetCatalogLookupResponse) GetOffersOk() ([]GetCatalogLookupResponseOffers, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Offers, true
}

// SetOffers sets field value
func (o *GetCatalogLookupResponse) SetOffers(v []GetCatalogLookupResponseOffers) {
	o.Offers = v
}

func (o GetCatalogLookupResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["identifier"] = o.Identifier
	}
	if true {
		toSerialize["offers"] = o.Offers
	}
	return json.Marshal(toSerialize)
}

type NullableGetCatalogLookupResponse struct {
	value *GetCatalogLookupResponse
	isSet bool
}

func (v NullableGetCatalogLookupResponse) Get() *GetCatalogLookupResponse {
	return v.value
}

func (v *NullableGetCatalogLookupResponse) Set(val *GetCatalogLookupResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetCatalogLookupResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetCatalogLookupResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetCatalogLookupResponse(val *GetCatalogLookupResponse) *NullableGetCatalogLookupResponse {
	return &NullableGetCatalogLookupResponse{value: val, isSet: true}
}

func (v NullableGetCatalogLookupResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetCatalogLookupResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


