/*
Crossly Buyer API

The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crossly_buyer

import (
	"encoding/json"
	"time"
)

// GetAnalyticItemResponseItems struct for GetAnalyticItemResponseItems
type GetAnalyticItemResponseItems struct {
	SaleId string `json:"saleId"`
	Platform string `json:"platform"`
	PlatformOrderId NullableString `json:"platformOrderId,omitempty"`
	ItemTitle NullableString `json:"itemTitle,omitempty"`
	ItemBrand NullableString `json:"itemBrand,omitempty"`
	ItemSku NullableString `json:"itemSku,omitempty"`
	SalePrice NullableFloat32 `json:"salePrice,omitempty"`
	PlatformFee NullableFloat32 `json:"platformFee,omitempty"`
	ShippingCost NullableFloat32 `json:"shippingCost,omitempty"`
	CostOfGoods NullableFloat32 `json:"costOfGoods,omitempty"`
	NetProfit NullableFloat32 `json:"netProfit,omitempty"`
	MarginPct float32 `json:"marginPct"`
	DaysToSell NullableFloat32 `json:"daysToSell,omitempty"`
	DetectedAt time.Time `json:"detectedAt"`
}

// NewGetAnalyticItemResponseItems instantiates a new GetAnalyticItemResponseItems object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAnalyticItemResponseItems(saleId string, platform string, marginPct float32, detectedAt time.Time) *GetAnalyticItemResponseItems {
	this := GetAnalyticItemResponseItems{}
	this.SaleId = saleId
	this.Platform = platform
	this.MarginPct = marginPct
	this.DetectedAt = detectedAt
	return &this
}

// NewGetAnalyticItemResponseItemsWithDefaults instantiates a new GetAnalyticItemResponseItems object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAnalyticItemResponseItemsWithDefaults() *GetAnalyticItemResponseItems {
	this := GetAnalyticItemResponseItems{}
	return &this
}

// GetSaleId returns the SaleId field value
func (o *GetAnalyticItemResponseItems) GetSaleId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SaleId
}

// GetSaleIdOk returns a tuple with the SaleId field value
// and a boolean to check if the value has been set.
func (o *GetAnalyticItemResponseItems) GetSaleIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.SaleId, true
}

// SetSaleId sets field value
func (o *GetAnalyticItemResponseItems) SetSaleId(v string) {
	o.SaleId = v
}

// GetPlatform returns the Platform field value
func (o *GetAnalyticItemResponseItems) GetPlatform() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Platform
}

// GetPlatformOk returns a tuple with the Platform field value
// and a boolean to check if the value has been set.
func (o *GetAnalyticItemResponseItems) GetPlatformOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Platform, true
}

// SetPlatform sets field value
func (o *GetAnalyticItemResponseItems) SetPlatform(v string) {
	o.Platform = v
}

// GetPlatformOrderId returns the PlatformOrderId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetAnalyticItemResponseItems) GetPlatformOrderId() string {
	if o == nil || o.PlatformOrderId.Get() == nil {
		var ret string
		return ret
	}
	return *o.PlatformOrderId.Get()
}

// GetPlatformOrderIdOk returns a tuple with the PlatformOrderId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetAnalyticItemResponseItems) GetPlatformOrderIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.PlatformOrderId.Get(), o.PlatformOrderId.IsSet()
}

// HasPlatformOrderId returns a boolean if a field has been set.
func (o *GetAnalyticItemResponseItems) HasPlatformOrderId() bool {
	if o != nil && o.PlatformOrderId.IsSet() {
		return true
	}

	return false
}

// SetPlatformOrderId gets a reference to the given NullableString and assigns it to the PlatformOrderId field.
func (o *GetAnalyticItemResponseItems) SetPlatformOrderId(v string) {
	o.PlatformOrderId.Set(&v)
}
// SetPlatformOrderIdNil sets the value for PlatformOrderId to be an explicit nil
func (o *GetAnalyticItemResponseItems) SetPlatformOrderIdNil() {
	o.PlatformOrderId.Set(nil)
}

// UnsetPlatformOrderId ensures that no value is present for PlatformOrderId, not even an explicit nil
func (o *GetAnalyticItemResponseItems) UnsetPlatformOrderId() {
	o.PlatformOrderId.Unset()
}

// GetItemTitle returns the ItemTitle field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetAnalyticItemResponseItems) GetItemTitle() string {
	if o == nil || o.ItemTitle.Get() == nil {
		var ret string
		return ret
	}
	return *o.ItemTitle.Get()
}

// GetItemTitleOk returns a tuple with the ItemTitle field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetAnalyticItemResponseItems) GetItemTitleOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.ItemTitle.Get(), o.ItemTitle.IsSet()
}

// HasItemTitle returns a boolean if a field has been set.
func (o *GetAnalyticItemResponseItems) HasItemTitle() bool {
	if o != nil && o.ItemTitle.IsSet() {
		return true
	}

	return false
}

// SetItemTitle gets a reference to the given NullableString and assigns it to the ItemTitle field.
func (o *GetAnalyticItemResponseItems) SetItemTitle(v string) {
	o.ItemTitle.Set(&v)
}
// SetItemTitleNil sets the value for ItemTitle to be an explicit nil
func (o *GetAnalyticItemResponseItems) SetItemTitleNil() {
	o.ItemTitle.Set(nil)
}

// UnsetItemTitle ensures that no value is present for ItemTitle, not even an explicit nil
func (o *GetAnalyticItemResponseItems) UnsetItemTitle() {
	o.ItemTitle.Unset()
}

// GetItemBrand returns the ItemBrand field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetAnalyticItemResponseItems) GetItemBrand() string {
	if o == nil || o.ItemBrand.Get() == nil {
		var ret string
		return ret
	}
	return *o.ItemBrand.Get()
}

// GetItemBrandOk returns a tuple with the ItemBrand field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetAnalyticItemResponseItems) GetItemBrandOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.ItemBrand.Get(), o.ItemBrand.IsSet()
}

// HasItemBrand returns a boolean if a field has been set.
func (o *GetAnalyticItemResponseItems) HasItemBrand() bool {
	if o != nil && o.ItemBrand.IsSet() {
		return true
	}

	return false
}

// SetItemBrand gets a reference to the given NullableString and assigns it to the ItemBrand field.
func (o *GetAnalyticItemResponseItems) SetItemBrand(v string) {
	o.ItemBrand.Set(&v)
}
// SetItemBrandNil sets the value for ItemBrand to be an explicit nil
func (o *GetAnalyticItemResponseItems) SetItemBrandNil() {
	o.ItemBrand.Set(nil)
}

// UnsetItemBrand ensures that no value is present for ItemBrand, not even an explicit nil
func (o *GetAnalyticItemResponseItems) UnsetItemBrand() {
	o.ItemBrand.Unset()
}

// GetItemSku returns the ItemSku field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetAnalyticItemResponseItems) GetItemSku() string {
	if o == nil || o.ItemSku.Get() == nil {
		var ret string
		return ret
	}
	return *o.ItemSku.Get()
}

// GetItemSkuOk returns a tuple with the ItemSku field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetAnalyticItemResponseItems) GetItemSkuOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.ItemSku.Get(), o.ItemSku.IsSet()
}

// HasItemSku returns a boolean if a field has been set.
func (o *GetAnalyticItemResponseItems) HasItemSku() bool {
	if o != nil && o.ItemSku.IsSet() {
		return true
	}

	return false
}

// SetItemSku gets a reference to the given NullableString and assigns it to the ItemSku field.
func (o *GetAnalyticItemResponseItems) SetItemSku(v string) {
	o.ItemSku.Set(&v)
}
// SetItemSkuNil sets the value for ItemSku to be an explicit nil
func (o *GetAnalyticItemResponseItems) SetItemSkuNil() {
	o.ItemSku.Set(nil)
}

// UnsetItemSku ensures that no value is present for ItemSku, not even an explicit nil
func (o *GetAnalyticItemResponseItems) UnsetItemSku() {
	o.ItemSku.Unset()
}

// GetSalePrice returns the SalePrice field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetAnalyticItemResponseItems) GetSalePrice() float32 {
	if o == nil || o.SalePrice.Get() == nil {
		var ret float32
		return ret
	}
	return *o.SalePrice.Get()
}

// GetSalePriceOk returns a tuple with the SalePrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetAnalyticItemResponseItems) GetSalePriceOk() (*float32, bool) {
	if o == nil  {
		return nil, false
	}
	return o.SalePrice.Get(), o.SalePrice.IsSet()
}

// HasSalePrice returns a boolean if a field has been set.
func (o *GetAnalyticItemResponseItems) HasSalePrice() bool {
	if o != nil && o.SalePrice.IsSet() {
		return true
	}

	return false
}

// SetSalePrice gets a reference to the given NullableFloat32 and assigns it to the SalePrice field.
func (o *GetAnalyticItemResponseItems) SetSalePrice(v float32) {
	o.SalePrice.Set(&v)
}
// SetSalePriceNil sets the value for SalePrice to be an explicit nil
func (o *GetAnalyticItemResponseItems) SetSalePriceNil() {
	o.SalePrice.Set(nil)
}

// UnsetSalePrice ensures that no value is present for SalePrice, not even an explicit nil
func (o *GetAnalyticItemResponseItems) UnsetSalePrice() {
	o.SalePrice.Unset()
}

// GetPlatformFee returns the PlatformFee field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetAnalyticItemResponseItems) GetPlatformFee() float32 {
	if o == nil || o.PlatformFee.Get() == nil {
		var ret float32
		return ret
	}
	return *o.PlatformFee.Get()
}

// GetPlatformFeeOk returns a tuple with the PlatformFee field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetAnalyticItemResponseItems) GetPlatformFeeOk() (*float32, bool) {
	if o == nil  {
		return nil, false
	}
	return o.PlatformFee.Get(), o.PlatformFee.IsSet()
}

// HasPlatformFee returns a boolean if a field has been set.
func (o *GetAnalyticItemResponseItems) HasPlatformFee() bool {
	if o != nil && o.PlatformFee.IsSet() {
		return true
	}

	return false
}

// SetPlatformFee gets a reference to the given NullableFloat32 and assigns it to the PlatformFee field.
func (o *GetAnalyticItemResponseItems) SetPlatformFee(v float32) {
	o.PlatformFee.Set(&v)
}
// SetPlatformFeeNil sets the value for PlatformFee to be an explicit nil
func (o *GetAnalyticItemResponseItems) SetPlatformFeeNil() {
	o.PlatformFee.Set(nil)
}

// UnsetPlatformFee ensures that no value is present for PlatformFee, not even an explicit nil
func (o *GetAnalyticItemResponseItems) UnsetPlatformFee() {
	o.PlatformFee.Unset()
}

// GetShippingCost returns the ShippingCost field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetAnalyticItemResponseItems) GetShippingCost() float32 {
	if o == nil || o.ShippingCost.Get() == nil {
		var ret float32
		return ret
	}
	return *o.ShippingCost.Get()
}

// GetShippingCostOk returns a tuple with the ShippingCost field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetAnalyticItemResponseItems) GetShippingCostOk() (*float32, bool) {
	if o == nil  {
		return nil, false
	}
	return o.ShippingCost.Get(), o.ShippingCost.IsSet()
}

// HasShippingCost returns a boolean if a field has been set.
func (o *GetAnalyticItemResponseItems) HasShippingCost() bool {
	if o != nil && o.ShippingCost.IsSet() {
		return true
	}

	return false
}

// SetShippingCost gets a reference to the given NullableFloat32 and assigns it to the ShippingCost field.
func (o *GetAnalyticItemResponseItems) SetShippingCost(v float32) {
	o.ShippingCost.Set(&v)
}
// SetShippingCostNil sets the value for ShippingCost to be an explicit nil
func (o *GetAnalyticItemResponseItems) SetShippingCostNil() {
	o.ShippingCost.Set(nil)
}

// UnsetShippingCost ensures that no value is present for ShippingCost, not even an explicit nil
func (o *GetAnalyticItemResponseItems) UnsetShippingCost() {
	o.ShippingCost.Unset()
}

// GetCostOfGoods returns the CostOfGoods field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetAnalyticItemResponseItems) GetCostOfGoods() float32 {
	if o == nil || o.CostOfGoods.Get() == nil {
		var ret float32
		return ret
	}
	return *o.CostOfGoods.Get()
}

// GetCostOfGoodsOk returns a tuple with the CostOfGoods field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetAnalyticItemResponseItems) GetCostOfGoodsOk() (*float32, bool) {
	if o == nil  {
		return nil, false
	}
	return o.CostOfGoods.Get(), o.CostOfGoods.IsSet()
}

// HasCostOfGoods returns a boolean if a field has been set.
func (o *GetAnalyticItemResponseItems) HasCostOfGoods() bool {
	if o != nil && o.CostOfGoods.IsSet() {
		return true
	}

	return false
}

// SetCostOfGoods gets a reference to the given NullableFloat32 and assigns it to the CostOfGoods field.
func (o *GetAnalyticItemResponseItems) SetCostOfGoods(v float32) {
	o.CostOfGoods.Set(&v)
}
// SetCostOfGoodsNil sets the value for CostOfGoods to be an explicit nil
func (o *GetAnalyticItemResponseItems) SetCostOfGoodsNil() {
	o.CostOfGoods.Set(nil)
}

// UnsetCostOfGoods ensures that no value is present for CostOfGoods, not even an explicit nil
func (o *GetAnalyticItemResponseItems) UnsetCostOfGoods() {
	o.CostOfGoods.Unset()
}

// GetNetProfit returns the NetProfit field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetAnalyticItemResponseItems) GetNetProfit() float32 {
	if o == nil || o.NetProfit.Get() == nil {
		var ret float32
		return ret
	}
	return *o.NetProfit.Get()
}

// GetNetProfitOk returns a tuple with the NetProfit field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetAnalyticItemResponseItems) GetNetProfitOk() (*float32, bool) {
	if o == nil  {
		return nil, false
	}
	return o.NetProfit.Get(), o.NetProfit.IsSet()
}

// HasNetProfit returns a boolean if a field has been set.
func (o *GetAnalyticItemResponseItems) HasNetProfit() bool {
	if o != nil && o.NetProfit.IsSet() {
		return true
	}

	return false
}

// SetNetProfit gets a reference to the given NullableFloat32 and assigns it to the NetProfit field.
func (o *GetAnalyticItemResponseItems) SetNetProfit(v float32) {
	o.NetProfit.Set(&v)
}
// SetNetProfitNil sets the value for NetProfit to be an explicit nil
func (o *GetAnalyticItemResponseItems) SetNetProfitNil() {
	o.NetProfit.Set(nil)
}

// UnsetNetProfit ensures that no value is present for NetProfit, not even an explicit nil
func (o *GetAnalyticItemResponseItems) UnsetNetProfit() {
	o.NetProfit.Unset()
}

// GetMarginPct returns the MarginPct field value
func (o *GetAnalyticItemResponseItems) GetMarginPct() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.MarginPct
}

// GetMarginPctOk returns a tuple with the MarginPct field value
// and a boolean to check if the value has been set.
func (o *GetAnalyticItemResponseItems) GetMarginPctOk() (*float32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.MarginPct, true
}

// SetMarginPct sets field value
func (o *GetAnalyticItemResponseItems) SetMarginPct(v float32) {
	o.MarginPct = v
}

// GetDaysToSell returns the DaysToSell field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetAnalyticItemResponseItems) GetDaysToSell() float32 {
	if o == nil || o.DaysToSell.Get() == nil {
		var ret float32
		return ret
	}
	return *o.DaysToSell.Get()
}

// GetDaysToSellOk returns a tuple with the DaysToSell field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetAnalyticItemResponseItems) GetDaysToSellOk() (*float32, bool) {
	if o == nil  {
		return nil, false
	}
	return o.DaysToSell.Get(), o.DaysToSell.IsSet()
}

// HasDaysToSell returns a boolean if a field has been set.
func (o *GetAnalyticItemResponseItems) HasDaysToSell() bool {
	if o != nil && o.DaysToSell.IsSet() {
		return true
	}

	return false
}

// SetDaysToSell gets a reference to the given NullableFloat32 and assigns it to the DaysToSell field.
func (o *GetAnalyticItemResponseItems) SetDaysToSell(v float32) {
	o.DaysToSell.Set(&v)
}
// SetDaysToSellNil sets the value for DaysToSell to be an explicit nil
func (o *GetAnalyticItemResponseItems) SetDaysToSellNil() {
	o.DaysToSell.Set(nil)
}

// UnsetDaysToSell ensures that no value is present for DaysToSell, not even an explicit nil
func (o *GetAnalyticItemResponseItems) UnsetDaysToSell() {
	o.DaysToSell.Unset()
}

// GetDetectedAt returns the DetectedAt field value
func (o *GetAnalyticItemResponseItems) GetDetectedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.DetectedAt
}

// GetDetectedAtOk returns a tuple with the DetectedAt field value
// and a boolean to check if the value has been set.
func (o *GetAnalyticItemResponseItems) GetDetectedAtOk() (*time.Time, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.DetectedAt, true
}

// SetDetectedAt sets field value
func (o *GetAnalyticItemResponseItems) SetDetectedAt(v time.Time) {
	o.DetectedAt = v
}

func (o GetAnalyticItemResponseItems) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["saleId"] = o.SaleId
	}
	if true {
		toSerialize["platform"] = o.Platform
	}
	if o.PlatformOrderId.IsSet() {
		toSerialize["platformOrderId"] = o.PlatformOrderId.Get()
	}
	if o.ItemTitle.IsSet() {
		toSerialize["itemTitle"] = o.ItemTitle.Get()
	}
	if o.ItemBrand.IsSet() {
		toSerialize["itemBrand"] = o.ItemBrand.Get()
	}
	if o.ItemSku.IsSet() {
		toSerialize["itemSku"] = o.ItemSku.Get()
	}
	if o.SalePrice.IsSet() {
		toSerialize["salePrice"] = o.SalePrice.Get()
	}
	if o.PlatformFee.IsSet() {
		toSerialize["platformFee"] = o.PlatformFee.Get()
	}
	if o.ShippingCost.IsSet() {
		toSerialize["shippingCost"] = o.ShippingCost.Get()
	}
	if o.CostOfGoods.IsSet() {
		toSerialize["costOfGoods"] = o.CostOfGoods.Get()
	}
	if o.NetProfit.IsSet() {
		toSerialize["netProfit"] = o.NetProfit.Get()
	}
	if true {
		toSerialize["marginPct"] = o.MarginPct
	}
	if o.DaysToSell.IsSet() {
		toSerialize["daysToSell"] = o.DaysToSell.Get()
	}
	if true {
		toSerialize["detectedAt"] = o.DetectedAt
	}
	return json.Marshal(toSerialize)
}

type NullableGetAnalyticItemResponseItems struct {
	value *GetAnalyticItemResponseItems
	isSet bool
}

func (v NullableGetAnalyticItemResponseItems) Get() *GetAnalyticItemResponseItems {
	return v.value
}

func (v *NullableGetAnalyticItemResponseItems) Set(val *GetAnalyticItemResponseItems) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAnalyticItemResponseItems) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAnalyticItemResponseItems) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAnalyticItemResponseItems(val *GetAnalyticItemResponseItems) *NullableGetAnalyticItemResponseItems {
	return &NullableGetAnalyticItemResponseItems{value: val, isSet: true}
}

func (v NullableGetAnalyticItemResponseItems) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAnalyticItemResponseItems) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


