/*
Crossly Buyer API

The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crossly_buyer

import (
	"encoding/json"
)

// CreateAutomationRuleValidateRecipeResponseDetails struct for CreateAutomationRuleValidateRecipeResponseDetails
type CreateAutomationRuleValidateRecipeResponseDetails struct {
	FormErrors []string `json:"formErrors"`
	FieldErrors CreateAutomationRuleValidateRecipeResponseDetailsFieldErrors `json:"fieldErrors"`
}

// NewCreateAutomationRuleValidateRecipeResponseDetails instantiates a new CreateAutomationRuleValidateRecipeResponseDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateAutomationRuleValidateRecipeResponseDetails(formErrors []string, fieldErrors CreateAutomationRuleValidateRecipeResponseDetailsFieldErrors) *CreateAutomationRuleValidateRecipeResponseDetails {
	this := CreateAutomationRuleValidateRecipeResponseDetails{}
	this.FormErrors = formErrors
	this.FieldErrors = fieldErrors
	return &this
}

// NewCreateAutomationRuleValidateRecipeResponseDetailsWithDefaults instantiates a new CreateAutomationRuleValidateRecipeResponseDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateAutomationRuleValidateRecipeResponseDetailsWithDefaults() *CreateAutomationRuleValidateRecipeResponseDetails {
	this := CreateAutomationRuleValidateRecipeResponseDetails{}
	return &this
}

// GetFormErrors returns the FormErrors field value
func (o *CreateAutomationRuleValidateRecipeResponseDetails) GetFormErrors() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.FormErrors
}

// GetFormErrorsOk returns a tuple with the FormErrors field value
// and a boolean to check if the value has been set.
func (o *CreateAutomationRuleValidateRecipeResponseDetails) GetFormErrorsOk() ([]string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.FormErrors, true
}

// SetFormErrors sets field value
func (o *CreateAutomationRuleValidateRecipeResponseDetails) SetFormErrors(v []string) {
	o.FormErrors = v
}

// GetFieldErrors returns the FieldErrors field value
func (o *CreateAutomationRuleValidateRecipeResponseDetails) GetFieldErrors() CreateAutomationRuleValidateRecipeResponseDetailsFieldErrors {
	if o == nil {
		var ret CreateAutomationRuleValidateRecipeResponseDetailsFieldErrors
		return ret
	}

	return o.FieldErrors
}

// GetFieldErrorsOk returns a tuple with the FieldErrors field value
// and a boolean to check if the value has been set.
func (o *CreateAutomationRuleValidateRecipeResponseDetails) GetFieldErrorsOk() (*CreateAutomationRuleValidateRecipeResponseDetailsFieldErrors, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.FieldErrors, true
}

// SetFieldErrors sets field value
func (o *CreateAutomationRuleValidateRecipeResponseDetails) SetFieldErrors(v CreateAutomationRuleValidateRecipeResponseDetailsFieldErrors) {
	o.FieldErrors = v
}

func (o CreateAutomationRuleValidateRecipeResponseDetails) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["formErrors"] = o.FormErrors
	}
	if true {
		toSerialize["fieldErrors"] = o.FieldErrors
	}
	return json.Marshal(toSerialize)
}

type NullableCreateAutomationRuleValidateRecipeResponseDetails struct {
	value *CreateAutomationRuleValidateRecipeResponseDetails
	isSet bool
}

func (v NullableCreateAutomationRuleValidateRecipeResponseDetails) Get() *CreateAutomationRuleValidateRecipeResponseDetails {
	return v.value
}

func (v *NullableCreateAutomationRuleValidateRecipeResponseDetails) Set(val *CreateAutomationRuleValidateRecipeResponseDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateAutomationRuleValidateRecipeResponseDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateAutomationRuleValidateRecipeResponseDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateAutomationRuleValidateRecipeResponseDetails(val *CreateAutomationRuleValidateRecipeResponseDetails) *NullableCreateAutomationRuleValidateRecipeResponseDetails {
	return &NullableCreateAutomationRuleValidateRecipeResponseDetails{value: val, isSet: true}
}

func (v NullableCreateAutomationRuleValidateRecipeResponseDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateAutomationRuleValidateRecipeResponseDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


