/*
Crossly Buyer API

The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crossly_buyer

import (
	"encoding/json"
)

// GetSpatialPublicResponseStats Only the count. `capitalCents` is the seller's spend and never leaves.
type GetSpatialPublicResponseStats struct {
	ItemCount float32 `json:"itemCount"`
}

// NewGetSpatialPublicResponseStats instantiates a new GetSpatialPublicResponseStats object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetSpatialPublicResponseStats(itemCount float32) *GetSpatialPublicResponseStats {
	this := GetSpatialPublicResponseStats{}
	this.ItemCount = itemCount
	return &this
}

// NewGetSpatialPublicResponseStatsWithDefaults instantiates a new GetSpatialPublicResponseStats object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetSpatialPublicResponseStatsWithDefaults() *GetSpatialPublicResponseStats {
	this := GetSpatialPublicResponseStats{}
	return &this
}

// GetItemCount returns the ItemCount field value
func (o *GetSpatialPublicResponseStats) GetItemCount() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.ItemCount
}

// GetItemCountOk returns a tuple with the ItemCount field value
// and a boolean to check if the value has been set.
func (o *GetSpatialPublicResponseStats) GetItemCountOk() (*float32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ItemCount, true
}

// SetItemCount sets field value
func (o *GetSpatialPublicResponseStats) SetItemCount(v float32) {
	o.ItemCount = v
}

func (o GetSpatialPublicResponseStats) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["itemCount"] = o.ItemCount
	}
	return json.Marshal(toSerialize)
}

type NullableGetSpatialPublicResponseStats struct {
	value *GetSpatialPublicResponseStats
	isSet bool
}

func (v NullableGetSpatialPublicResponseStats) Get() *GetSpatialPublicResponseStats {
	return v.value
}

func (v *NullableGetSpatialPublicResponseStats) Set(val *GetSpatialPublicResponseStats) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSpatialPublicResponseStats) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSpatialPublicResponseStats) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSpatialPublicResponseStats(val *GetSpatialPublicResponseStats) *NullableGetSpatialPublicResponseStats {
	return &NullableGetSpatialPublicResponseStats{value: val, isSet: true}
}

func (v NullableGetSpatialPublicResponseStats) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSpatialPublicResponseStats) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


