/*
Crossly Buyer API

The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crossly_buyer

import (
	"encoding/json"
)

// UpdateListingResponse struct for UpdateListingResponse
type UpdateListingResponse struct {
	Jobs []CreateListingResponseJobs `json:"jobs"`
}

// NewUpdateListingResponse instantiates a new UpdateListingResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateListingResponse(jobs []CreateListingResponseJobs) *UpdateListingResponse {
	this := UpdateListingResponse{}
	this.Jobs = jobs
	return &this
}

// NewUpdateListingResponseWithDefaults instantiates a new UpdateListingResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateListingResponseWithDefaults() *UpdateListingResponse {
	this := UpdateListingResponse{}
	return &this
}

// GetJobs returns the Jobs field value
func (o *UpdateListingResponse) GetJobs() []CreateListingResponseJobs {
	if o == nil {
		var ret []CreateListingResponseJobs
		return ret
	}

	return o.Jobs
}

// GetJobsOk returns a tuple with the Jobs field value
// and a boolean to check if the value has been set.
func (o *UpdateListingResponse) GetJobsOk() ([]CreateListingResponseJobs, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Jobs, true
}

// SetJobs sets field value
func (o *UpdateListingResponse) SetJobs(v []CreateListingResponseJobs) {
	o.Jobs = v
}

func (o UpdateListingResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["jobs"] = o.Jobs
	}
	return json.Marshal(toSerialize)
}

type NullableUpdateListingResponse struct {
	value *UpdateListingResponse
	isSet bool
}

func (v NullableUpdateListingResponse) Get() *UpdateListingResponse {
	return v.value
}

func (v *NullableUpdateListingResponse) Set(val *UpdateListingResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateListingResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateListingResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateListingResponse(val *UpdateListingResponse) *NullableUpdateListingResponse {
	return &NullableUpdateListingResponse{value: val, isSet: true}
}

func (v NullableUpdateListingResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateListingResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


