/*
Crossly Buyer API

The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crossly_buyer

import (
	"encoding/json"
)

// UpdateNotificationIntegrationResponse struct for UpdateNotificationIntegrationResponse
type UpdateNotificationIntegrationResponse struct {
	Ok bool `json:"ok"`
}

// NewUpdateNotificationIntegrationResponse instantiates a new UpdateNotificationIntegrationResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateNotificationIntegrationResponse(ok bool) *UpdateNotificationIntegrationResponse {
	this := UpdateNotificationIntegrationResponse{}
	this.Ok = ok
	return &this
}

// NewUpdateNotificationIntegrationResponseWithDefaults instantiates a new UpdateNotificationIntegrationResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateNotificationIntegrationResponseWithDefaults() *UpdateNotificationIntegrationResponse {
	this := UpdateNotificationIntegrationResponse{}
	return &this
}

// GetOk returns the Ok field value
func (o *UpdateNotificationIntegrationResponse) GetOk() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Ok
}

// GetOkOk returns a tuple with the Ok field value
// and a boolean to check if the value has been set.
func (o *UpdateNotificationIntegrationResponse) GetOkOk() (*bool, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Ok, true
}

// SetOk sets field value
func (o *UpdateNotificationIntegrationResponse) SetOk(v bool) {
	o.Ok = v
}

func (o UpdateNotificationIntegrationResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["ok"] = o.Ok
	}
	return json.Marshal(toSerialize)
}

type NullableUpdateNotificationIntegrationResponse struct {
	value *UpdateNotificationIntegrationResponse
	isSet bool
}

func (v NullableUpdateNotificationIntegrationResponse) Get() *UpdateNotificationIntegrationResponse {
	return v.value
}

func (v *NullableUpdateNotificationIntegrationResponse) Set(val *UpdateNotificationIntegrationResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateNotificationIntegrationResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateNotificationIntegrationResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateNotificationIntegrationResponse(val *UpdateNotificationIntegrationResponse) *NullableUpdateNotificationIntegrationResponse {
	return &NullableUpdateNotificationIntegrationResponse{value: val, isSet: true}
}

func (v NullableUpdateNotificationIntegrationResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateNotificationIntegrationResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


