/*
Crossly Buyer API

The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crossly_buyer

import (
	"encoding/json"
)

// ListVariationGroupsItem struct for ListVariationGroupsItem
type ListVariationGroupsItem struct {
	Members []ListVariationGroupsItemMembers `json:"members"`
	Rollup ListVariationGroupsItemRollup `json:"rollup"`
	Id string `json:"id"`
	Title NullableString `json:"title,omitempty"`
}

// NewListVariationGroupsItem instantiates a new ListVariationGroupsItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListVariationGroupsItem(members []ListVariationGroupsItemMembers, rollup ListVariationGroupsItemRollup, id string) *ListVariationGroupsItem {
	this := ListVariationGroupsItem{}
	this.Members = members
	this.Rollup = rollup
	this.Id = id
	return &this
}

// NewListVariationGroupsItemWithDefaults instantiates a new ListVariationGroupsItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListVariationGroupsItemWithDefaults() *ListVariationGroupsItem {
	this := ListVariationGroupsItem{}
	return &this
}

// GetMembers returns the Members field value
func (o *ListVariationGroupsItem) GetMembers() []ListVariationGroupsItemMembers {
	if o == nil {
		var ret []ListVariationGroupsItemMembers
		return ret
	}

	return o.Members
}

// GetMembersOk returns a tuple with the Members field value
// and a boolean to check if the value has been set.
func (o *ListVariationGroupsItem) GetMembersOk() ([]ListVariationGroupsItemMembers, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Members, true
}

// SetMembers sets field value
func (o *ListVariationGroupsItem) SetMembers(v []ListVariationGroupsItemMembers) {
	o.Members = v
}

// GetRollup returns the Rollup field value
func (o *ListVariationGroupsItem) GetRollup() ListVariationGroupsItemRollup {
	if o == nil {
		var ret ListVariationGroupsItemRollup
		return ret
	}

	return o.Rollup
}

// GetRollupOk returns a tuple with the Rollup field value
// and a boolean to check if the value has been set.
func (o *ListVariationGroupsItem) GetRollupOk() (*ListVariationGroupsItemRollup, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Rollup, true
}

// SetRollup sets field value
func (o *ListVariationGroupsItem) SetRollup(v ListVariationGroupsItemRollup) {
	o.Rollup = v
}

// GetId returns the Id field value
func (o *ListVariationGroupsItem) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ListVariationGroupsItem) GetIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ListVariationGroupsItem) SetId(v string) {
	o.Id = v
}

// GetTitle returns the Title field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListVariationGroupsItem) GetTitle() string {
	if o == nil || o.Title.Get() == nil {
		var ret string
		return ret
	}
	return *o.Title.Get()
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListVariationGroupsItem) GetTitleOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Title.Get(), o.Title.IsSet()
}

// HasTitle returns a boolean if a field has been set.
func (o *ListVariationGroupsItem) HasTitle() bool {
	if o != nil && o.Title.IsSet() {
		return true
	}

	return false
}

// SetTitle gets a reference to the given NullableString and assigns it to the Title field.
func (o *ListVariationGroupsItem) SetTitle(v string) {
	o.Title.Set(&v)
}
// SetTitleNil sets the value for Title to be an explicit nil
func (o *ListVariationGroupsItem) SetTitleNil() {
	o.Title.Set(nil)
}

// UnsetTitle ensures that no value is present for Title, not even an explicit nil
func (o *ListVariationGroupsItem) UnsetTitle() {
	o.Title.Unset()
}

func (o ListVariationGroupsItem) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["members"] = o.Members
	}
	if true {
		toSerialize["rollup"] = o.Rollup
	}
	if true {
		toSerialize["id"] = o.Id
	}
	if o.Title.IsSet() {
		toSerialize["title"] = o.Title.Get()
	}
	return json.Marshal(toSerialize)
}

type NullableListVariationGroupsItem struct {
	value *ListVariationGroupsItem
	isSet bool
}

func (v NullableListVariationGroupsItem) Get() *ListVariationGroupsItem {
	return v.value
}

func (v *NullableListVariationGroupsItem) Set(val *ListVariationGroupsItem) {
	v.value = val
	v.isSet = true
}

func (v NullableListVariationGroupsItem) IsSet() bool {
	return v.isSet
}

func (v *NullableListVariationGroupsItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListVariationGroupsItem(val *ListVariationGroupsItem) *NullableListVariationGroupsItem {
	return &NullableListVariationGroupsItem{value: val, isSet: true}
}

func (v NullableListVariationGroupsItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListVariationGroupsItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


