/*
Crossly Buyer API

The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crossly_buyer

import (
	"encoding/json"
)

// GetBuyerCatalogListingResponse struct for GetBuyerCatalogListingResponse
type GetBuyerCatalogListingResponse struct {
	Slug string `json:"slug"`
	Title string `json:"title"`
	Description NullableString `json:"description,omitempty"`
	PriceCents float32 `json:"priceCents"`
	CompareAtCents NullableFloat32 `json:"compareAtCents,omitempty"`
	Currency string `json:"currency"`
	Status string `json:"status"`
	Available bool `json:"available"`
	QuantityAvailable float32 `json:"quantityAvailable"`
	Condition NullableString `json:"condition,omitempty"`
	Brand NullableString `json:"brand,omitempty"`
	Size NullableString `json:"size,omitempty"`
	Color []string `json:"color,omitempty"`
	CategoryMain NullableString `json:"categoryMain,omitempty"`
	CategorySub NullableString `json:"categorySub,omitempty"`
	Images []string `json:"images"`
	SellerUsername NullableString `json:"sellerUsername,omitempty"`
	SellerDisplayName NullableString `json:"sellerDisplayName,omitempty"`
	ListedAt NullableString `json:"listedAt,omitempty"`
}

// NewGetBuyerCatalogListingResponse instantiates a new GetBuyerCatalogListingResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetBuyerCatalogListingResponse(slug string, title string, priceCents float32, currency string, status string, available bool, quantityAvailable float32, images []string) *GetBuyerCatalogListingResponse {
	this := GetBuyerCatalogListingResponse{}
	this.Slug = slug
	this.Title = title
	this.PriceCents = priceCents
	this.Currency = currency
	this.Status = status
	this.Available = available
	this.QuantityAvailable = quantityAvailable
	this.Images = images
	return &this
}

// NewGetBuyerCatalogListingResponseWithDefaults instantiates a new GetBuyerCatalogListingResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetBuyerCatalogListingResponseWithDefaults() *GetBuyerCatalogListingResponse {
	this := GetBuyerCatalogListingResponse{}
	return &this
}

// GetSlug returns the Slug field value
func (o *GetBuyerCatalogListingResponse) GetSlug() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Slug
}

// GetSlugOk returns a tuple with the Slug field value
// and a boolean to check if the value has been set.
func (o *GetBuyerCatalogListingResponse) GetSlugOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Slug, true
}

// SetSlug sets field value
func (o *GetBuyerCatalogListingResponse) SetSlug(v string) {
	o.Slug = v
}

// GetTitle returns the Title field value
func (o *GetBuyerCatalogListingResponse) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *GetBuyerCatalogListingResponse) GetTitleOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *GetBuyerCatalogListingResponse) SetTitle(v string) {
	o.Title = v
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetBuyerCatalogListingResponse) GetDescription() string {
	if o == nil || o.Description.Get() == nil {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetBuyerCatalogListingResponse) GetDescriptionOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *GetBuyerCatalogListingResponse) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *GetBuyerCatalogListingResponse) SetDescription(v string) {
	o.Description.Set(&v)
}
// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *GetBuyerCatalogListingResponse) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *GetBuyerCatalogListingResponse) UnsetDescription() {
	o.Description.Unset()
}

// GetPriceCents returns the PriceCents field value
func (o *GetBuyerCatalogListingResponse) GetPriceCents() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.PriceCents
}

// GetPriceCentsOk returns a tuple with the PriceCents field value
// and a boolean to check if the value has been set.
func (o *GetBuyerCatalogListingResponse) GetPriceCentsOk() (*float32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.PriceCents, true
}

// SetPriceCents sets field value
func (o *GetBuyerCatalogListingResponse) SetPriceCents(v float32) {
	o.PriceCents = v
}

// GetCompareAtCents returns the CompareAtCents field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetBuyerCatalogListingResponse) GetCompareAtCents() float32 {
	if o == nil || o.CompareAtCents.Get() == nil {
		var ret float32
		return ret
	}
	return *o.CompareAtCents.Get()
}

// GetCompareAtCentsOk returns a tuple with the CompareAtCents field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetBuyerCatalogListingResponse) GetCompareAtCentsOk() (*float32, bool) {
	if o == nil  {
		return nil, false
	}
	return o.CompareAtCents.Get(), o.CompareAtCents.IsSet()
}

// HasCompareAtCents returns a boolean if a field has been set.
func (o *GetBuyerCatalogListingResponse) HasCompareAtCents() bool {
	if o != nil && o.CompareAtCents.IsSet() {
		return true
	}

	return false
}

// SetCompareAtCents gets a reference to the given NullableFloat32 and assigns it to the CompareAtCents field.
func (o *GetBuyerCatalogListingResponse) SetCompareAtCents(v float32) {
	o.CompareAtCents.Set(&v)
}
// SetCompareAtCentsNil sets the value for CompareAtCents to be an explicit nil
func (o *GetBuyerCatalogListingResponse) SetCompareAtCentsNil() {
	o.CompareAtCents.Set(nil)
}

// UnsetCompareAtCents ensures that no value is present for CompareAtCents, not even an explicit nil
func (o *GetBuyerCatalogListingResponse) UnsetCompareAtCents() {
	o.CompareAtCents.Unset()
}

// GetCurrency returns the Currency field value
func (o *GetBuyerCatalogListingResponse) GetCurrency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value
// and a boolean to check if the value has been set.
func (o *GetBuyerCatalogListingResponse) GetCurrencyOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Currency, true
}

// SetCurrency sets field value
func (o *GetBuyerCatalogListingResponse) SetCurrency(v string) {
	o.Currency = v
}

// GetStatus returns the Status field value
func (o *GetBuyerCatalogListingResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *GetBuyerCatalogListingResponse) GetStatusOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *GetBuyerCatalogListingResponse) SetStatus(v string) {
	o.Status = v
}

// GetAvailable returns the Available field value
func (o *GetBuyerCatalogListingResponse) GetAvailable() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Available
}

// GetAvailableOk returns a tuple with the Available field value
// and a boolean to check if the value has been set.
func (o *GetBuyerCatalogListingResponse) GetAvailableOk() (*bool, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Available, true
}

// SetAvailable sets field value
func (o *GetBuyerCatalogListingResponse) SetAvailable(v bool) {
	o.Available = v
}

// GetQuantityAvailable returns the QuantityAvailable field value
func (o *GetBuyerCatalogListingResponse) GetQuantityAvailable() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.QuantityAvailable
}

// GetQuantityAvailableOk returns a tuple with the QuantityAvailable field value
// and a boolean to check if the value has been set.
func (o *GetBuyerCatalogListingResponse) GetQuantityAvailableOk() (*float32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.QuantityAvailable, true
}

// SetQuantityAvailable sets field value
func (o *GetBuyerCatalogListingResponse) SetQuantityAvailable(v float32) {
	o.QuantityAvailable = v
}

// GetCondition returns the Condition field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetBuyerCatalogListingResponse) GetCondition() string {
	if o == nil || o.Condition.Get() == nil {
		var ret string
		return ret
	}
	return *o.Condition.Get()
}

// GetConditionOk returns a tuple with the Condition field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetBuyerCatalogListingResponse) GetConditionOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Condition.Get(), o.Condition.IsSet()
}

// HasCondition returns a boolean if a field has been set.
func (o *GetBuyerCatalogListingResponse) HasCondition() bool {
	if o != nil && o.Condition.IsSet() {
		return true
	}

	return false
}

// SetCondition gets a reference to the given NullableString and assigns it to the Condition field.
func (o *GetBuyerCatalogListingResponse) SetCondition(v string) {
	o.Condition.Set(&v)
}
// SetConditionNil sets the value for Condition to be an explicit nil
func (o *GetBuyerCatalogListingResponse) SetConditionNil() {
	o.Condition.Set(nil)
}

// UnsetCondition ensures that no value is present for Condition, not even an explicit nil
func (o *GetBuyerCatalogListingResponse) UnsetCondition() {
	o.Condition.Unset()
}

// GetBrand returns the Brand field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetBuyerCatalogListingResponse) GetBrand() string {
	if o == nil || o.Brand.Get() == nil {
		var ret string
		return ret
	}
	return *o.Brand.Get()
}

// GetBrandOk returns a tuple with the Brand field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetBuyerCatalogListingResponse) GetBrandOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Brand.Get(), o.Brand.IsSet()
}

// HasBrand returns a boolean if a field has been set.
func (o *GetBuyerCatalogListingResponse) HasBrand() bool {
	if o != nil && o.Brand.IsSet() {
		return true
	}

	return false
}

// SetBrand gets a reference to the given NullableString and assigns it to the Brand field.
func (o *GetBuyerCatalogListingResponse) SetBrand(v string) {
	o.Brand.Set(&v)
}
// SetBrandNil sets the value for Brand to be an explicit nil
func (o *GetBuyerCatalogListingResponse) SetBrandNil() {
	o.Brand.Set(nil)
}

// UnsetBrand ensures that no value is present for Brand, not even an explicit nil
func (o *GetBuyerCatalogListingResponse) UnsetBrand() {
	o.Brand.Unset()
}

// GetSize returns the Size field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetBuyerCatalogListingResponse) GetSize() string {
	if o == nil || o.Size.Get() == nil {
		var ret string
		return ret
	}
	return *o.Size.Get()
}

// GetSizeOk returns a tuple with the Size field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetBuyerCatalogListingResponse) GetSizeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Size.Get(), o.Size.IsSet()
}

// HasSize returns a boolean if a field has been set.
func (o *GetBuyerCatalogListingResponse) HasSize() bool {
	if o != nil && o.Size.IsSet() {
		return true
	}

	return false
}

// SetSize gets a reference to the given NullableString and assigns it to the Size field.
func (o *GetBuyerCatalogListingResponse) SetSize(v string) {
	o.Size.Set(&v)
}
// SetSizeNil sets the value for Size to be an explicit nil
func (o *GetBuyerCatalogListingResponse) SetSizeNil() {
	o.Size.Set(nil)
}

// UnsetSize ensures that no value is present for Size, not even an explicit nil
func (o *GetBuyerCatalogListingResponse) UnsetSize() {
	o.Size.Unset()
}

// GetColor returns the Color field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetBuyerCatalogListingResponse) GetColor() []string {
	if o == nil  {
		var ret []string
		return ret
	}
	return o.Color
}

// GetColorOk returns a tuple with the Color field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetBuyerCatalogListingResponse) GetColorOk() ([]string, bool) {
	if o == nil || o.Color == nil {
		return nil, false
	}
	return o.Color, true
}

// HasColor returns a boolean if a field has been set.
func (o *GetBuyerCatalogListingResponse) HasColor() bool {
	if o != nil && o.Color != nil {
		return true
	}

	return false
}

// SetColor gets a reference to the given []string and assigns it to the Color field.
func (o *GetBuyerCatalogListingResponse) SetColor(v []string) {
	o.Color = v
}

// GetCategoryMain returns the CategoryMain field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetBuyerCatalogListingResponse) GetCategoryMain() string {
	if o == nil || o.CategoryMain.Get() == nil {
		var ret string
		return ret
	}
	return *o.CategoryMain.Get()
}

// GetCategoryMainOk returns a tuple with the CategoryMain field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetBuyerCatalogListingResponse) GetCategoryMainOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.CategoryMain.Get(), o.CategoryMain.IsSet()
}

// HasCategoryMain returns a boolean if a field has been set.
func (o *GetBuyerCatalogListingResponse) HasCategoryMain() bool {
	if o != nil && o.CategoryMain.IsSet() {
		return true
	}

	return false
}

// SetCategoryMain gets a reference to the given NullableString and assigns it to the CategoryMain field.
func (o *GetBuyerCatalogListingResponse) SetCategoryMain(v string) {
	o.CategoryMain.Set(&v)
}
// SetCategoryMainNil sets the value for CategoryMain to be an explicit nil
func (o *GetBuyerCatalogListingResponse) SetCategoryMainNil() {
	o.CategoryMain.Set(nil)
}

// UnsetCategoryMain ensures that no value is present for CategoryMain, not even an explicit nil
func (o *GetBuyerCatalogListingResponse) UnsetCategoryMain() {
	o.CategoryMain.Unset()
}

// GetCategorySub returns the CategorySub field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetBuyerCatalogListingResponse) GetCategorySub() string {
	if o == nil || o.CategorySub.Get() == nil {
		var ret string
		return ret
	}
	return *o.CategorySub.Get()
}

// GetCategorySubOk returns a tuple with the CategorySub field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetBuyerCatalogListingResponse) GetCategorySubOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.CategorySub.Get(), o.CategorySub.IsSet()
}

// HasCategorySub returns a boolean if a field has been set.
func (o *GetBuyerCatalogListingResponse) HasCategorySub() bool {
	if o != nil && o.CategorySub.IsSet() {
		return true
	}

	return false
}

// SetCategorySub gets a reference to the given NullableString and assigns it to the CategorySub field.
func (o *GetBuyerCatalogListingResponse) SetCategorySub(v string) {
	o.CategorySub.Set(&v)
}
// SetCategorySubNil sets the value for CategorySub to be an explicit nil
func (o *GetBuyerCatalogListingResponse) SetCategorySubNil() {
	o.CategorySub.Set(nil)
}

// UnsetCategorySub ensures that no value is present for CategorySub, not even an explicit nil
func (o *GetBuyerCatalogListingResponse) UnsetCategorySub() {
	o.CategorySub.Unset()
}

// GetImages returns the Images field value
func (o *GetBuyerCatalogListingResponse) GetImages() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Images
}

// GetImagesOk returns a tuple with the Images field value
// and a boolean to check if the value has been set.
func (o *GetBuyerCatalogListingResponse) GetImagesOk() ([]string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Images, true
}

// SetImages sets field value
func (o *GetBuyerCatalogListingResponse) SetImages(v []string) {
	o.Images = v
}

// GetSellerUsername returns the SellerUsername field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetBuyerCatalogListingResponse) GetSellerUsername() string {
	if o == nil || o.SellerUsername.Get() == nil {
		var ret string
		return ret
	}
	return *o.SellerUsername.Get()
}

// GetSellerUsernameOk returns a tuple with the SellerUsername field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetBuyerCatalogListingResponse) GetSellerUsernameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.SellerUsername.Get(), o.SellerUsername.IsSet()
}

// HasSellerUsername returns a boolean if a field has been set.
func (o *GetBuyerCatalogListingResponse) HasSellerUsername() bool {
	if o != nil && o.SellerUsername.IsSet() {
		return true
	}

	return false
}

// SetSellerUsername gets a reference to the given NullableString and assigns it to the SellerUsername field.
func (o *GetBuyerCatalogListingResponse) SetSellerUsername(v string) {
	o.SellerUsername.Set(&v)
}
// SetSellerUsernameNil sets the value for SellerUsername to be an explicit nil
func (o *GetBuyerCatalogListingResponse) SetSellerUsernameNil() {
	o.SellerUsername.Set(nil)
}

// UnsetSellerUsername ensures that no value is present for SellerUsername, not even an explicit nil
func (o *GetBuyerCatalogListingResponse) UnsetSellerUsername() {
	o.SellerUsername.Unset()
}

// GetSellerDisplayName returns the SellerDisplayName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetBuyerCatalogListingResponse) GetSellerDisplayName() string {
	if o == nil || o.SellerDisplayName.Get() == nil {
		var ret string
		return ret
	}
	return *o.SellerDisplayName.Get()
}

// GetSellerDisplayNameOk returns a tuple with the SellerDisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetBuyerCatalogListingResponse) GetSellerDisplayNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.SellerDisplayName.Get(), o.SellerDisplayName.IsSet()
}

// HasSellerDisplayName returns a boolean if a field has been set.
func (o *GetBuyerCatalogListingResponse) HasSellerDisplayName() bool {
	if o != nil && o.SellerDisplayName.IsSet() {
		return true
	}

	return false
}

// SetSellerDisplayName gets a reference to the given NullableString and assigns it to the SellerDisplayName field.
func (o *GetBuyerCatalogListingResponse) SetSellerDisplayName(v string) {
	o.SellerDisplayName.Set(&v)
}
// SetSellerDisplayNameNil sets the value for SellerDisplayName to be an explicit nil
func (o *GetBuyerCatalogListingResponse) SetSellerDisplayNameNil() {
	o.SellerDisplayName.Set(nil)
}

// UnsetSellerDisplayName ensures that no value is present for SellerDisplayName, not even an explicit nil
func (o *GetBuyerCatalogListingResponse) UnsetSellerDisplayName() {
	o.SellerDisplayName.Unset()
}

// GetListedAt returns the ListedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetBuyerCatalogListingResponse) GetListedAt() string {
	if o == nil || o.ListedAt.Get() == nil {
		var ret string
		return ret
	}
	return *o.ListedAt.Get()
}

// GetListedAtOk returns a tuple with the ListedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetBuyerCatalogListingResponse) GetListedAtOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.ListedAt.Get(), o.ListedAt.IsSet()
}

// HasListedAt returns a boolean if a field has been set.
func (o *GetBuyerCatalogListingResponse) HasListedAt() bool {
	if o != nil && o.ListedAt.IsSet() {
		return true
	}

	return false
}

// SetListedAt gets a reference to the given NullableString and assigns it to the ListedAt field.
func (o *GetBuyerCatalogListingResponse) SetListedAt(v string) {
	o.ListedAt.Set(&v)
}
// SetListedAtNil sets the value for ListedAt to be an explicit nil
func (o *GetBuyerCatalogListingResponse) SetListedAtNil() {
	o.ListedAt.Set(nil)
}

// UnsetListedAt ensures that no value is present for ListedAt, not even an explicit nil
func (o *GetBuyerCatalogListingResponse) UnsetListedAt() {
	o.ListedAt.Unset()
}

func (o GetBuyerCatalogListingResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["slug"] = o.Slug
	}
	if true {
		toSerialize["title"] = o.Title
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if true {
		toSerialize["priceCents"] = o.PriceCents
	}
	if o.CompareAtCents.IsSet() {
		toSerialize["compareAtCents"] = o.CompareAtCents.Get()
	}
	if true {
		toSerialize["currency"] = o.Currency
	}
	if true {
		toSerialize["status"] = o.Status
	}
	if true {
		toSerialize["available"] = o.Available
	}
	if true {
		toSerialize["quantityAvailable"] = o.QuantityAvailable
	}
	if o.Condition.IsSet() {
		toSerialize["condition"] = o.Condition.Get()
	}
	if o.Brand.IsSet() {
		toSerialize["brand"] = o.Brand.Get()
	}
	if o.Size.IsSet() {
		toSerialize["size"] = o.Size.Get()
	}
	if o.Color != nil {
		toSerialize["color"] = o.Color
	}
	if o.CategoryMain.IsSet() {
		toSerialize["categoryMain"] = o.CategoryMain.Get()
	}
	if o.CategorySub.IsSet() {
		toSerialize["categorySub"] = o.CategorySub.Get()
	}
	if true {
		toSerialize["images"] = o.Images
	}
	if o.SellerUsername.IsSet() {
		toSerialize["sellerUsername"] = o.SellerUsername.Get()
	}
	if o.SellerDisplayName.IsSet() {
		toSerialize["sellerDisplayName"] = o.SellerDisplayName.Get()
	}
	if o.ListedAt.IsSet() {
		toSerialize["listedAt"] = o.ListedAt.Get()
	}
	return json.Marshal(toSerialize)
}

type NullableGetBuyerCatalogListingResponse struct {
	value *GetBuyerCatalogListingResponse
	isSet bool
}

func (v NullableGetBuyerCatalogListingResponse) Get() *GetBuyerCatalogListingResponse {
	return v.value
}

func (v *NullableGetBuyerCatalogListingResponse) Set(val *GetBuyerCatalogListingResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetBuyerCatalogListingResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetBuyerCatalogListingResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetBuyerCatalogListingResponse(val *GetBuyerCatalogListingResponse) *NullableGetBuyerCatalogListingResponse {
	return &NullableGetBuyerCatalogListingResponse{value: val, isSet: true}
}

func (v NullableGetBuyerCatalogListingResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetBuyerCatalogListingResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


