/*
Crossly Buyer API

The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crossly_buyer

import (
	"encoding/json"
	"time"
)

// ListInboxItem struct for ListInboxItem
type ListInboxItem struct {
	Id string `json:"id"`
	CreatedAt time.Time `json:"createdAt"`
	UserId string `json:"userId"`
	Status string `json:"status"`
	Platform string `json:"platform"`
	ListingId NullableString `json:"listingId,omitempty"`
	AccountSlot float32 `json:"accountSlot"`
	InventoryItemId NullableString `json:"inventoryItemId,omitempty"`
	BuyerUsername NullableString `json:"buyerUsername,omitempty"`
	Subject NullableString `json:"subject,omitempty"`
	PlatformConversationId string `json:"platformConversationId"`
	BuyerPlatformId NullableString `json:"buyerPlatformId,omitempty"`
	IsRead bool `json:"isRead"`
	IsHidden bool `json:"isHidden"`
	HasOffer bool `json:"hasOffer"`
	OfferAmount NullableString `json:"offerAmount,omitempty"`
	OfferStatus NullableString `json:"offerStatus,omitempty"`
	PlatformConversationUrl NullableString `json:"platformConversationUrl,omitempty"`
	LastMessageAt NullableTime `json:"lastMessageAt,omitempty"`
}

// NewListInboxItem instantiates a new ListInboxItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListInboxItem(id string, createdAt time.Time, userId string, status string, platform string, accountSlot float32, platformConversationId string, isRead bool, isHidden bool, hasOffer bool) *ListInboxItem {
	this := ListInboxItem{}
	this.Id = id
	this.CreatedAt = createdAt
	this.UserId = userId
	this.Status = status
	this.Platform = platform
	this.AccountSlot = accountSlot
	this.PlatformConversationId = platformConversationId
	this.IsRead = isRead
	this.IsHidden = isHidden
	this.HasOffer = hasOffer
	return &this
}

// NewListInboxItemWithDefaults instantiates a new ListInboxItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListInboxItemWithDefaults() *ListInboxItem {
	this := ListInboxItem{}
	return &this
}

// GetId returns the Id field value
func (o *ListInboxItem) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ListInboxItem) GetIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ListInboxItem) SetId(v string) {
	o.Id = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *ListInboxItem) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *ListInboxItem) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *ListInboxItem) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUserId returns the UserId field value
func (o *ListInboxItem) GetUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *ListInboxItem) GetUserIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *ListInboxItem) SetUserId(v string) {
	o.UserId = v
}

// GetStatus returns the Status field value
func (o *ListInboxItem) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *ListInboxItem) GetStatusOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *ListInboxItem) SetStatus(v string) {
	o.Status = v
}

// GetPlatform returns the Platform field value
func (o *ListInboxItem) GetPlatform() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Platform
}

// GetPlatformOk returns a tuple with the Platform field value
// and a boolean to check if the value has been set.
func (o *ListInboxItem) GetPlatformOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Platform, true
}

// SetPlatform sets field value
func (o *ListInboxItem) SetPlatform(v string) {
	o.Platform = v
}

// GetListingId returns the ListingId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListInboxItem) GetListingId() string {
	if o == nil || o.ListingId.Get() == nil {
		var ret string
		return ret
	}
	return *o.ListingId.Get()
}

// GetListingIdOk returns a tuple with the ListingId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListInboxItem) GetListingIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.ListingId.Get(), o.ListingId.IsSet()
}

// HasListingId returns a boolean if a field has been set.
func (o *ListInboxItem) HasListingId() bool {
	if o != nil && o.ListingId.IsSet() {
		return true
	}

	return false
}

// SetListingId gets a reference to the given NullableString and assigns it to the ListingId field.
func (o *ListInboxItem) SetListingId(v string) {
	o.ListingId.Set(&v)
}
// SetListingIdNil sets the value for ListingId to be an explicit nil
func (o *ListInboxItem) SetListingIdNil() {
	o.ListingId.Set(nil)
}

// UnsetListingId ensures that no value is present for ListingId, not even an explicit nil
func (o *ListInboxItem) UnsetListingId() {
	o.ListingId.Unset()
}

// GetAccountSlot returns the AccountSlot field value
func (o *ListInboxItem) GetAccountSlot() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.AccountSlot
}

// GetAccountSlotOk returns a tuple with the AccountSlot field value
// and a boolean to check if the value has been set.
func (o *ListInboxItem) GetAccountSlotOk() (*float32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.AccountSlot, true
}

// SetAccountSlot sets field value
func (o *ListInboxItem) SetAccountSlot(v float32) {
	o.AccountSlot = v
}

// GetInventoryItemId returns the InventoryItemId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListInboxItem) GetInventoryItemId() string {
	if o == nil || o.InventoryItemId.Get() == nil {
		var ret string
		return ret
	}
	return *o.InventoryItemId.Get()
}

// GetInventoryItemIdOk returns a tuple with the InventoryItemId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListInboxItem) GetInventoryItemIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.InventoryItemId.Get(), o.InventoryItemId.IsSet()
}

// HasInventoryItemId returns a boolean if a field has been set.
func (o *ListInboxItem) HasInventoryItemId() bool {
	if o != nil && o.InventoryItemId.IsSet() {
		return true
	}

	return false
}

// SetInventoryItemId gets a reference to the given NullableString and assigns it to the InventoryItemId field.
func (o *ListInboxItem) SetInventoryItemId(v string) {
	o.InventoryItemId.Set(&v)
}
// SetInventoryItemIdNil sets the value for InventoryItemId to be an explicit nil
func (o *ListInboxItem) SetInventoryItemIdNil() {
	o.InventoryItemId.Set(nil)
}

// UnsetInventoryItemId ensures that no value is present for InventoryItemId, not even an explicit nil
func (o *ListInboxItem) UnsetInventoryItemId() {
	o.InventoryItemId.Unset()
}

// GetBuyerUsername returns the BuyerUsername field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListInboxItem) GetBuyerUsername() string {
	if o == nil || o.BuyerUsername.Get() == nil {
		var ret string
		return ret
	}
	return *o.BuyerUsername.Get()
}

// GetBuyerUsernameOk returns a tuple with the BuyerUsername field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListInboxItem) GetBuyerUsernameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.BuyerUsername.Get(), o.BuyerUsername.IsSet()
}

// HasBuyerUsername returns a boolean if a field has been set.
func (o *ListInboxItem) HasBuyerUsername() bool {
	if o != nil && o.BuyerUsername.IsSet() {
		return true
	}

	return false
}

// SetBuyerUsername gets a reference to the given NullableString and assigns it to the BuyerUsername field.
func (o *ListInboxItem) SetBuyerUsername(v string) {
	o.BuyerUsername.Set(&v)
}
// SetBuyerUsernameNil sets the value for BuyerUsername to be an explicit nil
func (o *ListInboxItem) SetBuyerUsernameNil() {
	o.BuyerUsername.Set(nil)
}

// UnsetBuyerUsername ensures that no value is present for BuyerUsername, not even an explicit nil
func (o *ListInboxItem) UnsetBuyerUsername() {
	o.BuyerUsername.Unset()
}

// GetSubject returns the Subject field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListInboxItem) GetSubject() string {
	if o == nil || o.Subject.Get() == nil {
		var ret string
		return ret
	}
	return *o.Subject.Get()
}

// GetSubjectOk returns a tuple with the Subject field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListInboxItem) GetSubjectOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Subject.Get(), o.Subject.IsSet()
}

// HasSubject returns a boolean if a field has been set.
func (o *ListInboxItem) HasSubject() bool {
	if o != nil && o.Subject.IsSet() {
		return true
	}

	return false
}

// SetSubject gets a reference to the given NullableString and assigns it to the Subject field.
func (o *ListInboxItem) SetSubject(v string) {
	o.Subject.Set(&v)
}
// SetSubjectNil sets the value for Subject to be an explicit nil
func (o *ListInboxItem) SetSubjectNil() {
	o.Subject.Set(nil)
}

// UnsetSubject ensures that no value is present for Subject, not even an explicit nil
func (o *ListInboxItem) UnsetSubject() {
	o.Subject.Unset()
}

// GetPlatformConversationId returns the PlatformConversationId field value
func (o *ListInboxItem) GetPlatformConversationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PlatformConversationId
}

// GetPlatformConversationIdOk returns a tuple with the PlatformConversationId field value
// and a boolean to check if the value has been set.
func (o *ListInboxItem) GetPlatformConversationIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.PlatformConversationId, true
}

// SetPlatformConversationId sets field value
func (o *ListInboxItem) SetPlatformConversationId(v string) {
	o.PlatformConversationId = v
}

// GetBuyerPlatformId returns the BuyerPlatformId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListInboxItem) GetBuyerPlatformId() string {
	if o == nil || o.BuyerPlatformId.Get() == nil {
		var ret string
		return ret
	}
	return *o.BuyerPlatformId.Get()
}

// GetBuyerPlatformIdOk returns a tuple with the BuyerPlatformId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListInboxItem) GetBuyerPlatformIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.BuyerPlatformId.Get(), o.BuyerPlatformId.IsSet()
}

// HasBuyerPlatformId returns a boolean if a field has been set.
func (o *ListInboxItem) HasBuyerPlatformId() bool {
	if o != nil && o.BuyerPlatformId.IsSet() {
		return true
	}

	return false
}

// SetBuyerPlatformId gets a reference to the given NullableString and assigns it to the BuyerPlatformId field.
func (o *ListInboxItem) SetBuyerPlatformId(v string) {
	o.BuyerPlatformId.Set(&v)
}
// SetBuyerPlatformIdNil sets the value for BuyerPlatformId to be an explicit nil
func (o *ListInboxItem) SetBuyerPlatformIdNil() {
	o.BuyerPlatformId.Set(nil)
}

// UnsetBuyerPlatformId ensures that no value is present for BuyerPlatformId, not even an explicit nil
func (o *ListInboxItem) UnsetBuyerPlatformId() {
	o.BuyerPlatformId.Unset()
}

// GetIsRead returns the IsRead field value
func (o *ListInboxItem) GetIsRead() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsRead
}

// GetIsReadOk returns a tuple with the IsRead field value
// and a boolean to check if the value has been set.
func (o *ListInboxItem) GetIsReadOk() (*bool, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.IsRead, true
}

// SetIsRead sets field value
func (o *ListInboxItem) SetIsRead(v bool) {
	o.IsRead = v
}

// GetIsHidden returns the IsHidden field value
func (o *ListInboxItem) GetIsHidden() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsHidden
}

// GetIsHiddenOk returns a tuple with the IsHidden field value
// and a boolean to check if the value has been set.
func (o *ListInboxItem) GetIsHiddenOk() (*bool, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.IsHidden, true
}

// SetIsHidden sets field value
func (o *ListInboxItem) SetIsHidden(v bool) {
	o.IsHidden = v
}

// GetHasOffer returns the HasOffer field value
func (o *ListInboxItem) GetHasOffer() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.HasOffer
}

// GetHasOfferOk returns a tuple with the HasOffer field value
// and a boolean to check if the value has been set.
func (o *ListInboxItem) GetHasOfferOk() (*bool, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.HasOffer, true
}

// SetHasOffer sets field value
func (o *ListInboxItem) SetHasOffer(v bool) {
	o.HasOffer = v
}

// GetOfferAmount returns the OfferAmount field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListInboxItem) GetOfferAmount() string {
	if o == nil || o.OfferAmount.Get() == nil {
		var ret string
		return ret
	}
	return *o.OfferAmount.Get()
}

// GetOfferAmountOk returns a tuple with the OfferAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListInboxItem) GetOfferAmountOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.OfferAmount.Get(), o.OfferAmount.IsSet()
}

// HasOfferAmount returns a boolean if a field has been set.
func (o *ListInboxItem) HasOfferAmount() bool {
	if o != nil && o.OfferAmount.IsSet() {
		return true
	}

	return false
}

// SetOfferAmount gets a reference to the given NullableString and assigns it to the OfferAmount field.
func (o *ListInboxItem) SetOfferAmount(v string) {
	o.OfferAmount.Set(&v)
}
// SetOfferAmountNil sets the value for OfferAmount to be an explicit nil
func (o *ListInboxItem) SetOfferAmountNil() {
	o.OfferAmount.Set(nil)
}

// UnsetOfferAmount ensures that no value is present for OfferAmount, not even an explicit nil
func (o *ListInboxItem) UnsetOfferAmount() {
	o.OfferAmount.Unset()
}

// GetOfferStatus returns the OfferStatus field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListInboxItem) GetOfferStatus() string {
	if o == nil || o.OfferStatus.Get() == nil {
		var ret string
		return ret
	}
	return *o.OfferStatus.Get()
}

// GetOfferStatusOk returns a tuple with the OfferStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListInboxItem) GetOfferStatusOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.OfferStatus.Get(), o.OfferStatus.IsSet()
}

// HasOfferStatus returns a boolean if a field has been set.
func (o *ListInboxItem) HasOfferStatus() bool {
	if o != nil && o.OfferStatus.IsSet() {
		return true
	}

	return false
}

// SetOfferStatus gets a reference to the given NullableString and assigns it to the OfferStatus field.
func (o *ListInboxItem) SetOfferStatus(v string) {
	o.OfferStatus.Set(&v)
}
// SetOfferStatusNil sets the value for OfferStatus to be an explicit nil
func (o *ListInboxItem) SetOfferStatusNil() {
	o.OfferStatus.Set(nil)
}

// UnsetOfferStatus ensures that no value is present for OfferStatus, not even an explicit nil
func (o *ListInboxItem) UnsetOfferStatus() {
	o.OfferStatus.Unset()
}

// GetPlatformConversationUrl returns the PlatformConversationUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListInboxItem) GetPlatformConversationUrl() string {
	if o == nil || o.PlatformConversationUrl.Get() == nil {
		var ret string
		return ret
	}
	return *o.PlatformConversationUrl.Get()
}

// GetPlatformConversationUrlOk returns a tuple with the PlatformConversationUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListInboxItem) GetPlatformConversationUrlOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.PlatformConversationUrl.Get(), o.PlatformConversationUrl.IsSet()
}

// HasPlatformConversationUrl returns a boolean if a field has been set.
func (o *ListInboxItem) HasPlatformConversationUrl() bool {
	if o != nil && o.PlatformConversationUrl.IsSet() {
		return true
	}

	return false
}

// SetPlatformConversationUrl gets a reference to the given NullableString and assigns it to the PlatformConversationUrl field.
func (o *ListInboxItem) SetPlatformConversationUrl(v string) {
	o.PlatformConversationUrl.Set(&v)
}
// SetPlatformConversationUrlNil sets the value for PlatformConversationUrl to be an explicit nil
func (o *ListInboxItem) SetPlatformConversationUrlNil() {
	o.PlatformConversationUrl.Set(nil)
}

// UnsetPlatformConversationUrl ensures that no value is present for PlatformConversationUrl, not even an explicit nil
func (o *ListInboxItem) UnsetPlatformConversationUrl() {
	o.PlatformConversationUrl.Unset()
}

// GetLastMessageAt returns the LastMessageAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListInboxItem) GetLastMessageAt() time.Time {
	if o == nil || o.LastMessageAt.Get() == nil {
		var ret time.Time
		return ret
	}
	return *o.LastMessageAt.Get()
}

// GetLastMessageAtOk returns a tuple with the LastMessageAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListInboxItem) GetLastMessageAtOk() (*time.Time, bool) {
	if o == nil  {
		return nil, false
	}
	return o.LastMessageAt.Get(), o.LastMessageAt.IsSet()
}

// HasLastMessageAt returns a boolean if a field has been set.
func (o *ListInboxItem) HasLastMessageAt() bool {
	if o != nil && o.LastMessageAt.IsSet() {
		return true
	}

	return false
}

// SetLastMessageAt gets a reference to the given NullableTime and assigns it to the LastMessageAt field.
func (o *ListInboxItem) SetLastMessageAt(v time.Time) {
	o.LastMessageAt.Set(&v)
}
// SetLastMessageAtNil sets the value for LastMessageAt to be an explicit nil
func (o *ListInboxItem) SetLastMessageAtNil() {
	o.LastMessageAt.Set(nil)
}

// UnsetLastMessageAt ensures that no value is present for LastMessageAt, not even an explicit nil
func (o *ListInboxItem) UnsetLastMessageAt() {
	o.LastMessageAt.Unset()
}

func (o ListInboxItem) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if true {
		toSerialize["userId"] = o.UserId
	}
	if true {
		toSerialize["status"] = o.Status
	}
	if true {
		toSerialize["platform"] = o.Platform
	}
	if o.ListingId.IsSet() {
		toSerialize["listingId"] = o.ListingId.Get()
	}
	if true {
		toSerialize["accountSlot"] = o.AccountSlot
	}
	if o.InventoryItemId.IsSet() {
		toSerialize["inventoryItemId"] = o.InventoryItemId.Get()
	}
	if o.BuyerUsername.IsSet() {
		toSerialize["buyerUsername"] = o.BuyerUsername.Get()
	}
	if o.Subject.IsSet() {
		toSerialize["subject"] = o.Subject.Get()
	}
	if true {
		toSerialize["platformConversationId"] = o.PlatformConversationId
	}
	if o.BuyerPlatformId.IsSet() {
		toSerialize["buyerPlatformId"] = o.BuyerPlatformId.Get()
	}
	if true {
		toSerialize["isRead"] = o.IsRead
	}
	if true {
		toSerialize["isHidden"] = o.IsHidden
	}
	if true {
		toSerialize["hasOffer"] = o.HasOffer
	}
	if o.OfferAmount.IsSet() {
		toSerialize["offerAmount"] = o.OfferAmount.Get()
	}
	if o.OfferStatus.IsSet() {
		toSerialize["offerStatus"] = o.OfferStatus.Get()
	}
	if o.PlatformConversationUrl.IsSet() {
		toSerialize["platformConversationUrl"] = o.PlatformConversationUrl.Get()
	}
	if o.LastMessageAt.IsSet() {
		toSerialize["lastMessageAt"] = o.LastMessageAt.Get()
	}
	return json.Marshal(toSerialize)
}

type NullableListInboxItem struct {
	value *ListInboxItem
	isSet bool
}

func (v NullableListInboxItem) Get() *ListInboxItem {
	return v.value
}

func (v *NullableListInboxItem) Set(val *ListInboxItem) {
	v.value = val
	v.isSet = true
}

func (v NullableListInboxItem) IsSet() bool {
	return v.isSet
}

func (v *NullableListInboxItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListInboxItem(val *ListInboxItem) *NullableListInboxItem {
	return &NullableListInboxItem{value: val, isSet: true}
}

func (v NullableListInboxItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListInboxItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


