/*
Crossly Buyer API

The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crossly_buyer

import (
	"encoding/json"
	"time"
)

// UpdateSavedViewResponse struct for UpdateSavedViewResponse
type UpdateSavedViewResponse struct {
	Id string `json:"id"`
	UserId string `json:"userId"`
	Resource string `json:"resource"`
	Name string `json:"name"`
	ViewMode NullableString `json:"viewMode,omitempty"`
	IsDefault bool `json:"isDefault"`
	SortOrder float32 `json:"sortOrder"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// NewUpdateSavedViewResponse instantiates a new UpdateSavedViewResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateSavedViewResponse(id string, userId string, resource string, name string, isDefault bool, sortOrder float32, createdAt time.Time, updatedAt time.Time) *UpdateSavedViewResponse {
	this := UpdateSavedViewResponse{}
	this.Id = id
	this.UserId = userId
	this.Resource = resource
	this.Name = name
	this.IsDefault = isDefault
	this.SortOrder = sortOrder
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	return &this
}

// NewUpdateSavedViewResponseWithDefaults instantiates a new UpdateSavedViewResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateSavedViewResponseWithDefaults() *UpdateSavedViewResponse {
	this := UpdateSavedViewResponse{}
	return &this
}

// GetId returns the Id field value
func (o *UpdateSavedViewResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *UpdateSavedViewResponse) GetIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *UpdateSavedViewResponse) SetId(v string) {
	o.Id = v
}

// GetUserId returns the UserId field value
func (o *UpdateSavedViewResponse) GetUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *UpdateSavedViewResponse) GetUserIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *UpdateSavedViewResponse) SetUserId(v string) {
	o.UserId = v
}

// GetResource returns the Resource field value
func (o *UpdateSavedViewResponse) GetResource() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Resource
}

// GetResourceOk returns a tuple with the Resource field value
// and a boolean to check if the value has been set.
func (o *UpdateSavedViewResponse) GetResourceOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Resource, true
}

// SetResource sets field value
func (o *UpdateSavedViewResponse) SetResource(v string) {
	o.Resource = v
}

// GetName returns the Name field value
func (o *UpdateSavedViewResponse) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *UpdateSavedViewResponse) GetNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *UpdateSavedViewResponse) SetName(v string) {
	o.Name = v
}

// GetViewMode returns the ViewMode field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateSavedViewResponse) GetViewMode() string {
	if o == nil || o.ViewMode.Get() == nil {
		var ret string
		return ret
	}
	return *o.ViewMode.Get()
}

// GetViewModeOk returns a tuple with the ViewMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateSavedViewResponse) GetViewModeOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.ViewMode.Get(), o.ViewMode.IsSet()
}

// HasViewMode returns a boolean if a field has been set.
func (o *UpdateSavedViewResponse) HasViewMode() bool {
	if o != nil && o.ViewMode.IsSet() {
		return true
	}

	return false
}

// SetViewMode gets a reference to the given NullableString and assigns it to the ViewMode field.
func (o *UpdateSavedViewResponse) SetViewMode(v string) {
	o.ViewMode.Set(&v)
}
// SetViewModeNil sets the value for ViewMode to be an explicit nil
func (o *UpdateSavedViewResponse) SetViewModeNil() {
	o.ViewMode.Set(nil)
}

// UnsetViewMode ensures that no value is present for ViewMode, not even an explicit nil
func (o *UpdateSavedViewResponse) UnsetViewMode() {
	o.ViewMode.Unset()
}

// GetIsDefault returns the IsDefault field value
func (o *UpdateSavedViewResponse) GetIsDefault() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.IsDefault
}

// GetIsDefaultOk returns a tuple with the IsDefault field value
// and a boolean to check if the value has been set.
func (o *UpdateSavedViewResponse) GetIsDefaultOk() (*bool, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.IsDefault, true
}

// SetIsDefault sets field value
func (o *UpdateSavedViewResponse) SetIsDefault(v bool) {
	o.IsDefault = v
}

// GetSortOrder returns the SortOrder field value
func (o *UpdateSavedViewResponse) GetSortOrder() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.SortOrder
}

// GetSortOrderOk returns a tuple with the SortOrder field value
// and a boolean to check if the value has been set.
func (o *UpdateSavedViewResponse) GetSortOrderOk() (*float32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.SortOrder, true
}

// SetSortOrder sets field value
func (o *UpdateSavedViewResponse) SetSortOrder(v float32) {
	o.SortOrder = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *UpdateSavedViewResponse) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *UpdateSavedViewResponse) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *UpdateSavedViewResponse) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *UpdateSavedViewResponse) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *UpdateSavedViewResponse) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *UpdateSavedViewResponse) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

func (o UpdateSavedViewResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["userId"] = o.UserId
	}
	if true {
		toSerialize["resource"] = o.Resource
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if o.ViewMode.IsSet() {
		toSerialize["viewMode"] = o.ViewMode.Get()
	}
	if true {
		toSerialize["isDefault"] = o.IsDefault
	}
	if true {
		toSerialize["sortOrder"] = o.SortOrder
	}
	if true {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if true {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	return json.Marshal(toSerialize)
}

type NullableUpdateSavedViewResponse struct {
	value *UpdateSavedViewResponse
	isSet bool
}

func (v NullableUpdateSavedViewResponse) Get() *UpdateSavedViewResponse {
	return v.value
}

func (v *NullableUpdateSavedViewResponse) Set(val *UpdateSavedViewResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateSavedViewResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateSavedViewResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateSavedViewResponse(val *UpdateSavedViewResponse) *NullableUpdateSavedViewResponse {
	return &NullableUpdateSavedViewResponse{value: val, isSet: true}
}

func (v NullableUpdateSavedViewResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateSavedViewResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


