/*
Crossly Buyer API

The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crossly_buyer

import (
	"encoding/json"
)

// CreateMagicScanResponseEbayHits struct for CreateMagicScanResponseEbayHits
type CreateMagicScanResponseEbayHits struct {
	ItemId string `json:"itemId"`
	LegacyItemId NullableString `json:"legacyItemId,omitempty"`
	Title string `json:"title"`
	Brand NullableString `json:"brand,omitempty"`
	// Normalized cents. eBay returns string + currency on `price.value`.
	PriceCents NullableFloat32 `json:"priceCents,omitempty"`
	Currency NullableString `json:"currency,omitempty"`
	Condition NullableString `json:"condition,omitempty"`
	// Top-level category eBay assigned to the match (id + path).
	CategoryId NullableString `json:"categoryId,omitempty"`
	CategoryPath NullableString `json:"categoryPath,omitempty"`
	ItemUrl string `json:"itemUrl"`
	ThumbnailUrl NullableString `json:"thumbnailUrl,omitempty"`
	// Loosely-typed aspect bag — Brand, Color, Material, etc. when eBay inlines them. Always inspected defensively by the synthesizer.
	Aspects map[string]interface{} `json:"aspects,omitempty"`
}

// NewCreateMagicScanResponseEbayHits instantiates a new CreateMagicScanResponseEbayHits object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateMagicScanResponseEbayHits(itemId string, title string, itemUrl string) *CreateMagicScanResponseEbayHits {
	this := CreateMagicScanResponseEbayHits{}
	this.ItemId = itemId
	this.Title = title
	this.ItemUrl = itemUrl
	return &this
}

// NewCreateMagicScanResponseEbayHitsWithDefaults instantiates a new CreateMagicScanResponseEbayHits object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateMagicScanResponseEbayHitsWithDefaults() *CreateMagicScanResponseEbayHits {
	this := CreateMagicScanResponseEbayHits{}
	return &this
}

// GetItemId returns the ItemId field value
func (o *CreateMagicScanResponseEbayHits) GetItemId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ItemId
}

// GetItemIdOk returns a tuple with the ItemId field value
// and a boolean to check if the value has been set.
func (o *CreateMagicScanResponseEbayHits) GetItemIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ItemId, true
}

// SetItemId sets field value
func (o *CreateMagicScanResponseEbayHits) SetItemId(v string) {
	o.ItemId = v
}

// GetLegacyItemId returns the LegacyItemId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateMagicScanResponseEbayHits) GetLegacyItemId() string {
	if o == nil || o.LegacyItemId.Get() == nil {
		var ret string
		return ret
	}
	return *o.LegacyItemId.Get()
}

// GetLegacyItemIdOk returns a tuple with the LegacyItemId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateMagicScanResponseEbayHits) GetLegacyItemIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.LegacyItemId.Get(), o.LegacyItemId.IsSet()
}

// HasLegacyItemId returns a boolean if a field has been set.
func (o *CreateMagicScanResponseEbayHits) HasLegacyItemId() bool {
	if o != nil && o.LegacyItemId.IsSet() {
		return true
	}

	return false
}

// SetLegacyItemId gets a reference to the given NullableString and assigns it to the LegacyItemId field.
func (o *CreateMagicScanResponseEbayHits) SetLegacyItemId(v string) {
	o.LegacyItemId.Set(&v)
}
// SetLegacyItemIdNil sets the value for LegacyItemId to be an explicit nil
func (o *CreateMagicScanResponseEbayHits) SetLegacyItemIdNil() {
	o.LegacyItemId.Set(nil)
}

// UnsetLegacyItemId ensures that no value is present for LegacyItemId, not even an explicit nil
func (o *CreateMagicScanResponseEbayHits) UnsetLegacyItemId() {
	o.LegacyItemId.Unset()
}

// GetTitle returns the Title field value
func (o *CreateMagicScanResponseEbayHits) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *CreateMagicScanResponseEbayHits) GetTitleOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *CreateMagicScanResponseEbayHits) SetTitle(v string) {
	o.Title = v
}

// GetBrand returns the Brand field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateMagicScanResponseEbayHits) GetBrand() string {
	if o == nil || o.Brand.Get() == nil {
		var ret string
		return ret
	}
	return *o.Brand.Get()
}

// GetBrandOk returns a tuple with the Brand field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateMagicScanResponseEbayHits) GetBrandOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Brand.Get(), o.Brand.IsSet()
}

// HasBrand returns a boolean if a field has been set.
func (o *CreateMagicScanResponseEbayHits) HasBrand() bool {
	if o != nil && o.Brand.IsSet() {
		return true
	}

	return false
}

// SetBrand gets a reference to the given NullableString and assigns it to the Brand field.
func (o *CreateMagicScanResponseEbayHits) SetBrand(v string) {
	o.Brand.Set(&v)
}
// SetBrandNil sets the value for Brand to be an explicit nil
func (o *CreateMagicScanResponseEbayHits) SetBrandNil() {
	o.Brand.Set(nil)
}

// UnsetBrand ensures that no value is present for Brand, not even an explicit nil
func (o *CreateMagicScanResponseEbayHits) UnsetBrand() {
	o.Brand.Unset()
}

// GetPriceCents returns the PriceCents field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateMagicScanResponseEbayHits) GetPriceCents() float32 {
	if o == nil || o.PriceCents.Get() == nil {
		var ret float32
		return ret
	}
	return *o.PriceCents.Get()
}

// GetPriceCentsOk returns a tuple with the PriceCents field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateMagicScanResponseEbayHits) GetPriceCentsOk() (*float32, bool) {
	if o == nil  {
		return nil, false
	}
	return o.PriceCents.Get(), o.PriceCents.IsSet()
}

// HasPriceCents returns a boolean if a field has been set.
func (o *CreateMagicScanResponseEbayHits) HasPriceCents() bool {
	if o != nil && o.PriceCents.IsSet() {
		return true
	}

	return false
}

// SetPriceCents gets a reference to the given NullableFloat32 and assigns it to the PriceCents field.
func (o *CreateMagicScanResponseEbayHits) SetPriceCents(v float32) {
	o.PriceCents.Set(&v)
}
// SetPriceCentsNil sets the value for PriceCents to be an explicit nil
func (o *CreateMagicScanResponseEbayHits) SetPriceCentsNil() {
	o.PriceCents.Set(nil)
}

// UnsetPriceCents ensures that no value is present for PriceCents, not even an explicit nil
func (o *CreateMagicScanResponseEbayHits) UnsetPriceCents() {
	o.PriceCents.Unset()
}

// GetCurrency returns the Currency field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateMagicScanResponseEbayHits) GetCurrency() string {
	if o == nil || o.Currency.Get() == nil {
		var ret string
		return ret
	}
	return *o.Currency.Get()
}

// GetCurrencyOk returns a tuple with the Currency field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateMagicScanResponseEbayHits) GetCurrencyOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Currency.Get(), o.Currency.IsSet()
}

// HasCurrency returns a boolean if a field has been set.
func (o *CreateMagicScanResponseEbayHits) HasCurrency() bool {
	if o != nil && o.Currency.IsSet() {
		return true
	}

	return false
}

// SetCurrency gets a reference to the given NullableString and assigns it to the Currency field.
func (o *CreateMagicScanResponseEbayHits) SetCurrency(v string) {
	o.Currency.Set(&v)
}
// SetCurrencyNil sets the value for Currency to be an explicit nil
func (o *CreateMagicScanResponseEbayHits) SetCurrencyNil() {
	o.Currency.Set(nil)
}

// UnsetCurrency ensures that no value is present for Currency, not even an explicit nil
func (o *CreateMagicScanResponseEbayHits) UnsetCurrency() {
	o.Currency.Unset()
}

// GetCondition returns the Condition field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateMagicScanResponseEbayHits) GetCondition() string {
	if o == nil || o.Condition.Get() == nil {
		var ret string
		return ret
	}
	return *o.Condition.Get()
}

// GetConditionOk returns a tuple with the Condition field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateMagicScanResponseEbayHits) GetConditionOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Condition.Get(), o.Condition.IsSet()
}

// HasCondition returns a boolean if a field has been set.
func (o *CreateMagicScanResponseEbayHits) HasCondition() bool {
	if o != nil && o.Condition.IsSet() {
		return true
	}

	return false
}

// SetCondition gets a reference to the given NullableString and assigns it to the Condition field.
func (o *CreateMagicScanResponseEbayHits) SetCondition(v string) {
	o.Condition.Set(&v)
}
// SetConditionNil sets the value for Condition to be an explicit nil
func (o *CreateMagicScanResponseEbayHits) SetConditionNil() {
	o.Condition.Set(nil)
}

// UnsetCondition ensures that no value is present for Condition, not even an explicit nil
func (o *CreateMagicScanResponseEbayHits) UnsetCondition() {
	o.Condition.Unset()
}

// GetCategoryId returns the CategoryId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateMagicScanResponseEbayHits) GetCategoryId() string {
	if o == nil || o.CategoryId.Get() == nil {
		var ret string
		return ret
	}
	return *o.CategoryId.Get()
}

// GetCategoryIdOk returns a tuple with the CategoryId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateMagicScanResponseEbayHits) GetCategoryIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.CategoryId.Get(), o.CategoryId.IsSet()
}

// HasCategoryId returns a boolean if a field has been set.
func (o *CreateMagicScanResponseEbayHits) HasCategoryId() bool {
	if o != nil && o.CategoryId.IsSet() {
		return true
	}

	return false
}

// SetCategoryId gets a reference to the given NullableString and assigns it to the CategoryId field.
func (o *CreateMagicScanResponseEbayHits) SetCategoryId(v string) {
	o.CategoryId.Set(&v)
}
// SetCategoryIdNil sets the value for CategoryId to be an explicit nil
func (o *CreateMagicScanResponseEbayHits) SetCategoryIdNil() {
	o.CategoryId.Set(nil)
}

// UnsetCategoryId ensures that no value is present for CategoryId, not even an explicit nil
func (o *CreateMagicScanResponseEbayHits) UnsetCategoryId() {
	o.CategoryId.Unset()
}

// GetCategoryPath returns the CategoryPath field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateMagicScanResponseEbayHits) GetCategoryPath() string {
	if o == nil || o.CategoryPath.Get() == nil {
		var ret string
		return ret
	}
	return *o.CategoryPath.Get()
}

// GetCategoryPathOk returns a tuple with the CategoryPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateMagicScanResponseEbayHits) GetCategoryPathOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.CategoryPath.Get(), o.CategoryPath.IsSet()
}

// HasCategoryPath returns a boolean if a field has been set.
func (o *CreateMagicScanResponseEbayHits) HasCategoryPath() bool {
	if o != nil && o.CategoryPath.IsSet() {
		return true
	}

	return false
}

// SetCategoryPath gets a reference to the given NullableString and assigns it to the CategoryPath field.
func (o *CreateMagicScanResponseEbayHits) SetCategoryPath(v string) {
	o.CategoryPath.Set(&v)
}
// SetCategoryPathNil sets the value for CategoryPath to be an explicit nil
func (o *CreateMagicScanResponseEbayHits) SetCategoryPathNil() {
	o.CategoryPath.Set(nil)
}

// UnsetCategoryPath ensures that no value is present for CategoryPath, not even an explicit nil
func (o *CreateMagicScanResponseEbayHits) UnsetCategoryPath() {
	o.CategoryPath.Unset()
}

// GetItemUrl returns the ItemUrl field value
func (o *CreateMagicScanResponseEbayHits) GetItemUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ItemUrl
}

// GetItemUrlOk returns a tuple with the ItemUrl field value
// and a boolean to check if the value has been set.
func (o *CreateMagicScanResponseEbayHits) GetItemUrlOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ItemUrl, true
}

// SetItemUrl sets field value
func (o *CreateMagicScanResponseEbayHits) SetItemUrl(v string) {
	o.ItemUrl = v
}

// GetThumbnailUrl returns the ThumbnailUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateMagicScanResponseEbayHits) GetThumbnailUrl() string {
	if o == nil || o.ThumbnailUrl.Get() == nil {
		var ret string
		return ret
	}
	return *o.ThumbnailUrl.Get()
}

// GetThumbnailUrlOk returns a tuple with the ThumbnailUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateMagicScanResponseEbayHits) GetThumbnailUrlOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.ThumbnailUrl.Get(), o.ThumbnailUrl.IsSet()
}

// HasThumbnailUrl returns a boolean if a field has been set.
func (o *CreateMagicScanResponseEbayHits) HasThumbnailUrl() bool {
	if o != nil && o.ThumbnailUrl.IsSet() {
		return true
	}

	return false
}

// SetThumbnailUrl gets a reference to the given NullableString and assigns it to the ThumbnailUrl field.
func (o *CreateMagicScanResponseEbayHits) SetThumbnailUrl(v string) {
	o.ThumbnailUrl.Set(&v)
}
// SetThumbnailUrlNil sets the value for ThumbnailUrl to be an explicit nil
func (o *CreateMagicScanResponseEbayHits) SetThumbnailUrlNil() {
	o.ThumbnailUrl.Set(nil)
}

// UnsetThumbnailUrl ensures that no value is present for ThumbnailUrl, not even an explicit nil
func (o *CreateMagicScanResponseEbayHits) UnsetThumbnailUrl() {
	o.ThumbnailUrl.Unset()
}

// GetAspects returns the Aspects field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateMagicScanResponseEbayHits) GetAspects() map[string]interface{} {
	if o == nil  {
		var ret map[string]interface{}
		return ret
	}
	return o.Aspects
}

// GetAspectsOk returns a tuple with the Aspects field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateMagicScanResponseEbayHits) GetAspectsOk() (map[string]interface{}, bool) {
	if o == nil || o.Aspects == nil {
		return nil, false
	}
	return o.Aspects, true
}

// HasAspects returns a boolean if a field has been set.
func (o *CreateMagicScanResponseEbayHits) HasAspects() bool {
	if o != nil && o.Aspects != nil {
		return true
	}

	return false
}

// SetAspects gets a reference to the given map[string]interface{} and assigns it to the Aspects field.
func (o *CreateMagicScanResponseEbayHits) SetAspects(v map[string]interface{}) {
	o.Aspects = v
}

func (o CreateMagicScanResponseEbayHits) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["itemId"] = o.ItemId
	}
	if o.LegacyItemId.IsSet() {
		toSerialize["legacyItemId"] = o.LegacyItemId.Get()
	}
	if true {
		toSerialize["title"] = o.Title
	}
	if o.Brand.IsSet() {
		toSerialize["brand"] = o.Brand.Get()
	}
	if o.PriceCents.IsSet() {
		toSerialize["priceCents"] = o.PriceCents.Get()
	}
	if o.Currency.IsSet() {
		toSerialize["currency"] = o.Currency.Get()
	}
	if o.Condition.IsSet() {
		toSerialize["condition"] = o.Condition.Get()
	}
	if o.CategoryId.IsSet() {
		toSerialize["categoryId"] = o.CategoryId.Get()
	}
	if o.CategoryPath.IsSet() {
		toSerialize["categoryPath"] = o.CategoryPath.Get()
	}
	if true {
		toSerialize["itemUrl"] = o.ItemUrl
	}
	if o.ThumbnailUrl.IsSet() {
		toSerialize["thumbnailUrl"] = o.ThumbnailUrl.Get()
	}
	if o.Aspects != nil {
		toSerialize["aspects"] = o.Aspects
	}
	return json.Marshal(toSerialize)
}

type NullableCreateMagicScanResponseEbayHits struct {
	value *CreateMagicScanResponseEbayHits
	isSet bool
}

func (v NullableCreateMagicScanResponseEbayHits) Get() *CreateMagicScanResponseEbayHits {
	return v.value
}

func (v *NullableCreateMagicScanResponseEbayHits) Set(val *CreateMagicScanResponseEbayHits) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateMagicScanResponseEbayHits) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateMagicScanResponseEbayHits) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateMagicScanResponseEbayHits(val *CreateMagicScanResponseEbayHits) *NullableCreateMagicScanResponseEbayHits {
	return &NullableCreateMagicScanResponseEbayHits{value: val, isSet: true}
}

func (v NullableCreateMagicScanResponseEbayHits) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateMagicScanResponseEbayHits) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


