/*
Crossly Buyer API

The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crossly_buyer

import (
	"encoding/json"
)

// CreateBuyerIdentifyResponseHud struct for CreateBuyerIdentifyResponseHud
type CreateBuyerIdentifyResponseHud struct {
	Headline string `json:"headline"`
	Subline NullableString `json:"subline,omitempty"`
	Facts []CreateBuyerIdentifyResponseHudFacts `json:"facts"`
	Action CreateBuyerIdentifyResponseHudAction `json:"action"`
	// `win` earned a saving, `info` found something, `none` found nothing.
	Tone string `json:"tone"`
	// Image for the lens card, when there is a match worth showing.
	ImageUrl NullableString `json:"imageUrl,omitempty"`
}

// NewCreateBuyerIdentifyResponseHud instantiates a new CreateBuyerIdentifyResponseHud object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateBuyerIdentifyResponseHud(headline string, facts []CreateBuyerIdentifyResponseHudFacts, action CreateBuyerIdentifyResponseHudAction, tone string) *CreateBuyerIdentifyResponseHud {
	this := CreateBuyerIdentifyResponseHud{}
	this.Headline = headline
	this.Facts = facts
	this.Action = action
	this.Tone = tone
	return &this
}

// NewCreateBuyerIdentifyResponseHudWithDefaults instantiates a new CreateBuyerIdentifyResponseHud object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateBuyerIdentifyResponseHudWithDefaults() *CreateBuyerIdentifyResponseHud {
	this := CreateBuyerIdentifyResponseHud{}
	return &this
}

// GetHeadline returns the Headline field value
func (o *CreateBuyerIdentifyResponseHud) GetHeadline() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Headline
}

// GetHeadlineOk returns a tuple with the Headline field value
// and a boolean to check if the value has been set.
func (o *CreateBuyerIdentifyResponseHud) GetHeadlineOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Headline, true
}

// SetHeadline sets field value
func (o *CreateBuyerIdentifyResponseHud) SetHeadline(v string) {
	o.Headline = v
}

// GetSubline returns the Subline field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateBuyerIdentifyResponseHud) GetSubline() string {
	if o == nil || o.Subline.Get() == nil {
		var ret string
		return ret
	}
	return *o.Subline.Get()
}

// GetSublineOk returns a tuple with the Subline field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateBuyerIdentifyResponseHud) GetSublineOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Subline.Get(), o.Subline.IsSet()
}

// HasSubline returns a boolean if a field has been set.
func (o *CreateBuyerIdentifyResponseHud) HasSubline() bool {
	if o != nil && o.Subline.IsSet() {
		return true
	}

	return false
}

// SetSubline gets a reference to the given NullableString and assigns it to the Subline field.
func (o *CreateBuyerIdentifyResponseHud) SetSubline(v string) {
	o.Subline.Set(&v)
}
// SetSublineNil sets the value for Subline to be an explicit nil
func (o *CreateBuyerIdentifyResponseHud) SetSublineNil() {
	o.Subline.Set(nil)
}

// UnsetSubline ensures that no value is present for Subline, not even an explicit nil
func (o *CreateBuyerIdentifyResponseHud) UnsetSubline() {
	o.Subline.Unset()
}

// GetFacts returns the Facts field value
func (o *CreateBuyerIdentifyResponseHud) GetFacts() []CreateBuyerIdentifyResponseHudFacts {
	if o == nil {
		var ret []CreateBuyerIdentifyResponseHudFacts
		return ret
	}

	return o.Facts
}

// GetFactsOk returns a tuple with the Facts field value
// and a boolean to check if the value has been set.
func (o *CreateBuyerIdentifyResponseHud) GetFactsOk() ([]CreateBuyerIdentifyResponseHudFacts, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Facts, true
}

// SetFacts sets field value
func (o *CreateBuyerIdentifyResponseHud) SetFacts(v []CreateBuyerIdentifyResponseHudFacts) {
	o.Facts = v
}

// GetAction returns the Action field value
func (o *CreateBuyerIdentifyResponseHud) GetAction() CreateBuyerIdentifyResponseHudAction {
	if o == nil {
		var ret CreateBuyerIdentifyResponseHudAction
		return ret
	}

	return o.Action
}

// GetActionOk returns a tuple with the Action field value
// and a boolean to check if the value has been set.
func (o *CreateBuyerIdentifyResponseHud) GetActionOk() (*CreateBuyerIdentifyResponseHudAction, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Action, true
}

// SetAction sets field value
func (o *CreateBuyerIdentifyResponseHud) SetAction(v CreateBuyerIdentifyResponseHudAction) {
	o.Action = v
}

// GetTone returns the Tone field value
func (o *CreateBuyerIdentifyResponseHud) GetTone() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Tone
}

// GetToneOk returns a tuple with the Tone field value
// and a boolean to check if the value has been set.
func (o *CreateBuyerIdentifyResponseHud) GetToneOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Tone, true
}

// SetTone sets field value
func (o *CreateBuyerIdentifyResponseHud) SetTone(v string) {
	o.Tone = v
}

// GetImageUrl returns the ImageUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateBuyerIdentifyResponseHud) GetImageUrl() string {
	if o == nil || o.ImageUrl.Get() == nil {
		var ret string
		return ret
	}
	return *o.ImageUrl.Get()
}

// GetImageUrlOk returns a tuple with the ImageUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateBuyerIdentifyResponseHud) GetImageUrlOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.ImageUrl.Get(), o.ImageUrl.IsSet()
}

// HasImageUrl returns a boolean if a field has been set.
func (o *CreateBuyerIdentifyResponseHud) HasImageUrl() bool {
	if o != nil && o.ImageUrl.IsSet() {
		return true
	}

	return false
}

// SetImageUrl gets a reference to the given NullableString and assigns it to the ImageUrl field.
func (o *CreateBuyerIdentifyResponseHud) SetImageUrl(v string) {
	o.ImageUrl.Set(&v)
}
// SetImageUrlNil sets the value for ImageUrl to be an explicit nil
func (o *CreateBuyerIdentifyResponseHud) SetImageUrlNil() {
	o.ImageUrl.Set(nil)
}

// UnsetImageUrl ensures that no value is present for ImageUrl, not even an explicit nil
func (o *CreateBuyerIdentifyResponseHud) UnsetImageUrl() {
	o.ImageUrl.Unset()
}

func (o CreateBuyerIdentifyResponseHud) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["headline"] = o.Headline
	}
	if o.Subline.IsSet() {
		toSerialize["subline"] = o.Subline.Get()
	}
	if true {
		toSerialize["facts"] = o.Facts
	}
	if true {
		toSerialize["action"] = o.Action
	}
	if true {
		toSerialize["tone"] = o.Tone
	}
	if o.ImageUrl.IsSet() {
		toSerialize["imageUrl"] = o.ImageUrl.Get()
	}
	return json.Marshal(toSerialize)
}

type NullableCreateBuyerIdentifyResponseHud struct {
	value *CreateBuyerIdentifyResponseHud
	isSet bool
}

func (v NullableCreateBuyerIdentifyResponseHud) Get() *CreateBuyerIdentifyResponseHud {
	return v.value
}

func (v *NullableCreateBuyerIdentifyResponseHud) Set(val *CreateBuyerIdentifyResponseHud) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateBuyerIdentifyResponseHud) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateBuyerIdentifyResponseHud) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateBuyerIdentifyResponseHud(val *CreateBuyerIdentifyResponseHud) *NullableCreateBuyerIdentifyResponseHud {
	return &NullableCreateBuyerIdentifyResponseHud{value: val, isSet: true}
}

func (v NullableCreateBuyerIdentifyResponseHud) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateBuyerIdentifyResponseHud) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


