/*
Crossly Buyer API

The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crossly_buyer

import (
	"encoding/json"
	"time"
)

// GetInboxCannedResponsResponseCannedResponses struct for GetInboxCannedResponsResponseCannedResponses
type GetInboxCannedResponsResponseCannedResponses struct {
	Id string `json:"id"`
	Name string `json:"name"`
	CreatedAt time.Time `json:"createdAt"`
	UserId string `json:"userId"`
	Title NullableString `json:"title,omitempty"`
	Surface string `json:"surface"`
	Body string `json:"body"`
}

// NewGetInboxCannedResponsResponseCannedResponses instantiates a new GetInboxCannedResponsResponseCannedResponses object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetInboxCannedResponsResponseCannedResponses(id string, name string, createdAt time.Time, userId string, surface string, body string) *GetInboxCannedResponsResponseCannedResponses {
	this := GetInboxCannedResponsResponseCannedResponses{}
	this.Id = id
	this.Name = name
	this.CreatedAt = createdAt
	this.UserId = userId
	this.Surface = surface
	this.Body = body
	return &this
}

// NewGetInboxCannedResponsResponseCannedResponsesWithDefaults instantiates a new GetInboxCannedResponsResponseCannedResponses object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetInboxCannedResponsResponseCannedResponsesWithDefaults() *GetInboxCannedResponsResponseCannedResponses {
	this := GetInboxCannedResponsResponseCannedResponses{}
	return &this
}

// GetId returns the Id field value
func (o *GetInboxCannedResponsResponseCannedResponses) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *GetInboxCannedResponsResponseCannedResponses) GetIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *GetInboxCannedResponsResponseCannedResponses) SetId(v string) {
	o.Id = v
}

// GetName returns the Name field value
func (o *GetInboxCannedResponsResponseCannedResponses) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *GetInboxCannedResponsResponseCannedResponses) GetNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *GetInboxCannedResponsResponseCannedResponses) SetName(v string) {
	o.Name = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *GetInboxCannedResponsResponseCannedResponses) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *GetInboxCannedResponsResponseCannedResponses) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *GetInboxCannedResponsResponseCannedResponses) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUserId returns the UserId field value
func (o *GetInboxCannedResponsResponseCannedResponses) GetUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *GetInboxCannedResponsResponseCannedResponses) GetUserIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *GetInboxCannedResponsResponseCannedResponses) SetUserId(v string) {
	o.UserId = v
}

// GetTitle returns the Title field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetInboxCannedResponsResponseCannedResponses) GetTitle() string {
	if o == nil || o.Title.Get() == nil {
		var ret string
		return ret
	}
	return *o.Title.Get()
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetInboxCannedResponsResponseCannedResponses) GetTitleOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Title.Get(), o.Title.IsSet()
}

// HasTitle returns a boolean if a field has been set.
func (o *GetInboxCannedResponsResponseCannedResponses) HasTitle() bool {
	if o != nil && o.Title.IsSet() {
		return true
	}

	return false
}

// SetTitle gets a reference to the given NullableString and assigns it to the Title field.
func (o *GetInboxCannedResponsResponseCannedResponses) SetTitle(v string) {
	o.Title.Set(&v)
}
// SetTitleNil sets the value for Title to be an explicit nil
func (o *GetInboxCannedResponsResponseCannedResponses) SetTitleNil() {
	o.Title.Set(nil)
}

// UnsetTitle ensures that no value is present for Title, not even an explicit nil
func (o *GetInboxCannedResponsResponseCannedResponses) UnsetTitle() {
	o.Title.Unset()
}

// GetSurface returns the Surface field value
func (o *GetInboxCannedResponsResponseCannedResponses) GetSurface() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Surface
}

// GetSurfaceOk returns a tuple with the Surface field value
// and a boolean to check if the value has been set.
func (o *GetInboxCannedResponsResponseCannedResponses) GetSurfaceOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Surface, true
}

// SetSurface sets field value
func (o *GetInboxCannedResponsResponseCannedResponses) SetSurface(v string) {
	o.Surface = v
}

// GetBody returns the Body field value
func (o *GetInboxCannedResponsResponseCannedResponses) GetBody() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Body
}

// GetBodyOk returns a tuple with the Body field value
// and a boolean to check if the value has been set.
func (o *GetInboxCannedResponsResponseCannedResponses) GetBodyOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Body, true
}

// SetBody sets field value
func (o *GetInboxCannedResponsResponseCannedResponses) SetBody(v string) {
	o.Body = v
}

func (o GetInboxCannedResponsResponseCannedResponses) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if true {
		toSerialize["userId"] = o.UserId
	}
	if o.Title.IsSet() {
		toSerialize["title"] = o.Title.Get()
	}
	if true {
		toSerialize["surface"] = o.Surface
	}
	if true {
		toSerialize["body"] = o.Body
	}
	return json.Marshal(toSerialize)
}

type NullableGetInboxCannedResponsResponseCannedResponses struct {
	value *GetInboxCannedResponsResponseCannedResponses
	isSet bool
}

func (v NullableGetInboxCannedResponsResponseCannedResponses) Get() *GetInboxCannedResponsResponseCannedResponses {
	return v.value
}

func (v *NullableGetInboxCannedResponsResponseCannedResponses) Set(val *GetInboxCannedResponsResponseCannedResponses) {
	v.value = val
	v.isSet = true
}

func (v NullableGetInboxCannedResponsResponseCannedResponses) IsSet() bool {
	return v.isSet
}

func (v *NullableGetInboxCannedResponsResponseCannedResponses) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetInboxCannedResponsResponseCannedResponses(val *GetInboxCannedResponsResponseCannedResponses) *NullableGetInboxCannedResponsResponseCannedResponses {
	return &NullableGetInboxCannedResponsResponseCannedResponses{value: val, isSet: true}
}

func (v NullableGetInboxCannedResponsResponseCannedResponses) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetInboxCannedResponsResponseCannedResponses) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


