/*
Crossly Buyer API

The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crossly_buyer

import (
	"encoding/json"
)

// GetAnalyticTodayResponseStreak struct for GetAnalyticTodayResponseStreak
type GetAnalyticTodayResponseStreak struct {
	Current float32 `json:"current"`
	Longest float32 `json:"longest"`
	LastActiveDate NullableString `json:"lastActiveDate,omitempty"`
}

// NewGetAnalyticTodayResponseStreak instantiates a new GetAnalyticTodayResponseStreak object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAnalyticTodayResponseStreak(current float32, longest float32) *GetAnalyticTodayResponseStreak {
	this := GetAnalyticTodayResponseStreak{}
	this.Current = current
	this.Longest = longest
	return &this
}

// NewGetAnalyticTodayResponseStreakWithDefaults instantiates a new GetAnalyticTodayResponseStreak object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAnalyticTodayResponseStreakWithDefaults() *GetAnalyticTodayResponseStreak {
	this := GetAnalyticTodayResponseStreak{}
	return &this
}

// GetCurrent returns the Current field value
func (o *GetAnalyticTodayResponseStreak) GetCurrent() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Current
}

// GetCurrentOk returns a tuple with the Current field value
// and a boolean to check if the value has been set.
func (o *GetAnalyticTodayResponseStreak) GetCurrentOk() (*float32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Current, true
}

// SetCurrent sets field value
func (o *GetAnalyticTodayResponseStreak) SetCurrent(v float32) {
	o.Current = v
}

// GetLongest returns the Longest field value
func (o *GetAnalyticTodayResponseStreak) GetLongest() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Longest
}

// GetLongestOk returns a tuple with the Longest field value
// and a boolean to check if the value has been set.
func (o *GetAnalyticTodayResponseStreak) GetLongestOk() (*float32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Longest, true
}

// SetLongest sets field value
func (o *GetAnalyticTodayResponseStreak) SetLongest(v float32) {
	o.Longest = v
}

// GetLastActiveDate returns the LastActiveDate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetAnalyticTodayResponseStreak) GetLastActiveDate() string {
	if o == nil || o.LastActiveDate.Get() == nil {
		var ret string
		return ret
	}
	return *o.LastActiveDate.Get()
}

// GetLastActiveDateOk returns a tuple with the LastActiveDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetAnalyticTodayResponseStreak) GetLastActiveDateOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.LastActiveDate.Get(), o.LastActiveDate.IsSet()
}

// HasLastActiveDate returns a boolean if a field has been set.
func (o *GetAnalyticTodayResponseStreak) HasLastActiveDate() bool {
	if o != nil && o.LastActiveDate.IsSet() {
		return true
	}

	return false
}

// SetLastActiveDate gets a reference to the given NullableString and assigns it to the LastActiveDate field.
func (o *GetAnalyticTodayResponseStreak) SetLastActiveDate(v string) {
	o.LastActiveDate.Set(&v)
}
// SetLastActiveDateNil sets the value for LastActiveDate to be an explicit nil
func (o *GetAnalyticTodayResponseStreak) SetLastActiveDateNil() {
	o.LastActiveDate.Set(nil)
}

// UnsetLastActiveDate ensures that no value is present for LastActiveDate, not even an explicit nil
func (o *GetAnalyticTodayResponseStreak) UnsetLastActiveDate() {
	o.LastActiveDate.Unset()
}

func (o GetAnalyticTodayResponseStreak) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["current"] = o.Current
	}
	if true {
		toSerialize["longest"] = o.Longest
	}
	if o.LastActiveDate.IsSet() {
		toSerialize["lastActiveDate"] = o.LastActiveDate.Get()
	}
	return json.Marshal(toSerialize)
}

type NullableGetAnalyticTodayResponseStreak struct {
	value *GetAnalyticTodayResponseStreak
	isSet bool
}

func (v NullableGetAnalyticTodayResponseStreak) Get() *GetAnalyticTodayResponseStreak {
	return v.value
}

func (v *NullableGetAnalyticTodayResponseStreak) Set(val *GetAnalyticTodayResponseStreak) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAnalyticTodayResponseStreak) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAnalyticTodayResponseStreak) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAnalyticTodayResponseStreak(val *GetAnalyticTodayResponseStreak) *NullableGetAnalyticTodayResponseStreak {
	return &NullableGetAnalyticTodayResponseStreak{value: val, isSet: true}
}

func (v NullableGetAnalyticTodayResponseStreak) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAnalyticTodayResponseStreak) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


