/*
Crossly Buyer API

The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crossly_buyer

import (
	"encoding/json"
)

// GetAnalyticDashboardResponseSalesByPlatform struct for GetAnalyticDashboardResponseSalesByPlatform
type GetAnalyticDashboardResponseSalesByPlatform struct {
	Platform string `json:"platform"`
	Count string `json:"count"`
	Revenue float32 `json:"revenue"`
}

// NewGetAnalyticDashboardResponseSalesByPlatform instantiates a new GetAnalyticDashboardResponseSalesByPlatform object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetAnalyticDashboardResponseSalesByPlatform(platform string, count string, revenue float32) *GetAnalyticDashboardResponseSalesByPlatform {
	this := GetAnalyticDashboardResponseSalesByPlatform{}
	this.Platform = platform
	this.Count = count
	this.Revenue = revenue
	return &this
}

// NewGetAnalyticDashboardResponseSalesByPlatformWithDefaults instantiates a new GetAnalyticDashboardResponseSalesByPlatform object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetAnalyticDashboardResponseSalesByPlatformWithDefaults() *GetAnalyticDashboardResponseSalesByPlatform {
	this := GetAnalyticDashboardResponseSalesByPlatform{}
	return &this
}

// GetPlatform returns the Platform field value
func (o *GetAnalyticDashboardResponseSalesByPlatform) GetPlatform() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Platform
}

// GetPlatformOk returns a tuple with the Platform field value
// and a boolean to check if the value has been set.
func (o *GetAnalyticDashboardResponseSalesByPlatform) GetPlatformOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Platform, true
}

// SetPlatform sets field value
func (o *GetAnalyticDashboardResponseSalesByPlatform) SetPlatform(v string) {
	o.Platform = v
}

// GetCount returns the Count field value
func (o *GetAnalyticDashboardResponseSalesByPlatform) GetCount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *GetAnalyticDashboardResponseSalesByPlatform) GetCountOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *GetAnalyticDashboardResponseSalesByPlatform) SetCount(v string) {
	o.Count = v
}

// GetRevenue returns the Revenue field value
func (o *GetAnalyticDashboardResponseSalesByPlatform) GetRevenue() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Revenue
}

// GetRevenueOk returns a tuple with the Revenue field value
// and a boolean to check if the value has been set.
func (o *GetAnalyticDashboardResponseSalesByPlatform) GetRevenueOk() (*float32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Revenue, true
}

// SetRevenue sets field value
func (o *GetAnalyticDashboardResponseSalesByPlatform) SetRevenue(v float32) {
	o.Revenue = v
}

func (o GetAnalyticDashboardResponseSalesByPlatform) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["platform"] = o.Platform
	}
	if true {
		toSerialize["count"] = o.Count
	}
	if true {
		toSerialize["revenue"] = o.Revenue
	}
	return json.Marshal(toSerialize)
}

type NullableGetAnalyticDashboardResponseSalesByPlatform struct {
	value *GetAnalyticDashboardResponseSalesByPlatform
	isSet bool
}

func (v NullableGetAnalyticDashboardResponseSalesByPlatform) Get() *GetAnalyticDashboardResponseSalesByPlatform {
	return v.value
}

func (v *NullableGetAnalyticDashboardResponseSalesByPlatform) Set(val *GetAnalyticDashboardResponseSalesByPlatform) {
	v.value = val
	v.isSet = true
}

func (v NullableGetAnalyticDashboardResponseSalesByPlatform) IsSet() bool {
	return v.isSet
}

func (v *NullableGetAnalyticDashboardResponseSalesByPlatform) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetAnalyticDashboardResponseSalesByPlatform(val *GetAnalyticDashboardResponseSalesByPlatform) *NullableGetAnalyticDashboardResponseSalesByPlatform {
	return &NullableGetAnalyticDashboardResponseSalesByPlatform{value: val, isSet: true}
}

func (v NullableGetAnalyticDashboardResponseSalesByPlatform) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetAnalyticDashboardResponseSalesByPlatform) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


