/*
Crossly Buyer API

The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crossly_buyer

import (
	"encoding/json"
)

// GetTaxonomyCategoryResponse struct for GetTaxonomyCategoryResponse
type GetTaxonomyCategoryResponse struct {
	Categories []GetTaxonomyCategoryResponseCategories `json:"categories"`
}

// NewGetTaxonomyCategoryResponse instantiates a new GetTaxonomyCategoryResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetTaxonomyCategoryResponse(categories []GetTaxonomyCategoryResponseCategories) *GetTaxonomyCategoryResponse {
	this := GetTaxonomyCategoryResponse{}
	this.Categories = categories
	return &this
}

// NewGetTaxonomyCategoryResponseWithDefaults instantiates a new GetTaxonomyCategoryResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetTaxonomyCategoryResponseWithDefaults() *GetTaxonomyCategoryResponse {
	this := GetTaxonomyCategoryResponse{}
	return &this
}

// GetCategories returns the Categories field value
func (o *GetTaxonomyCategoryResponse) GetCategories() []GetTaxonomyCategoryResponseCategories {
	if o == nil {
		var ret []GetTaxonomyCategoryResponseCategories
		return ret
	}

	return o.Categories
}

// GetCategoriesOk returns a tuple with the Categories field value
// and a boolean to check if the value has been set.
func (o *GetTaxonomyCategoryResponse) GetCategoriesOk() ([]GetTaxonomyCategoryResponseCategories, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Categories, true
}

// SetCategories sets field value
func (o *GetTaxonomyCategoryResponse) SetCategories(v []GetTaxonomyCategoryResponseCategories) {
	o.Categories = v
}

func (o GetTaxonomyCategoryResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["categories"] = o.Categories
	}
	return json.Marshal(toSerialize)
}

type NullableGetTaxonomyCategoryResponse struct {
	value *GetTaxonomyCategoryResponse
	isSet bool
}

func (v NullableGetTaxonomyCategoryResponse) Get() *GetTaxonomyCategoryResponse {
	return v.value
}

func (v *NullableGetTaxonomyCategoryResponse) Set(val *GetTaxonomyCategoryResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetTaxonomyCategoryResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetTaxonomyCategoryResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetTaxonomyCategoryResponse(val *GetTaxonomyCategoryResponse) *NullableGetTaxonomyCategoryResponse {
	return &NullableGetTaxonomyCategoryResponse{value: val, isSet: true}
}

func (v NullableGetTaxonomyCategoryResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetTaxonomyCategoryResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


