/*
Crossly Buyer API

The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crossly_buyer

import (
	"encoding/json"
)

// GetTaxonomyCategoryAspectResponse struct for GetTaxonomyCategoryAspectResponse
type GetTaxonomyCategoryAspectResponse struct {
	Aspects []GetTaxonomyCategoryAspectResponseAspects `json:"aspects"`
}

// NewGetTaxonomyCategoryAspectResponse instantiates a new GetTaxonomyCategoryAspectResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetTaxonomyCategoryAspectResponse(aspects []GetTaxonomyCategoryAspectResponseAspects) *GetTaxonomyCategoryAspectResponse {
	this := GetTaxonomyCategoryAspectResponse{}
	this.Aspects = aspects
	return &this
}

// NewGetTaxonomyCategoryAspectResponseWithDefaults instantiates a new GetTaxonomyCategoryAspectResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetTaxonomyCategoryAspectResponseWithDefaults() *GetTaxonomyCategoryAspectResponse {
	this := GetTaxonomyCategoryAspectResponse{}
	return &this
}

// GetAspects returns the Aspects field value
func (o *GetTaxonomyCategoryAspectResponse) GetAspects() []GetTaxonomyCategoryAspectResponseAspects {
	if o == nil {
		var ret []GetTaxonomyCategoryAspectResponseAspects
		return ret
	}

	return o.Aspects
}

// GetAspectsOk returns a tuple with the Aspects field value
// and a boolean to check if the value has been set.
func (o *GetTaxonomyCategoryAspectResponse) GetAspectsOk() ([]GetTaxonomyCategoryAspectResponseAspects, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Aspects, true
}

// SetAspects sets field value
func (o *GetTaxonomyCategoryAspectResponse) SetAspects(v []GetTaxonomyCategoryAspectResponseAspects) {
	o.Aspects = v
}

func (o GetTaxonomyCategoryAspectResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["aspects"] = o.Aspects
	}
	return json.Marshal(toSerialize)
}

type NullableGetTaxonomyCategoryAspectResponse struct {
	value *GetTaxonomyCategoryAspectResponse
	isSet bool
}

func (v NullableGetTaxonomyCategoryAspectResponse) Get() *GetTaxonomyCategoryAspectResponse {
	return v.value
}

func (v *NullableGetTaxonomyCategoryAspectResponse) Set(val *GetTaxonomyCategoryAspectResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetTaxonomyCategoryAspectResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetTaxonomyCategoryAspectResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetTaxonomyCategoryAspectResponse(val *GetTaxonomyCategoryAspectResponse) *NullableGetTaxonomyCategoryAspectResponse {
	return &NullableGetTaxonomyCategoryAspectResponse{value: val, isSet: true}
}

func (v NullableGetTaxonomyCategoryAspectResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetTaxonomyCategoryAspectResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


