/*
Crossly Buyer API

The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crossly_buyer

import (
	"encoding/json"
)

// GetOauthInitResponseOneOf2 struct for GetOauthInitResponseOneOf2
type GetOauthInitResponseOneOf2 struct {
	Url string `json:"url"`
	OneShot bool `json:"oneShot"`
}

// NewGetOauthInitResponseOneOf2 instantiates a new GetOauthInitResponseOneOf2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetOauthInitResponseOneOf2(url string, oneShot bool) *GetOauthInitResponseOneOf2 {
	this := GetOauthInitResponseOneOf2{}
	this.Url = url
	this.OneShot = oneShot
	return &this
}

// NewGetOauthInitResponseOneOf2WithDefaults instantiates a new GetOauthInitResponseOneOf2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetOauthInitResponseOneOf2WithDefaults() *GetOauthInitResponseOneOf2 {
	this := GetOauthInitResponseOneOf2{}
	return &this
}

// GetUrl returns the Url field value
func (o *GetOauthInitResponseOneOf2) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *GetOauthInitResponseOneOf2) GetUrlOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *GetOauthInitResponseOneOf2) SetUrl(v string) {
	o.Url = v
}

// GetOneShot returns the OneShot field value
func (o *GetOauthInitResponseOneOf2) GetOneShot() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.OneShot
}

// GetOneShotOk returns a tuple with the OneShot field value
// and a boolean to check if the value has been set.
func (o *GetOauthInitResponseOneOf2) GetOneShotOk() (*bool, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.OneShot, true
}

// SetOneShot sets field value
func (o *GetOauthInitResponseOneOf2) SetOneShot(v bool) {
	o.OneShot = v
}

func (o GetOauthInitResponseOneOf2) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["url"] = o.Url
	}
	if true {
		toSerialize["oneShot"] = o.OneShot
	}
	return json.Marshal(toSerialize)
}

type NullableGetOauthInitResponseOneOf2 struct {
	value *GetOauthInitResponseOneOf2
	isSet bool
}

func (v NullableGetOauthInitResponseOneOf2) Get() *GetOauthInitResponseOneOf2 {
	return v.value
}

func (v *NullableGetOauthInitResponseOneOf2) Set(val *GetOauthInitResponseOneOf2) {
	v.value = val
	v.isSet = true
}

func (v NullableGetOauthInitResponseOneOf2) IsSet() bool {
	return v.isSet
}

func (v *NullableGetOauthInitResponseOneOf2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetOauthInitResponseOneOf2(val *GetOauthInitResponseOneOf2) *NullableGetOauthInitResponseOneOf2 {
	return &NullableGetOauthInitResponseOneOf2{value: val, isSet: true}
}

func (v NullableGetOauthInitResponseOneOf2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetOauthInitResponseOneOf2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


