/*
Crossly Buyer API

The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crossly_buyer

import (
	"encoding/json"
	"time"
)

// ListSourcingDemandMineItem struct for ListSourcingDemandMineItem
type ListSourcingDemandMineItem struct {
	IdentifierValue string `json:"identifierValue"`
	// How many distinct shoppers looked, in the window.
	Lookers float32 `json:"lookers"`
	// How many of those looks Crossly could not answer at all.
	Misses float32 `json:"misses"`
	// What the retailers were charging, median of what Scout saw.
	MedianRetailCents NullableFloat32 `json:"medianRetailCents,omitempty"`
	// 'in_stock' — it is in their inventory. 'sold_before' — they have sold one.
	Relation string `json:"relation"`
	// Their own row, for the link.
	InventoryItemId NullableString `json:"inventoryItemId,omitempty"`
	Title NullableString `json:"title,omitempty"`
	// What they got for it last time, when they have sold one.
	LastSoldCents NullableFloat32 `json:"lastSoldCents,omitempty"`
	LastSoldAt NullableTime `json:"lastSoldAt,omitempty"`
}

// NewListSourcingDemandMineItem instantiates a new ListSourcingDemandMineItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListSourcingDemandMineItem(identifierValue string, lookers float32, misses float32, relation string) *ListSourcingDemandMineItem {
	this := ListSourcingDemandMineItem{}
	this.IdentifierValue = identifierValue
	this.Lookers = lookers
	this.Misses = misses
	this.Relation = relation
	return &this
}

// NewListSourcingDemandMineItemWithDefaults instantiates a new ListSourcingDemandMineItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListSourcingDemandMineItemWithDefaults() *ListSourcingDemandMineItem {
	this := ListSourcingDemandMineItem{}
	return &this
}

// GetIdentifierValue returns the IdentifierValue field value
func (o *ListSourcingDemandMineItem) GetIdentifierValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IdentifierValue
}

// GetIdentifierValueOk returns a tuple with the IdentifierValue field value
// and a boolean to check if the value has been set.
func (o *ListSourcingDemandMineItem) GetIdentifierValueOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.IdentifierValue, true
}

// SetIdentifierValue sets field value
func (o *ListSourcingDemandMineItem) SetIdentifierValue(v string) {
	o.IdentifierValue = v
}

// GetLookers returns the Lookers field value
func (o *ListSourcingDemandMineItem) GetLookers() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Lookers
}

// GetLookersOk returns a tuple with the Lookers field value
// and a boolean to check if the value has been set.
func (o *ListSourcingDemandMineItem) GetLookersOk() (*float32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Lookers, true
}

// SetLookers sets field value
func (o *ListSourcingDemandMineItem) SetLookers(v float32) {
	o.Lookers = v
}

// GetMisses returns the Misses field value
func (o *ListSourcingDemandMineItem) GetMisses() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Misses
}

// GetMissesOk returns a tuple with the Misses field value
// and a boolean to check if the value has been set.
func (o *ListSourcingDemandMineItem) GetMissesOk() (*float32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Misses, true
}

// SetMisses sets field value
func (o *ListSourcingDemandMineItem) SetMisses(v float32) {
	o.Misses = v
}

// GetMedianRetailCents returns the MedianRetailCents field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListSourcingDemandMineItem) GetMedianRetailCents() float32 {
	if o == nil || o.MedianRetailCents.Get() == nil {
		var ret float32
		return ret
	}
	return *o.MedianRetailCents.Get()
}

// GetMedianRetailCentsOk returns a tuple with the MedianRetailCents field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListSourcingDemandMineItem) GetMedianRetailCentsOk() (*float32, bool) {
	if o == nil  {
		return nil, false
	}
	return o.MedianRetailCents.Get(), o.MedianRetailCents.IsSet()
}

// HasMedianRetailCents returns a boolean if a field has been set.
func (o *ListSourcingDemandMineItem) HasMedianRetailCents() bool {
	if o != nil && o.MedianRetailCents.IsSet() {
		return true
	}

	return false
}

// SetMedianRetailCents gets a reference to the given NullableFloat32 and assigns it to the MedianRetailCents field.
func (o *ListSourcingDemandMineItem) SetMedianRetailCents(v float32) {
	o.MedianRetailCents.Set(&v)
}
// SetMedianRetailCentsNil sets the value for MedianRetailCents to be an explicit nil
func (o *ListSourcingDemandMineItem) SetMedianRetailCentsNil() {
	o.MedianRetailCents.Set(nil)
}

// UnsetMedianRetailCents ensures that no value is present for MedianRetailCents, not even an explicit nil
func (o *ListSourcingDemandMineItem) UnsetMedianRetailCents() {
	o.MedianRetailCents.Unset()
}

// GetRelation returns the Relation field value
func (o *ListSourcingDemandMineItem) GetRelation() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Relation
}

// GetRelationOk returns a tuple with the Relation field value
// and a boolean to check if the value has been set.
func (o *ListSourcingDemandMineItem) GetRelationOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Relation, true
}

// SetRelation sets field value
func (o *ListSourcingDemandMineItem) SetRelation(v string) {
	o.Relation = v
}

// GetInventoryItemId returns the InventoryItemId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListSourcingDemandMineItem) GetInventoryItemId() string {
	if o == nil || o.InventoryItemId.Get() == nil {
		var ret string
		return ret
	}
	return *o.InventoryItemId.Get()
}

// GetInventoryItemIdOk returns a tuple with the InventoryItemId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListSourcingDemandMineItem) GetInventoryItemIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.InventoryItemId.Get(), o.InventoryItemId.IsSet()
}

// HasInventoryItemId returns a boolean if a field has been set.
func (o *ListSourcingDemandMineItem) HasInventoryItemId() bool {
	if o != nil && o.InventoryItemId.IsSet() {
		return true
	}

	return false
}

// SetInventoryItemId gets a reference to the given NullableString and assigns it to the InventoryItemId field.
func (o *ListSourcingDemandMineItem) SetInventoryItemId(v string) {
	o.InventoryItemId.Set(&v)
}
// SetInventoryItemIdNil sets the value for InventoryItemId to be an explicit nil
func (o *ListSourcingDemandMineItem) SetInventoryItemIdNil() {
	o.InventoryItemId.Set(nil)
}

// UnsetInventoryItemId ensures that no value is present for InventoryItemId, not even an explicit nil
func (o *ListSourcingDemandMineItem) UnsetInventoryItemId() {
	o.InventoryItemId.Unset()
}

// GetTitle returns the Title field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListSourcingDemandMineItem) GetTitle() string {
	if o == nil || o.Title.Get() == nil {
		var ret string
		return ret
	}
	return *o.Title.Get()
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListSourcingDemandMineItem) GetTitleOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Title.Get(), o.Title.IsSet()
}

// HasTitle returns a boolean if a field has been set.
func (o *ListSourcingDemandMineItem) HasTitle() bool {
	if o != nil && o.Title.IsSet() {
		return true
	}

	return false
}

// SetTitle gets a reference to the given NullableString and assigns it to the Title field.
func (o *ListSourcingDemandMineItem) SetTitle(v string) {
	o.Title.Set(&v)
}
// SetTitleNil sets the value for Title to be an explicit nil
func (o *ListSourcingDemandMineItem) SetTitleNil() {
	o.Title.Set(nil)
}

// UnsetTitle ensures that no value is present for Title, not even an explicit nil
func (o *ListSourcingDemandMineItem) UnsetTitle() {
	o.Title.Unset()
}

// GetLastSoldCents returns the LastSoldCents field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListSourcingDemandMineItem) GetLastSoldCents() float32 {
	if o == nil || o.LastSoldCents.Get() == nil {
		var ret float32
		return ret
	}
	return *o.LastSoldCents.Get()
}

// GetLastSoldCentsOk returns a tuple with the LastSoldCents field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListSourcingDemandMineItem) GetLastSoldCentsOk() (*float32, bool) {
	if o == nil  {
		return nil, false
	}
	return o.LastSoldCents.Get(), o.LastSoldCents.IsSet()
}

// HasLastSoldCents returns a boolean if a field has been set.
func (o *ListSourcingDemandMineItem) HasLastSoldCents() bool {
	if o != nil && o.LastSoldCents.IsSet() {
		return true
	}

	return false
}

// SetLastSoldCents gets a reference to the given NullableFloat32 and assigns it to the LastSoldCents field.
func (o *ListSourcingDemandMineItem) SetLastSoldCents(v float32) {
	o.LastSoldCents.Set(&v)
}
// SetLastSoldCentsNil sets the value for LastSoldCents to be an explicit nil
func (o *ListSourcingDemandMineItem) SetLastSoldCentsNil() {
	o.LastSoldCents.Set(nil)
}

// UnsetLastSoldCents ensures that no value is present for LastSoldCents, not even an explicit nil
func (o *ListSourcingDemandMineItem) UnsetLastSoldCents() {
	o.LastSoldCents.Unset()
}

// GetLastSoldAt returns the LastSoldAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ListSourcingDemandMineItem) GetLastSoldAt() time.Time {
	if o == nil || o.LastSoldAt.Get() == nil {
		var ret time.Time
		return ret
	}
	return *o.LastSoldAt.Get()
}

// GetLastSoldAtOk returns a tuple with the LastSoldAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListSourcingDemandMineItem) GetLastSoldAtOk() (*time.Time, bool) {
	if o == nil  {
		return nil, false
	}
	return o.LastSoldAt.Get(), o.LastSoldAt.IsSet()
}

// HasLastSoldAt returns a boolean if a field has been set.
func (o *ListSourcingDemandMineItem) HasLastSoldAt() bool {
	if o != nil && o.LastSoldAt.IsSet() {
		return true
	}

	return false
}

// SetLastSoldAt gets a reference to the given NullableTime and assigns it to the LastSoldAt field.
func (o *ListSourcingDemandMineItem) SetLastSoldAt(v time.Time) {
	o.LastSoldAt.Set(&v)
}
// SetLastSoldAtNil sets the value for LastSoldAt to be an explicit nil
func (o *ListSourcingDemandMineItem) SetLastSoldAtNil() {
	o.LastSoldAt.Set(nil)
}

// UnsetLastSoldAt ensures that no value is present for LastSoldAt, not even an explicit nil
func (o *ListSourcingDemandMineItem) UnsetLastSoldAt() {
	o.LastSoldAt.Unset()
}

func (o ListSourcingDemandMineItem) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["identifierValue"] = o.IdentifierValue
	}
	if true {
		toSerialize["lookers"] = o.Lookers
	}
	if true {
		toSerialize["misses"] = o.Misses
	}
	if o.MedianRetailCents.IsSet() {
		toSerialize["medianRetailCents"] = o.MedianRetailCents.Get()
	}
	if true {
		toSerialize["relation"] = o.Relation
	}
	if o.InventoryItemId.IsSet() {
		toSerialize["inventoryItemId"] = o.InventoryItemId.Get()
	}
	if o.Title.IsSet() {
		toSerialize["title"] = o.Title.Get()
	}
	if o.LastSoldCents.IsSet() {
		toSerialize["lastSoldCents"] = o.LastSoldCents.Get()
	}
	if o.LastSoldAt.IsSet() {
		toSerialize["lastSoldAt"] = o.LastSoldAt.Get()
	}
	return json.Marshal(toSerialize)
}

type NullableListSourcingDemandMineItem struct {
	value *ListSourcingDemandMineItem
	isSet bool
}

func (v NullableListSourcingDemandMineItem) Get() *ListSourcingDemandMineItem {
	return v.value
}

func (v *NullableListSourcingDemandMineItem) Set(val *ListSourcingDemandMineItem) {
	v.value = val
	v.isSet = true
}

func (v NullableListSourcingDemandMineItem) IsSet() bool {
	return v.isSet
}

func (v *NullableListSourcingDemandMineItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListSourcingDemandMineItem(val *ListSourcingDemandMineItem) *NullableListSourcingDemandMineItem {
	return &NullableListSourcingDemandMineItem{value: val, isSet: true}
}

func (v NullableListSourcingDemandMineItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListSourcingDemandMineItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


