/*
Crossly Buyer API

The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crossly_buyer

import (
	"encoding/json"
)

// GetBuyerCatalogListingAvailabilityResponse struct for GetBuyerCatalogListingAvailabilityResponse
type GetBuyerCatalogListingAvailabilityResponse struct {
	Slug string `json:"slug"`
	Available bool `json:"available"`
	QuantityAvailable float32 `json:"quantityAvailable"`
	PriceCents float32 `json:"priceCents"`
	Currency string `json:"currency"`
	Status string `json:"status"`
}

// NewGetBuyerCatalogListingAvailabilityResponse instantiates a new GetBuyerCatalogListingAvailabilityResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetBuyerCatalogListingAvailabilityResponse(slug string, available bool, quantityAvailable float32, priceCents float32, currency string, status string) *GetBuyerCatalogListingAvailabilityResponse {
	this := GetBuyerCatalogListingAvailabilityResponse{}
	this.Slug = slug
	this.Available = available
	this.QuantityAvailable = quantityAvailable
	this.PriceCents = priceCents
	this.Currency = currency
	this.Status = status
	return &this
}

// NewGetBuyerCatalogListingAvailabilityResponseWithDefaults instantiates a new GetBuyerCatalogListingAvailabilityResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetBuyerCatalogListingAvailabilityResponseWithDefaults() *GetBuyerCatalogListingAvailabilityResponse {
	this := GetBuyerCatalogListingAvailabilityResponse{}
	return &this
}

// GetSlug returns the Slug field value
func (o *GetBuyerCatalogListingAvailabilityResponse) GetSlug() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Slug
}

// GetSlugOk returns a tuple with the Slug field value
// and a boolean to check if the value has been set.
func (o *GetBuyerCatalogListingAvailabilityResponse) GetSlugOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Slug, true
}

// SetSlug sets field value
func (o *GetBuyerCatalogListingAvailabilityResponse) SetSlug(v string) {
	o.Slug = v
}

// GetAvailable returns the Available field value
func (o *GetBuyerCatalogListingAvailabilityResponse) GetAvailable() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Available
}

// GetAvailableOk returns a tuple with the Available field value
// and a boolean to check if the value has been set.
func (o *GetBuyerCatalogListingAvailabilityResponse) GetAvailableOk() (*bool, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Available, true
}

// SetAvailable sets field value
func (o *GetBuyerCatalogListingAvailabilityResponse) SetAvailable(v bool) {
	o.Available = v
}

// GetQuantityAvailable returns the QuantityAvailable field value
func (o *GetBuyerCatalogListingAvailabilityResponse) GetQuantityAvailable() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.QuantityAvailable
}

// GetQuantityAvailableOk returns a tuple with the QuantityAvailable field value
// and a boolean to check if the value has been set.
func (o *GetBuyerCatalogListingAvailabilityResponse) GetQuantityAvailableOk() (*float32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.QuantityAvailable, true
}

// SetQuantityAvailable sets field value
func (o *GetBuyerCatalogListingAvailabilityResponse) SetQuantityAvailable(v float32) {
	o.QuantityAvailable = v
}

// GetPriceCents returns the PriceCents field value
func (o *GetBuyerCatalogListingAvailabilityResponse) GetPriceCents() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.PriceCents
}

// GetPriceCentsOk returns a tuple with the PriceCents field value
// and a boolean to check if the value has been set.
func (o *GetBuyerCatalogListingAvailabilityResponse) GetPriceCentsOk() (*float32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.PriceCents, true
}

// SetPriceCents sets field value
func (o *GetBuyerCatalogListingAvailabilityResponse) SetPriceCents(v float32) {
	o.PriceCents = v
}

// GetCurrency returns the Currency field value
func (o *GetBuyerCatalogListingAvailabilityResponse) GetCurrency() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Currency
}

// GetCurrencyOk returns a tuple with the Currency field value
// and a boolean to check if the value has been set.
func (o *GetBuyerCatalogListingAvailabilityResponse) GetCurrencyOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Currency, true
}

// SetCurrency sets field value
func (o *GetBuyerCatalogListingAvailabilityResponse) SetCurrency(v string) {
	o.Currency = v
}

// GetStatus returns the Status field value
func (o *GetBuyerCatalogListingAvailabilityResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *GetBuyerCatalogListingAvailabilityResponse) GetStatusOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *GetBuyerCatalogListingAvailabilityResponse) SetStatus(v string) {
	o.Status = v
}

func (o GetBuyerCatalogListingAvailabilityResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["slug"] = o.Slug
	}
	if true {
		toSerialize["available"] = o.Available
	}
	if true {
		toSerialize["quantityAvailable"] = o.QuantityAvailable
	}
	if true {
		toSerialize["priceCents"] = o.PriceCents
	}
	if true {
		toSerialize["currency"] = o.Currency
	}
	if true {
		toSerialize["status"] = o.Status
	}
	return json.Marshal(toSerialize)
}

type NullableGetBuyerCatalogListingAvailabilityResponse struct {
	value *GetBuyerCatalogListingAvailabilityResponse
	isSet bool
}

func (v NullableGetBuyerCatalogListingAvailabilityResponse) Get() *GetBuyerCatalogListingAvailabilityResponse {
	return v.value
}

func (v *NullableGetBuyerCatalogListingAvailabilityResponse) Set(val *GetBuyerCatalogListingAvailabilityResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetBuyerCatalogListingAvailabilityResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetBuyerCatalogListingAvailabilityResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetBuyerCatalogListingAvailabilityResponse(val *GetBuyerCatalogListingAvailabilityResponse) *NullableGetBuyerCatalogListingAvailabilityResponse {
	return &NullableGetBuyerCatalogListingAvailabilityResponse{value: val, isSet: true}
}

func (v NullableGetBuyerCatalogListingAvailabilityResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetBuyerCatalogListingAvailabilityResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


