/*
Crossly Buyer API

The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crossly_buyer

import (
	"encoding/json"
)

// DeleteAiKeyResponse struct for DeleteAiKeyResponse
type DeleteAiKeyResponse struct {
	Success bool `json:"success"`
}

// NewDeleteAiKeyResponse instantiates a new DeleteAiKeyResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteAiKeyResponse(success bool) *DeleteAiKeyResponse {
	this := DeleteAiKeyResponse{}
	this.Success = success
	return &this
}

// NewDeleteAiKeyResponseWithDefaults instantiates a new DeleteAiKeyResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteAiKeyResponseWithDefaults() *DeleteAiKeyResponse {
	this := DeleteAiKeyResponse{}
	return &this
}

// GetSuccess returns the Success field value
func (o *DeleteAiKeyResponse) GetSuccess() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Success
}

// GetSuccessOk returns a tuple with the Success field value
// and a boolean to check if the value has been set.
func (o *DeleteAiKeyResponse) GetSuccessOk() (*bool, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Success, true
}

// SetSuccess sets field value
func (o *DeleteAiKeyResponse) SetSuccess(v bool) {
	o.Success = v
}

func (o DeleteAiKeyResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["success"] = o.Success
	}
	return json.Marshal(toSerialize)
}

type NullableDeleteAiKeyResponse struct {
	value *DeleteAiKeyResponse
	isSet bool
}

func (v NullableDeleteAiKeyResponse) Get() *DeleteAiKeyResponse {
	return v.value
}

func (v *NullableDeleteAiKeyResponse) Set(val *DeleteAiKeyResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteAiKeyResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteAiKeyResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteAiKeyResponse(val *DeleteAiKeyResponse) *NullableDeleteAiKeyResponse {
	return &NullableDeleteAiKeyResponse{value: val, isSet: true}
}

func (v NullableDeleteAiKeyResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteAiKeyResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


