/*
Crossly Buyer API

The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crossly_buyer

import (
	"encoding/json"
)

// UpdateInventoryResponse struct for UpdateInventoryResponse
type UpdateInventoryResponse struct {
	Category NullableListInventoryItemCategory `json:"category,omitempty"`
}

// NewUpdateInventoryResponse instantiates a new UpdateInventoryResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateInventoryResponse() *UpdateInventoryResponse {
	this := UpdateInventoryResponse{}
	return &this
}

// NewUpdateInventoryResponseWithDefaults instantiates a new UpdateInventoryResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateInventoryResponseWithDefaults() *UpdateInventoryResponse {
	this := UpdateInventoryResponse{}
	return &this
}

// GetCategory returns the Category field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateInventoryResponse) GetCategory() ListInventoryItemCategory {
	if o == nil || o.Category.Get() == nil {
		var ret ListInventoryItemCategory
		return ret
	}
	return *o.Category.Get()
}

// GetCategoryOk returns a tuple with the Category field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateInventoryResponse) GetCategoryOk() (*ListInventoryItemCategory, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Category.Get(), o.Category.IsSet()
}

// HasCategory returns a boolean if a field has been set.
func (o *UpdateInventoryResponse) HasCategory() bool {
	if o != nil && o.Category.IsSet() {
		return true
	}

	return false
}

// SetCategory gets a reference to the given NullableListInventoryItemCategory and assigns it to the Category field.
func (o *UpdateInventoryResponse) SetCategory(v ListInventoryItemCategory) {
	o.Category.Set(&v)
}
// SetCategoryNil sets the value for Category to be an explicit nil
func (o *UpdateInventoryResponse) SetCategoryNil() {
	o.Category.Set(nil)
}

// UnsetCategory ensures that no value is present for Category, not even an explicit nil
func (o *UpdateInventoryResponse) UnsetCategory() {
	o.Category.Unset()
}

func (o UpdateInventoryResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Category.IsSet() {
		toSerialize["category"] = o.Category.Get()
	}
	return json.Marshal(toSerialize)
}

type NullableUpdateInventoryResponse struct {
	value *UpdateInventoryResponse
	isSet bool
}

func (v NullableUpdateInventoryResponse) Get() *UpdateInventoryResponse {
	return v.value
}

func (v *NullableUpdateInventoryResponse) Set(val *UpdateInventoryResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateInventoryResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateInventoryResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateInventoryResponse(val *UpdateInventoryResponse) *NullableUpdateInventoryResponse {
	return &NullableUpdateInventoryResponse{value: val, isSet: true}
}

func (v NullableUpdateInventoryResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateInventoryResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


