/*
Crossly Buyer API

The buyer-facing Crossly API — cart, orders, wishlists, offers, cashback. A DIFFERENT principal from the seller API: authenticated by a buyer OAuth token scoped `buyer:*` and resolved by `resolveBuyer`. A seller Personal Access Token will NOT authenticate these endpoints.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package crossly_buyer

import (
	"encoding/json"
	"time"
)

// GetInboxResponseMessages struct for GetInboxResponseMessages
type GetInboxResponseMessages struct {
	Id string `json:"id"`
	VideoUrl NullableString `json:"videoUrl,omitempty"`
	SyncedAt NullableTime `json:"syncedAt,omitempty"`
	SentAt time.Time `json:"sentAt"`
	Body NullableString `json:"body,omitempty"`
	ConversationId string `json:"conversationId"`
	PlatformMessageId NullableString `json:"platformMessageId,omitempty"`
	Sender string `json:"sender"`
	Attachments []string `json:"attachments,omitempty"`
	AiIntent NullableString `json:"aiIntent,omitempty"`
	AiUrgency NullableString `json:"aiUrgency,omitempty"`
	AiScamScore NullableFloat32 `json:"aiScamScore,omitempty"`
	AiSuggestedReply NullableString `json:"aiSuggestedReply,omitempty"`
	AiTriagedAt NullableTime `json:"aiTriagedAt,omitempty"`
	StickerId NullableString `json:"stickerId,omitempty"`
	GifUrl NullableString `json:"gifUrl,omitempty"`
	VideoThumbUrl NullableString `json:"videoThumbUrl,omitempty"`
	VoiceUrl NullableString `json:"voiceUrl,omitempty"`
	VoiceDurationSeconds NullableFloat32 `json:"voiceDurationSeconds,omitempty"`
}

// NewGetInboxResponseMessages instantiates a new GetInboxResponseMessages object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetInboxResponseMessages(id string, sentAt time.Time, conversationId string, sender string) *GetInboxResponseMessages {
	this := GetInboxResponseMessages{}
	this.Id = id
	this.SentAt = sentAt
	this.ConversationId = conversationId
	this.Sender = sender
	return &this
}

// NewGetInboxResponseMessagesWithDefaults instantiates a new GetInboxResponseMessages object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetInboxResponseMessagesWithDefaults() *GetInboxResponseMessages {
	this := GetInboxResponseMessages{}
	return &this
}

// GetId returns the Id field value
func (o *GetInboxResponseMessages) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *GetInboxResponseMessages) GetIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *GetInboxResponseMessages) SetId(v string) {
	o.Id = v
}

// GetVideoUrl returns the VideoUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetInboxResponseMessages) GetVideoUrl() string {
	if o == nil || o.VideoUrl.Get() == nil {
		var ret string
		return ret
	}
	return *o.VideoUrl.Get()
}

// GetVideoUrlOk returns a tuple with the VideoUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetInboxResponseMessages) GetVideoUrlOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.VideoUrl.Get(), o.VideoUrl.IsSet()
}

// HasVideoUrl returns a boolean if a field has been set.
func (o *GetInboxResponseMessages) HasVideoUrl() bool {
	if o != nil && o.VideoUrl.IsSet() {
		return true
	}

	return false
}

// SetVideoUrl gets a reference to the given NullableString and assigns it to the VideoUrl field.
func (o *GetInboxResponseMessages) SetVideoUrl(v string) {
	o.VideoUrl.Set(&v)
}
// SetVideoUrlNil sets the value for VideoUrl to be an explicit nil
func (o *GetInboxResponseMessages) SetVideoUrlNil() {
	o.VideoUrl.Set(nil)
}

// UnsetVideoUrl ensures that no value is present for VideoUrl, not even an explicit nil
func (o *GetInboxResponseMessages) UnsetVideoUrl() {
	o.VideoUrl.Unset()
}

// GetSyncedAt returns the SyncedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetInboxResponseMessages) GetSyncedAt() time.Time {
	if o == nil || o.SyncedAt.Get() == nil {
		var ret time.Time
		return ret
	}
	return *o.SyncedAt.Get()
}

// GetSyncedAtOk returns a tuple with the SyncedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetInboxResponseMessages) GetSyncedAtOk() (*time.Time, bool) {
	if o == nil  {
		return nil, false
	}
	return o.SyncedAt.Get(), o.SyncedAt.IsSet()
}

// HasSyncedAt returns a boolean if a field has been set.
func (o *GetInboxResponseMessages) HasSyncedAt() bool {
	if o != nil && o.SyncedAt.IsSet() {
		return true
	}

	return false
}

// SetSyncedAt gets a reference to the given NullableTime and assigns it to the SyncedAt field.
func (o *GetInboxResponseMessages) SetSyncedAt(v time.Time) {
	o.SyncedAt.Set(&v)
}
// SetSyncedAtNil sets the value for SyncedAt to be an explicit nil
func (o *GetInboxResponseMessages) SetSyncedAtNil() {
	o.SyncedAt.Set(nil)
}

// UnsetSyncedAt ensures that no value is present for SyncedAt, not even an explicit nil
func (o *GetInboxResponseMessages) UnsetSyncedAt() {
	o.SyncedAt.Unset()
}

// GetSentAt returns the SentAt field value
func (o *GetInboxResponseMessages) GetSentAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.SentAt
}

// GetSentAtOk returns a tuple with the SentAt field value
// and a boolean to check if the value has been set.
func (o *GetInboxResponseMessages) GetSentAtOk() (*time.Time, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.SentAt, true
}

// SetSentAt sets field value
func (o *GetInboxResponseMessages) SetSentAt(v time.Time) {
	o.SentAt = v
}

// GetBody returns the Body field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetInboxResponseMessages) GetBody() string {
	if o == nil || o.Body.Get() == nil {
		var ret string
		return ret
	}
	return *o.Body.Get()
}

// GetBodyOk returns a tuple with the Body field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetInboxResponseMessages) GetBodyOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.Body.Get(), o.Body.IsSet()
}

// HasBody returns a boolean if a field has been set.
func (o *GetInboxResponseMessages) HasBody() bool {
	if o != nil && o.Body.IsSet() {
		return true
	}

	return false
}

// SetBody gets a reference to the given NullableString and assigns it to the Body field.
func (o *GetInboxResponseMessages) SetBody(v string) {
	o.Body.Set(&v)
}
// SetBodyNil sets the value for Body to be an explicit nil
func (o *GetInboxResponseMessages) SetBodyNil() {
	o.Body.Set(nil)
}

// UnsetBody ensures that no value is present for Body, not even an explicit nil
func (o *GetInboxResponseMessages) UnsetBody() {
	o.Body.Unset()
}

// GetConversationId returns the ConversationId field value
func (o *GetInboxResponseMessages) GetConversationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ConversationId
}

// GetConversationIdOk returns a tuple with the ConversationId field value
// and a boolean to check if the value has been set.
func (o *GetInboxResponseMessages) GetConversationIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.ConversationId, true
}

// SetConversationId sets field value
func (o *GetInboxResponseMessages) SetConversationId(v string) {
	o.ConversationId = v
}

// GetPlatformMessageId returns the PlatformMessageId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetInboxResponseMessages) GetPlatformMessageId() string {
	if o == nil || o.PlatformMessageId.Get() == nil {
		var ret string
		return ret
	}
	return *o.PlatformMessageId.Get()
}

// GetPlatformMessageIdOk returns a tuple with the PlatformMessageId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetInboxResponseMessages) GetPlatformMessageIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.PlatformMessageId.Get(), o.PlatformMessageId.IsSet()
}

// HasPlatformMessageId returns a boolean if a field has been set.
func (o *GetInboxResponseMessages) HasPlatformMessageId() bool {
	if o != nil && o.PlatformMessageId.IsSet() {
		return true
	}

	return false
}

// SetPlatformMessageId gets a reference to the given NullableString and assigns it to the PlatformMessageId field.
func (o *GetInboxResponseMessages) SetPlatformMessageId(v string) {
	o.PlatformMessageId.Set(&v)
}
// SetPlatformMessageIdNil sets the value for PlatformMessageId to be an explicit nil
func (o *GetInboxResponseMessages) SetPlatformMessageIdNil() {
	o.PlatformMessageId.Set(nil)
}

// UnsetPlatformMessageId ensures that no value is present for PlatformMessageId, not even an explicit nil
func (o *GetInboxResponseMessages) UnsetPlatformMessageId() {
	o.PlatformMessageId.Unset()
}

// GetSender returns the Sender field value
func (o *GetInboxResponseMessages) GetSender() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Sender
}

// GetSenderOk returns a tuple with the Sender field value
// and a boolean to check if the value has been set.
func (o *GetInboxResponseMessages) GetSenderOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Sender, true
}

// SetSender sets field value
func (o *GetInboxResponseMessages) SetSender(v string) {
	o.Sender = v
}

// GetAttachments returns the Attachments field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetInboxResponseMessages) GetAttachments() []string {
	if o == nil  {
		var ret []string
		return ret
	}
	return o.Attachments
}

// GetAttachmentsOk returns a tuple with the Attachments field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetInboxResponseMessages) GetAttachmentsOk() ([]string, bool) {
	if o == nil || o.Attachments == nil {
		return nil, false
	}
	return o.Attachments, true
}

// HasAttachments returns a boolean if a field has been set.
func (o *GetInboxResponseMessages) HasAttachments() bool {
	if o != nil && o.Attachments != nil {
		return true
	}

	return false
}

// SetAttachments gets a reference to the given []string and assigns it to the Attachments field.
func (o *GetInboxResponseMessages) SetAttachments(v []string) {
	o.Attachments = v
}

// GetAiIntent returns the AiIntent field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetInboxResponseMessages) GetAiIntent() string {
	if o == nil || o.AiIntent.Get() == nil {
		var ret string
		return ret
	}
	return *o.AiIntent.Get()
}

// GetAiIntentOk returns a tuple with the AiIntent field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetInboxResponseMessages) GetAiIntentOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.AiIntent.Get(), o.AiIntent.IsSet()
}

// HasAiIntent returns a boolean if a field has been set.
func (o *GetInboxResponseMessages) HasAiIntent() bool {
	if o != nil && o.AiIntent.IsSet() {
		return true
	}

	return false
}

// SetAiIntent gets a reference to the given NullableString and assigns it to the AiIntent field.
func (o *GetInboxResponseMessages) SetAiIntent(v string) {
	o.AiIntent.Set(&v)
}
// SetAiIntentNil sets the value for AiIntent to be an explicit nil
func (o *GetInboxResponseMessages) SetAiIntentNil() {
	o.AiIntent.Set(nil)
}

// UnsetAiIntent ensures that no value is present for AiIntent, not even an explicit nil
func (o *GetInboxResponseMessages) UnsetAiIntent() {
	o.AiIntent.Unset()
}

// GetAiUrgency returns the AiUrgency field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetInboxResponseMessages) GetAiUrgency() string {
	if o == nil || o.AiUrgency.Get() == nil {
		var ret string
		return ret
	}
	return *o.AiUrgency.Get()
}

// GetAiUrgencyOk returns a tuple with the AiUrgency field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetInboxResponseMessages) GetAiUrgencyOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.AiUrgency.Get(), o.AiUrgency.IsSet()
}

// HasAiUrgency returns a boolean if a field has been set.
func (o *GetInboxResponseMessages) HasAiUrgency() bool {
	if o != nil && o.AiUrgency.IsSet() {
		return true
	}

	return false
}

// SetAiUrgency gets a reference to the given NullableString and assigns it to the AiUrgency field.
func (o *GetInboxResponseMessages) SetAiUrgency(v string) {
	o.AiUrgency.Set(&v)
}
// SetAiUrgencyNil sets the value for AiUrgency to be an explicit nil
func (o *GetInboxResponseMessages) SetAiUrgencyNil() {
	o.AiUrgency.Set(nil)
}

// UnsetAiUrgency ensures that no value is present for AiUrgency, not even an explicit nil
func (o *GetInboxResponseMessages) UnsetAiUrgency() {
	o.AiUrgency.Unset()
}

// GetAiScamScore returns the AiScamScore field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetInboxResponseMessages) GetAiScamScore() float32 {
	if o == nil || o.AiScamScore.Get() == nil {
		var ret float32
		return ret
	}
	return *o.AiScamScore.Get()
}

// GetAiScamScoreOk returns a tuple with the AiScamScore field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetInboxResponseMessages) GetAiScamScoreOk() (*float32, bool) {
	if o == nil  {
		return nil, false
	}
	return o.AiScamScore.Get(), o.AiScamScore.IsSet()
}

// HasAiScamScore returns a boolean if a field has been set.
func (o *GetInboxResponseMessages) HasAiScamScore() bool {
	if o != nil && o.AiScamScore.IsSet() {
		return true
	}

	return false
}

// SetAiScamScore gets a reference to the given NullableFloat32 and assigns it to the AiScamScore field.
func (o *GetInboxResponseMessages) SetAiScamScore(v float32) {
	o.AiScamScore.Set(&v)
}
// SetAiScamScoreNil sets the value for AiScamScore to be an explicit nil
func (o *GetInboxResponseMessages) SetAiScamScoreNil() {
	o.AiScamScore.Set(nil)
}

// UnsetAiScamScore ensures that no value is present for AiScamScore, not even an explicit nil
func (o *GetInboxResponseMessages) UnsetAiScamScore() {
	o.AiScamScore.Unset()
}

// GetAiSuggestedReply returns the AiSuggestedReply field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetInboxResponseMessages) GetAiSuggestedReply() string {
	if o == nil || o.AiSuggestedReply.Get() == nil {
		var ret string
		return ret
	}
	return *o.AiSuggestedReply.Get()
}

// GetAiSuggestedReplyOk returns a tuple with the AiSuggestedReply field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetInboxResponseMessages) GetAiSuggestedReplyOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.AiSuggestedReply.Get(), o.AiSuggestedReply.IsSet()
}

// HasAiSuggestedReply returns a boolean if a field has been set.
func (o *GetInboxResponseMessages) HasAiSuggestedReply() bool {
	if o != nil && o.AiSuggestedReply.IsSet() {
		return true
	}

	return false
}

// SetAiSuggestedReply gets a reference to the given NullableString and assigns it to the AiSuggestedReply field.
func (o *GetInboxResponseMessages) SetAiSuggestedReply(v string) {
	o.AiSuggestedReply.Set(&v)
}
// SetAiSuggestedReplyNil sets the value for AiSuggestedReply to be an explicit nil
func (o *GetInboxResponseMessages) SetAiSuggestedReplyNil() {
	o.AiSuggestedReply.Set(nil)
}

// UnsetAiSuggestedReply ensures that no value is present for AiSuggestedReply, not even an explicit nil
func (o *GetInboxResponseMessages) UnsetAiSuggestedReply() {
	o.AiSuggestedReply.Unset()
}

// GetAiTriagedAt returns the AiTriagedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetInboxResponseMessages) GetAiTriagedAt() time.Time {
	if o == nil || o.AiTriagedAt.Get() == nil {
		var ret time.Time
		return ret
	}
	return *o.AiTriagedAt.Get()
}

// GetAiTriagedAtOk returns a tuple with the AiTriagedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetInboxResponseMessages) GetAiTriagedAtOk() (*time.Time, bool) {
	if o == nil  {
		return nil, false
	}
	return o.AiTriagedAt.Get(), o.AiTriagedAt.IsSet()
}

// HasAiTriagedAt returns a boolean if a field has been set.
func (o *GetInboxResponseMessages) HasAiTriagedAt() bool {
	if o != nil && o.AiTriagedAt.IsSet() {
		return true
	}

	return false
}

// SetAiTriagedAt gets a reference to the given NullableTime and assigns it to the AiTriagedAt field.
func (o *GetInboxResponseMessages) SetAiTriagedAt(v time.Time) {
	o.AiTriagedAt.Set(&v)
}
// SetAiTriagedAtNil sets the value for AiTriagedAt to be an explicit nil
func (o *GetInboxResponseMessages) SetAiTriagedAtNil() {
	o.AiTriagedAt.Set(nil)
}

// UnsetAiTriagedAt ensures that no value is present for AiTriagedAt, not even an explicit nil
func (o *GetInboxResponseMessages) UnsetAiTriagedAt() {
	o.AiTriagedAt.Unset()
}

// GetStickerId returns the StickerId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetInboxResponseMessages) GetStickerId() string {
	if o == nil || o.StickerId.Get() == nil {
		var ret string
		return ret
	}
	return *o.StickerId.Get()
}

// GetStickerIdOk returns a tuple with the StickerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetInboxResponseMessages) GetStickerIdOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.StickerId.Get(), o.StickerId.IsSet()
}

// HasStickerId returns a boolean if a field has been set.
func (o *GetInboxResponseMessages) HasStickerId() bool {
	if o != nil && o.StickerId.IsSet() {
		return true
	}

	return false
}

// SetStickerId gets a reference to the given NullableString and assigns it to the StickerId field.
func (o *GetInboxResponseMessages) SetStickerId(v string) {
	o.StickerId.Set(&v)
}
// SetStickerIdNil sets the value for StickerId to be an explicit nil
func (o *GetInboxResponseMessages) SetStickerIdNil() {
	o.StickerId.Set(nil)
}

// UnsetStickerId ensures that no value is present for StickerId, not even an explicit nil
func (o *GetInboxResponseMessages) UnsetStickerId() {
	o.StickerId.Unset()
}

// GetGifUrl returns the GifUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetInboxResponseMessages) GetGifUrl() string {
	if o == nil || o.GifUrl.Get() == nil {
		var ret string
		return ret
	}
	return *o.GifUrl.Get()
}

// GetGifUrlOk returns a tuple with the GifUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetInboxResponseMessages) GetGifUrlOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.GifUrl.Get(), o.GifUrl.IsSet()
}

// HasGifUrl returns a boolean if a field has been set.
func (o *GetInboxResponseMessages) HasGifUrl() bool {
	if o != nil && o.GifUrl.IsSet() {
		return true
	}

	return false
}

// SetGifUrl gets a reference to the given NullableString and assigns it to the GifUrl field.
func (o *GetInboxResponseMessages) SetGifUrl(v string) {
	o.GifUrl.Set(&v)
}
// SetGifUrlNil sets the value for GifUrl to be an explicit nil
func (o *GetInboxResponseMessages) SetGifUrlNil() {
	o.GifUrl.Set(nil)
}

// UnsetGifUrl ensures that no value is present for GifUrl, not even an explicit nil
func (o *GetInboxResponseMessages) UnsetGifUrl() {
	o.GifUrl.Unset()
}

// GetVideoThumbUrl returns the VideoThumbUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetInboxResponseMessages) GetVideoThumbUrl() string {
	if o == nil || o.VideoThumbUrl.Get() == nil {
		var ret string
		return ret
	}
	return *o.VideoThumbUrl.Get()
}

// GetVideoThumbUrlOk returns a tuple with the VideoThumbUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetInboxResponseMessages) GetVideoThumbUrlOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.VideoThumbUrl.Get(), o.VideoThumbUrl.IsSet()
}

// HasVideoThumbUrl returns a boolean if a field has been set.
func (o *GetInboxResponseMessages) HasVideoThumbUrl() bool {
	if o != nil && o.VideoThumbUrl.IsSet() {
		return true
	}

	return false
}

// SetVideoThumbUrl gets a reference to the given NullableString and assigns it to the VideoThumbUrl field.
func (o *GetInboxResponseMessages) SetVideoThumbUrl(v string) {
	o.VideoThumbUrl.Set(&v)
}
// SetVideoThumbUrlNil sets the value for VideoThumbUrl to be an explicit nil
func (o *GetInboxResponseMessages) SetVideoThumbUrlNil() {
	o.VideoThumbUrl.Set(nil)
}

// UnsetVideoThumbUrl ensures that no value is present for VideoThumbUrl, not even an explicit nil
func (o *GetInboxResponseMessages) UnsetVideoThumbUrl() {
	o.VideoThumbUrl.Unset()
}

// GetVoiceUrl returns the VoiceUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetInboxResponseMessages) GetVoiceUrl() string {
	if o == nil || o.VoiceUrl.Get() == nil {
		var ret string
		return ret
	}
	return *o.VoiceUrl.Get()
}

// GetVoiceUrlOk returns a tuple with the VoiceUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetInboxResponseMessages) GetVoiceUrlOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return o.VoiceUrl.Get(), o.VoiceUrl.IsSet()
}

// HasVoiceUrl returns a boolean if a field has been set.
func (o *GetInboxResponseMessages) HasVoiceUrl() bool {
	if o != nil && o.VoiceUrl.IsSet() {
		return true
	}

	return false
}

// SetVoiceUrl gets a reference to the given NullableString and assigns it to the VoiceUrl field.
func (o *GetInboxResponseMessages) SetVoiceUrl(v string) {
	o.VoiceUrl.Set(&v)
}
// SetVoiceUrlNil sets the value for VoiceUrl to be an explicit nil
func (o *GetInboxResponseMessages) SetVoiceUrlNil() {
	o.VoiceUrl.Set(nil)
}

// UnsetVoiceUrl ensures that no value is present for VoiceUrl, not even an explicit nil
func (o *GetInboxResponseMessages) UnsetVoiceUrl() {
	o.VoiceUrl.Unset()
}

// GetVoiceDurationSeconds returns the VoiceDurationSeconds field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetInboxResponseMessages) GetVoiceDurationSeconds() float32 {
	if o == nil || o.VoiceDurationSeconds.Get() == nil {
		var ret float32
		return ret
	}
	return *o.VoiceDurationSeconds.Get()
}

// GetVoiceDurationSecondsOk returns a tuple with the VoiceDurationSeconds field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetInboxResponseMessages) GetVoiceDurationSecondsOk() (*float32, bool) {
	if o == nil  {
		return nil, false
	}
	return o.VoiceDurationSeconds.Get(), o.VoiceDurationSeconds.IsSet()
}

// HasVoiceDurationSeconds returns a boolean if a field has been set.
func (o *GetInboxResponseMessages) HasVoiceDurationSeconds() bool {
	if o != nil && o.VoiceDurationSeconds.IsSet() {
		return true
	}

	return false
}

// SetVoiceDurationSeconds gets a reference to the given NullableFloat32 and assigns it to the VoiceDurationSeconds field.
func (o *GetInboxResponseMessages) SetVoiceDurationSeconds(v float32) {
	o.VoiceDurationSeconds.Set(&v)
}
// SetVoiceDurationSecondsNil sets the value for VoiceDurationSeconds to be an explicit nil
func (o *GetInboxResponseMessages) SetVoiceDurationSecondsNil() {
	o.VoiceDurationSeconds.Set(nil)
}

// UnsetVoiceDurationSeconds ensures that no value is present for VoiceDurationSeconds, not even an explicit nil
func (o *GetInboxResponseMessages) UnsetVoiceDurationSeconds() {
	o.VoiceDurationSeconds.Unset()
}

func (o GetInboxResponseMessages) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	if o.VideoUrl.IsSet() {
		toSerialize["videoUrl"] = o.VideoUrl.Get()
	}
	if o.SyncedAt.IsSet() {
		toSerialize["syncedAt"] = o.SyncedAt.Get()
	}
	if true {
		toSerialize["sentAt"] = o.SentAt
	}
	if o.Body.IsSet() {
		toSerialize["body"] = o.Body.Get()
	}
	if true {
		toSerialize["conversationId"] = o.ConversationId
	}
	if o.PlatformMessageId.IsSet() {
		toSerialize["platformMessageId"] = o.PlatformMessageId.Get()
	}
	if true {
		toSerialize["sender"] = o.Sender
	}
	if o.Attachments != nil {
		toSerialize["attachments"] = o.Attachments
	}
	if o.AiIntent.IsSet() {
		toSerialize["aiIntent"] = o.AiIntent.Get()
	}
	if o.AiUrgency.IsSet() {
		toSerialize["aiUrgency"] = o.AiUrgency.Get()
	}
	if o.AiScamScore.IsSet() {
		toSerialize["aiScamScore"] = o.AiScamScore.Get()
	}
	if o.AiSuggestedReply.IsSet() {
		toSerialize["aiSuggestedReply"] = o.AiSuggestedReply.Get()
	}
	if o.AiTriagedAt.IsSet() {
		toSerialize["aiTriagedAt"] = o.AiTriagedAt.Get()
	}
	if o.StickerId.IsSet() {
		toSerialize["stickerId"] = o.StickerId.Get()
	}
	if o.GifUrl.IsSet() {
		toSerialize["gifUrl"] = o.GifUrl.Get()
	}
	if o.VideoThumbUrl.IsSet() {
		toSerialize["videoThumbUrl"] = o.VideoThumbUrl.Get()
	}
	if o.VoiceUrl.IsSet() {
		toSerialize["voiceUrl"] = o.VoiceUrl.Get()
	}
	if o.VoiceDurationSeconds.IsSet() {
		toSerialize["voiceDurationSeconds"] = o.VoiceDurationSeconds.Get()
	}
	return json.Marshal(toSerialize)
}

type NullableGetInboxResponseMessages struct {
	value *GetInboxResponseMessages
	isSet bool
}

func (v NullableGetInboxResponseMessages) Get() *GetInboxResponseMessages {
	return v.value
}

func (v *NullableGetInboxResponseMessages) Set(val *GetInboxResponseMessages) {
	v.value = val
	v.isSet = true
}

func (v NullableGetInboxResponseMessages) IsSet() bool {
	return v.isSet
}

func (v *NullableGetInboxResponseMessages) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetInboxResponseMessages(val *GetInboxResponseMessages) *NullableGetInboxResponseMessages {
	return &NullableGetInboxResponseMessages{value: val, isSet: true}
}

func (v NullableGetInboxResponseMessages) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetInboxResponseMessages) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


